### ISSUE TITLE
Sign Up - Sign In pages : check for consistency

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#107]
I looked at both pages and we seem to use both Sign In and Log In. I think we need to use only one term. since we are using **Sign Up to register**, it will be logic to use **Sign In to connect.**

**Comment by joshi1983** [comment]
I agree that "Sign In" instead of "Log In" sounds better and more consistent.

By weekend, a developer will be picked for this p1(1 week) issue so that it is done by Dec. 21.

**Comment by joshi1983** [comment]
I'm closing this because the wording has been updated to be consistent.  I think that covers the work requested by this issue.
