### ISSUE TITLE
Contact form : Send messages to an accesslocator.com email address

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#112]
- [ ] Message to be sent to info@accesslocator.com for now.

- [ ] Josh, please create info@accesslocator.com 
I think I will be able to access it with gmail.

**Comment by Blandine-AA** [comment]
Related to issue #88

**Comment by joshi1983** [comment]
The basic requirement to send email messages from the contact form to us is complete.  This requirement to have an info@accesslocator.com account is blocked by #82.

**Comment by joshi1983** [comment]
I assigned #112 to Blandine because it is blocked by #82 which is also waiting on a task from Blandine.

**Comment by joshi1983** [comment]
I'm closing this for the same reason as closing #82.  We know that JMCC isn't willing to give us email accounts from their organization and we don't have money for an email service.  Having @accesslocator.com will look a little more professional but there are too many other things with higher priority to implement this any time soon.
