### ISSUE TITLE
Home page : problem with categories layout

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#113]
The lines in the categories selection are not visible anymore, and they are now smaller and rectangle. 

The lines need to be visible to differentiate the categories! Also the previous size and square shape ere much better. 

Probably a bug! Can all that be put back?

The alphabetical order is correct!

**Comment by joshi1983** [comment]
When do you think these undesirable changes happened?  

The Sign in / Sign up button was removedwhen you're signed in December 10.
The "Windsor, Ontario, Canada" input was added December 8.

I'll add the white borders again.

**Comment by joshi1983** [comment]
Is this how you want it to look?  I added some borders and increased the font size.
![image](https://cloud.githubusercontent.com/assets/11838191/21248369/917993b6-c304-11e6-90ff-63fe6e9ee1cc.png)

**Comment by joshi1983** [comment]
I'll remove the border around the very outer edge as requested at the meeting.

It would be nice to get mockups of the elements that show up when hovering so the text isn't too small and so it looks precisely the way you want.

**Comment by joshi1983** [comment]
I made the borders sharper:
![image](https://cloud.githubusercontent.com/assets/11838191/21288303/6d9171ae-c44d-11e6-9851-1c0acf29c85c.png)

During our Friday meeting, the idea of making the tiles square was suggested.  I'll experiment with making them closer to square and see if it looks better overall.  It may improve the look of wrapped text.

**Comment by joshi1983** [comment]
It looks like this now:
![image](https://cloud.githubusercontent.com/assets/11838191/21290352/c293e088-c484-11e6-9a93-652d4ed4acd6.png)

I think this is pretty close to what you wanted.  The hover text size and appearance can be handled with a different issue.
