### ISSUE TITLE
Home page : create new background image for home page

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#117]
Create a new image for the home page background.

A single photo was mentioned and trying to be consistent with the colours while still looking natural.

A high resolution version would be good such as over 1500 pixels width.

**Comment by joshi1983** [comment]
This is the new background image that Areeba sent me.
![accessbility app background copy](https://cloud.githubusercontent.com/assets/11838191/21542265/9f4f47c0-cd8a-11e6-8106-fb3c86e92134.jpg)

**Comment by joshi1983** [comment]
I replaced the home page background with the blurrier one provided by Areeba.

**Comment by Blandine-AA** [comment]
I prefer the original one. this one kind of make me feel dizzy. It feel less clear than the original one. 

I think for now we will just go with or the other for the first round of testing and not put more work on it until we get some feedback. We can have both background tested

**Comment by Blandine-AA** [comment]
At the last meeting, we talked about reversing this to the original background. Can this be updated in the next couple of days?

**Comment by joshi1983** [comment]
I thought the conclusion we came to was that it wasn't very important for the next few days and we could wait until uncopyrighten source images are taken.  We talked about how the clearer version used previously can get distracting to vision impaired users who have trouble reading the location tags/categories so there are weaknesses to both the old and new home page.

**Comment by joshi1983** [comment]
I ended up mixing the old and new background images together for the uncollapsed layout of the home page since I was worried that the blurriness could leave a negative impression on reviewers.  The blurry background image is used at every resolution under 1200 so the sharp edges and fine details don't distract readers of foreground text.

**Comment by Blandine-AA** [comment]
@joshi1983 , @areebakamal , it seems to me that we are pretty happy with the current homepage background. So, we can close this issue. correct?

**Comment by joshi1983** [comment]
I suggest not closing because we're still using a potentially copyrighten material.  It doesn't seem as high priority as several other issues but we'll keep risking a copyright complaint until the home page is replaced.  Replacing with an image made purely with our team's photos or properly licensed graphics was why this issue was created and that still isn't complete.

Part of our current home page is from:
http://www.richardmeier.com/wp-content/uploads/2014/07/P3.6UU.068C-1024x799.jpg

**Comment by areebakamal** [comment]
Does anyone know of a nice building with a big ramp?

**Comment by Blandine-AA** [comment]
@areebakamal , how big? Try the Toldo building at the university. It has quite a long ramp

**Comment by areebakamal** [comment]
Ok, I will try to take a good picture. I looked on Maps street view to check for ramps. Found a few but none are as nice as that building ramp that I used. Will post a couple pictures here for new choices for background.
If anyone has any other ideas for the homepage background besides a large building with a large ramp, feel free to comment here!

**Comment by areebakamal** [comment]
![background2 copxxxxy](https://cloud.githubusercontent.com/assets/23005093/25268922/918c81fe-2648-11e7-8246-2d41019ab959.jpg)

**Comment by joshi1983** [comment]
That looks pretty really good, @areebakamal.

Can you share all the source graphics on here in maybe a zip file?  If you have them before they were edited, that would be even better.  It looks like the colours for the main image have been edited a little.  

Is the marker and wheelchair graphics also yours or do you know what the copyright policies are on them?

**Comment by areebakamal** [comment]
Yeah I changed a lot of the colors to make it more blue toned like the current one, added some grass as it looked scarce in the original pic.

The blue marker is pretty universal. Even if I remake it by tracing, it would look the same. I could modify the shape so it's not an exact copy. 
The wheel chair pic is not mine, it's taken from: http://www.rehabmagazine.ca/featured-sidebar/the-other-seat/ 
Not sure about the copyright policy on this. I made it very low opacity. 

![20170420_124531](https://cloud.githubusercontent.com/assets/23005093/25294541/a43fa0b4-26ad-11e7-82b4-26fa45b14b8e.jpg)
![o-wheelchair1124-facebook](https://cloud.githubusercontent.com/assets/23005093/25294558/b10233ca-26ad-11e7-849f-c75c48c62526.jpg)
![location](https://cloud.githubusercontent.com/assets/23005093/25294565/b7ea50e6-26ad-11e7-9043-7baa87481d60.png)

**Comment by Blandine-AA** [comment]
@areebakamal , I don't think that there will be a problem with the wheelchair. First it is very settle as view, second it looks like any wheelchair within the millions that exist. So, not point of making too much fuzz about it. Looks great !

**Comment by joshi1983** [comment]
This work from @areebakamal was merged and made available on [app.accesslocator.com](http://app.accesslocator.com).  There was a little problem with the marker getting overlapped by the left side but this was adjusted by moving the intro element on the left up slightly.

**Comment by Blandine-AA** [comment]
Looks good. PASS!
