### ISSUE TITLE
UX Design for hover/touch text popup

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#122]
Blandine mentioned that the text that shows when hovering over the location categories/tags in the grid on the home page looks too small.  It may be too small for people with visual impairment to read and it doesn't scale up at least in Chrome.

Need to redesign the tooltip to be more visible.

- [ ] Create a UX Design/mockup for how this should look
- [ ] Get the mockup approved by Blandine

**Comment by joshi1983** [comment]
This may be good for @areebakamal  or @RumanaHakeem except they're already pretty busy with other tasks.

**Comment by areebakamal** [comment]
I think this can be closed as it's in development phase now in #242?

**Comment by joshi1983** [comment]
I agree with @areebakamal so I'm closing it.
