### ISSUE TITLE
Home page : Change info text

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#124]
Being updated... 

Change : "Find locations with accessibility ratings by real users and rate locations yourself!"

to: "Find accessibility informations on locations rated by real users, and make your own ratings!"

**Comment by stephanosm** [comment]
Find accessibility information

**Comment by joshi1983** [comment]
I'm marking this complete because the rewording is done.  I used @stephanosm 's suggestion and kept the 's' out of 'informations'.  Also, I didn't include the original comma which looked better to me.

**Comment by brucelau-github** [comment]
I have time to write some code. Joshi, What should I do now? I have made it run on my machine.

**Comment by joshi1983** [comment]
Great Bruce.  Since this is unrelated to the issue, I've sent an email to discuss what you can work on there.  Your address is liu1ee@uwindsor.ca , right?
