### ISSUE TITLE
Menu : Update top menu

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#125]
Being updated

- [x] The search menu item seems to be redundant with the Home page in the way it "might" works. Need to see if we remove the "Search" menu item or design it specifically for search only. To be different from the Home page
- [x] After user has signed in, add a "Sign out" button on the right of the "Contact" menu item

**Comment by joshi1983** [comment]
The Search menu item was removed for now until a sketch is made to show how the search screen should look.  I suggest making a search screen that is full of search-related features.  This would be different from the home page which uses less than half the screen for search.

**Comment by joshi1983** [comment]
I'm marking this done because the second task is definitely done and the first one is done if it is just asking for the Search link to be removed.

**Comment by Blandine-AA** [comment]
The Sign out button should be on the right of the contact menu. It needs to be last!

**Comment by brucelau-github** [comment]
![logoutbotton](https://cloud.githubusercontent.com/assets/22227484/21444236/7b0cabb6-c879-11e6-8313-05211eb430bf.png)

**Comment by joshi1983** [comment]
I reopened because the changes should be available for Blandine to see before closing it.  I won't do this today because it seems like Bruce may make a pull request for it some time soon since he has the change on his computer.  I'll help Bruce with reviewing his pull requests.

**Comment by joshi1983** [comment]
I merged the work Bruce did and deployed it to http://app.accesslocator.com so Blandine can see them.  I think this is done now so closing.
