### ISSUE TITLE
Sign Up page : Make Gmail/Google authentication work

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#127]
The Sign Up page has a Google link.  Make the link work.

This is similar to #57 except with gmail/Google instead of facebook.

In the end, sign up with Google should involve the following steps:

1. Click Sign Up.  This would open another page from Google to enter credentials.
1. Enter gmail/google account credentials.  Google's authentication service should return account information such as an email address that can be used by accesslocator to make a new account.

![image](https://cloud.githubusercontent.com/assets/11838191/21404985/ea21742a-c791-11e6-9682-cf62b53de4a7.png)

**Comment by brucelau-github** [comment]
Okay, I will do this first!

**Comment by joshi1983** [comment]
Great, Bruce.  I assigned it to go with you wanting to work on it.  I also added some extra detail to the issue description in case it helps your work.

**Comment by brucelau-github** [comment]
I have figured this module out. It is easy to add more social network module to login

**Comment by joshi1983** [comment]
Excellent.

**Comment by brucelau-github** [comment]
I have a question on how should we redirect users url after authentication. should we save user data back into our database or any idea? Currently I just dump all those gathered data on test page.

**Comment by brucelau-github** [comment]
![facebook login](https://cloud.githubusercontent.com/assets/22227484/21442529/55d8f596-c86c-11e6-83af-c00bb4f47ae5.png)

**Comment by joshi1983** [comment]
@brucelau-github there's a bug in http://app.accesslocator.com/signin where clicking the Google link redirects to localhost.  I suspect it might be related to a host name in your google account that I copied from your .env.  I started thinking it was related to the base_url in config/hybridauth.php but hardcoded app.accesslocator.com there and it still went to localhost.

I think you could reproduce the problem locally if you update your hosts file to let a name like 'bruce.accesslocator.com' point to 127.0.0.1.  Also, run 'php artisan serve' with the --host=0.0.0.0 to use another host name. That should let you access your local server from http://bruce.accesslocator.com:8000/ Can you try that?

**Comment by brucelau-github** [comment]
I have tested on my local machine the base_url. It works well. It failed at the first time when I forget to restart the php artisan serve after changing the key value pair APP_URL in .env file. the latest commit will handle the authentication error.

**Comment by brucelau-github** [comment]
I have changed the default password.

**Comment by brucelau-github** [comment]
I have add this app.accesslocator.com in the google authorized redirect urls. now it would be work

**Comment by joshi1983** [comment]
Can you rebase your issue#127 on latest master?

**Comment by brucelau-github** [comment]
rebase and fix up the error handle error. @joshi1983

**Comment by brucelau-github** [comment]
#8b4a7a5e63adfc322c608be6536d6d7e65ca6a3a

**Comment by brucelau-github** [comment]
[8b4a7a5e63adfc322c608be6536d6d7e65ca6a3a](url)

**Comment by Blandine-AA** [comment]
This doesn't work anymore ! I can't sign in using my Google password.

**Comment by brucelau-github** [comment]
Yah. probably, User should be redirected to the map page or the profile page where users can change their profile.

**Comment by brucelau-github** [comment]
![screenshot from 2017-01-04 13-49-29](https://cloud.githubusercontent.com/assets/22227484/21654768/042e914c-d285-11e6-8fc8-9740ee824bac.
redirect users to profile page and save user's login status.

**Comment by joshi1983** [comment]
@Blandine-AA I tested this and demo redirects to demo as desired.  app redirects to app as desired.  It looks done to me.  If you agree that this is ready to close, please close it.

**Comment by joshi1983** [comment]
I'm closing the issue because I'm pretty confident it is done.

**Comment by joshi1983** [comment]
I'm reopening for testing.

**Comment by joshi1983** [comment]
I'm closing again because I think this was done before the last demo release was made.
