### ISSUE TITLE
Home page : Change Sign in / Sign up font to BOLD

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#130]
When used with a tablet, the Sign in / sign up is barely visible. Make the font bold like the categories.

Josh,
Please assign this and make it P1 or Critical for quick resolution

**Comment by joshi1983** [comment]
Sure.  I'll update the button on the home page today.

**Comment by joshi1983** [comment]
![image](https://cloud.githubusercontent.com/assets/11838191/21437611/d1a0e1c6-c852-11e6-9dc3-9472bb3834fe.png)

**Comment by joshi1983** [comment]
The requested text was made bold so I'm closing.

Blandine, what kind of tablet are you using?  iPad?  Android?  What version?

I've been testing with a Samsung Galaxy Tab s3.
https://i.ytimg.com/vi/vjE33E92zPg/hqdefault.jpg
