### ISSUE TITLE
Sign up : text consistency problem

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#143]
After signing up, I get a message using "log in" instead of "sign in".

![image](https://cloud.githubusercontent.com/assets/20052162/21513060/0e8641f2-cc82-11e6-8e9f-e8421cd2ee86.png)

Josh,
Please assign as appropriate and set it Critical or P1 as necessary.
Thanks,

**Comment by joshi1983** [comment]
I'll get this change done in about 15 minutes.

**Comment by joshi1983** [comment]
This is done and deployed to app.accesslocator.com so I'm closing the issue.

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/11838191/21523110/1351d7d0-ccd9-11e6-8959-caaa9a8b5646.png)
