### ISSUE TITLE
Profile page : need more precision

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#145]
We need to provide the user some help on what to enter in the fields.
For example:
- [x] Location should have "Windsor" as help info
- [x] Distance should have the unit beside it: m, km???
- [x] The save button is missing. How do I get out of the profile? It is not obvious if the page autosaves or not, and that you can just jump to the Home page or the Search page. I think the design was defined in the initial issue to create the profile. BTW, the profile is not currently saved. 

Josh,
Please review and assign accordingly.

**Comment by joshi1983** [comment]
I thought these tasks were being developed as part of #110 and I added some of mocked work to get it just a little closer to the sketches without completing it.  Some other work such as a password change button is needed as part of #110.

Is this critical for January 1?  Over the next few days, @brucelau-github probably is most ready to take this on but he's focused on and getting good momentum on third party authentication.  Unless you think #145 is critical for January 1, it seems good that he continue with his current tasks and #145 potentially be given 2 weeks to complete.

**Comment by brucelau-github** [comment]
I can fix this problem.

**Comment by brucelau-github** [comment]
I need more clear definition on the issue.  how could I change them?

**Comment by joshi1983** [comment]
I added "Windsor, Ontario, Canada" as placeholder text in the location search on the profile but didn't update the "City" to do the same.

**Comment by Blandine-AA** [comment]
I think we don't need that for the Home section as the fields are clear. It is the location field that was a bit confusing.

Isn't distance in km a bit to wide? Since it is used for precision near my position. for 100 m,  I will have to enter 0.1. Let's see how it goes with initial user testing.

**Comment by joshi1983** [comment]
I think kilometers is good enough for now.  Since the 3 tasks are completed and this question of the unit being km or meters being answered when testing is complete, I'll close this issue.  A new issue can be created when/if meters needs to be used instead of km.
