### ISSUE TITLE
Slogan

### ISSUE THREAD

**Issue by areebakamal** [hhaccessibility/hhaccessibility.github.io#149]
1.	Access the world your own way
1.	Access the world with your own view
1.	Helping you personalize access to the world.
1.	Accessing the world in a personalized way
1.	An accessible world at your fingertips
1.	Guide me to my location
1.	The accessible world as you want 
1.	The accessible world personalized
1.	Guide you to the world 
1.	Personally guides you to the world
1.	Your personal guide to the world.
1.	Personalized access to the world
1.   Accessing the world in a friendly and personalized way
1.   Your personalized access to the world.
1.   Your way to access
1.   Your way to accessibility
1.   Accessibility  personalized/ Accessibility personalized at your fingertips 

Choose your top 3. You can also add new ideas or combine suggestions.

**Comment by stephanosm** [comment]
Here are my suggestions:
4. Accessing the world in a personalized way
13. Accessing the world in a friendly and personalized way
5. An accessible world at your fingertips

I recommend inviting Anne and Tracey to provide their suggestions

**Comment by Blandine-AA** [comment]
Anne and Tracey invited!

**Comment by Blandine-AA** [comment]
My picks, with minor modifications:
4. Access the world in a personalized way
5. The accessible world at your fingertips
1. Access the world your way

**Comment by joshi1983** [comment]
My picks from most preferred first are:
Access the world your own way
Your personalized access to the world
Your personal guide to the world

**Comment by annejmcc** [comment]
5.An accessible world at your fingertips
12.Personalized access to the world
8.The accessible world personalized

**Comment by joshi1983** [comment]
This is a shorter one than we currently have but what about "Your way to access"?

I'll add it to the issue description to put it with the list.

**Comment by Blandine-AA** [comment]
> what about "Your way to access"?

Better yet... "Your way to accessibility"

**Comment by Blandine-AA** [comment]
Another one.. "Accessibility personalized"

**Comment by Blandine-AA** [comment]
Tracey's picks: 
> I like slogans 5, 14 and 4 the best.

**Comment by Blandine-AA** [comment]
To summarize the votes (in brackets):
4. Accessing the world in a personalized way (**4**)
5. An(The) accessible world at your fingertips (**4**)
8. The accessible world personalized(**2**)
11. Your personal guide to the world (**2**)
14. Your personalized access to the world (**2**)
1.Access the world your (own) way (**1**)
9. Guide you to the world (**1**)
12. (Your) Personalized access to the world (**1**)
13. Accessing the world in a friendly and personalized way (**1**)

There are ties. I would suggest to pick your 2 bests!

**Comment by annejmcc** [comment]
Tracey likes 14 and 5
Anne likes 5 (with THE not An) and 12/14 (they are the same?)

**Comment by stephanosm** [comment]
Yes 12 and 14 are the same, thus having 3 votes. 
Mine are 12/14 and second option is 5

**Comment by RumanaHakeem** [comment]
I like the 5th one.

**Comment by brucelau-github** [comment]
the 4 th and 12

**Comment by areebakamal** [comment]
14.Your personalized access to the world.
1.Access the world _your_ way
8. The accessible world personalized

**Comment by Blandine-AA** [comment]
My picks are:
12/14 and 8

**Comment by joshi1983** [comment]
My picks from most preferred first are:
Access the world your way
15. Your way to access
16. Your way to accessibility
14.Your personalized access to the world

I commented about it on Dec. 31 but just wanted to update the preferences since we added a few items to the list.

**Comment by Blandine-AA** [comment]
@joshi1983 I was asking for your 2 picks from the second list after I tallied the initial choices. Please see my comment from a day ago.

**Comment by joshi1983** [comment]
I missed that @Blandine-AA.  Here's my 2 picks out of the revised list:

4. Accessing the world in a personalized way
12/14. Your personalized access to the world

**Comment by Blandine-AA** [comment]
Every body has voted and here are the results:
12/14. Your personalized access to the world (**7**)
5. The accessible world at your fingertips (**4**)
4. Accessing the world in a personalized way (**2**)
8. The accessible world personalized (**2**)

**The clear choice is : "Your personalized access to the world"**

@joshi1983  you can  implement this .
