### ISSUE TITLE
PPT Presentation about AccessLocator

### ISSUE THREAD

**Issue by stephanosm** [hhaccessibility/hhaccessibility.github.io#153]
The first draft presentation. It includes animations. Any feedback or changes?

[AccessLocator.pptx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/679853/AccessLocator.pptx)

**Comment by joshi1983** [comment]
This is a clearer version of the image you captured of the logo with project name:

![image](https://cloud.githubusercontent.com/assets/11838191/21582214/8157c87a-d01c-11e6-8180-8b931d57d562.png)

I suggest replacing with that.

**Comment by joshi1983** [comment]
[accesslocator.com](http://accesslocator.com) was updated to let people download your PowerPoint presentation file.

Let me know if you make changes that you want copied over to accesslocator.com's version of the PowerPoint.

**Comment by Blandine-AA** [comment]
I would like to suggest 2 things:

1- The presentation is a very nice presentation of what the Front page is showing. I am not sure we should have people downloading it. But since the information is already publicly available, I suggest to have the button say: "Download the presentation". If we say "View the Presentation", I expect the presentation to open on a new screen (popup or new page). It is a bit destabilizing to expect a view and have a download.

2- My second point is that, the app has been cleaned enough with messages on features that don't work yet, that we can cut-off a demo version of the app and have a Demo button. This will really bring new information to the viewer.

**Comment by stephanosm** [comment]
I've make the corrections and I made it as a video. The problem is that this way you can't click the demo button. Any other ideas? May be remove the button from the video and include it next to this video on the informational website?


[AccessLocator_video.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/680221/AccessLocator_video.zip)

**Comment by stephanosm** [comment]
I removed the button.

[AccessLocator_video.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/680286/AccessLocator_video.zip)

**Comment by Blandine-AA** [comment]
I just reviewed some of the sketches that Areeba posted on the UX design issue #30 , and I think some of them should be include on the Front page and the video. She did a really good job too with the last ones.

For the Front page, 

- [ ]  Replace the current map with this one as discussed in the last meeting, _after she made the few chages requested_ : https://cloud.githubusercontent.com/assets/23005093/21532983/072ad790-cd24-11e6-9408-66bcc72819a7.jpg

- [ ] Add the following sketche between the home page and the map : https://cloud.githubusercontent.com/assets/23005093/21532864/c2852d4e-cd22-11e6-9d97-98b90b465731.jpg

It will make 3 pictures at the bottom of the page

**Comment by stephanosm** [comment]
I've changed the map image with the new one and I updated the video. No room for any more images. I think the rest is ok to be just on the site. If we put them all then it just becomes a copy of the site.
[AccessLocator_video.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/680355/AccessLocator_video.zip)

**Comment by areebakamal** [comment]
The first image in @Blandine-AA's post with the changes in regards to 'Rate' button can be found here: 

https://cloud.githubusercontent.com/assets/23005093/21584888/ec6d6b68-d082-11e6-84b1-ce087dc034b9.jpg

**Comment by Blandine-AA** [comment]
I don't agree that adding more screen captures or sketches makes it a copy of the site as they are not all implemented yet. I thought the idea was to showcase the work that we do and/or plan to do.

I still believe that it is important to have more screen captures to balance out the text in the presentation and make it less like the Front page !

**Comment by Blandine-AA** [comment]
Regarding Stephanos comment : 

> "No room for any more images. I think the rest is ok to be just on the site. If we put them all then it just becomes a copy of the site."

I suggest then that we do not use the same images in the video and on the site then.

**Comment by Blandine-AA** [comment]
@stephanosm, I presented the Info page We-Tech on Wednesday, and I got some feedback. One of them, unspoken, was the presentation video was a bit slow. I don't know if there is anything we can do for some of the animations and transition that take time on the screen. 

Now the video is only 3 mins long. Which is not too bad!

Also, now that we have the slogan, can that be updated too?

**Comment by Blandine-AA** [comment]
@joshi1983, Now that we have the slogan, could you please provide an updated "Logo+App name +Slogan" image to Stephanos for the PPT?
Thanks,

**Comment by stephanosm** [comment]
@Blandine-AA, some of the slides of the PPT are slow in purpose. Those are the ones with lots of text so the viewer has enough time to read it. 
Yesterday, we had a meeting about the Hackathon and the people from WeTech were excited about AccessLocator.

**Comment by joshi1983** [comment]
As @Blandine-AA reminded me, here's an updated image of the logo with the new slogan.

![image](https://cloud.githubusercontent.com/assets/11838191/21955955/8564c66c-da43-11e6-8967-c8d5cac3a7c5.png)

**Comment by Blandine-AA** [comment]
@stephanosm , thanks for the clarification on the slide. I also thought that would be the reason.

I did a quick presentation on Wednesday to Irek from Hackforge. That's why! He is very excited about the project et can't believe how far we got! It is good sign! We may get some help from them after all.

**Comment by joshi1983** [comment]
If you mean Irek Kusmierczyk, I think he's more connected with WeTech.

**Comment by stephanosm** [comment]
Yes, Irek from WeTech

**Comment by joshi1983** [comment]
I added Areeba to this since she'll be copying any new presentation files to the information website now.

**Comment by Blandine-AA** [comment]
Yes. I meant Irek from WE-Tech. There is only one Irek K. in windsor :).

**Comment by Blandine-AA** [comment]
@stephanosm, could you please update the ppt and video to include the new logo+slogan image Josh posted 9 days ago?
> here's an updated image of the logo with the new slogan that would be good to add to the presentation file and video.

Then let @areebakamal know so that she can update the link.

**Comment by Blandine-AA** [comment]
All items that missed the deadline will be fixed for demo 0.0.2
