### ISSUE TITLE
Demo : initial version (0.0.1) readiness

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#173]
Some work is needed to have a "clean" demo release. I think the time spent will be worthwhile, as it will allow to do 'clean' demos to potential sponsors and early adopters.

- Update the following pages or links that are not completed or will not be completed by the end of the month with "Under Development" popup/message:
     - [x] Sign In with Facebook - Currently doesn't work. If we are not going to complete by the end of the month, we want to show the "Under Development" pop-up. Otherwise it looks as if it is broken.
     - [x] Profile page: photo upload - Currently doesn't work. If we are not going to complete by the end of the month, we want to show the "Under Development" popup. Otherwise it looks as if it is broken.
     - [x] Profile page: save button - Currently broken. If we are not going to complete by the end of the month, we want to show the "Under Development" pop-up. 

           BTW, why is it a check-mark all the time on the save button?

     - [x] Profile page: My Reviews button - Show the "Under Development" pop-up, as I know we will not have it implemented by end of the month
     - [x] Location Search Results page: put (Under Development) in brackets, even though we still provide the result list to allow to see the map, we want to tell the user that development is still in progress. We need to show  the list.
     - [x] Location rating by category display on map : put (Under Development) in brackets, even though we still provide the location rating on the map, we want to tell the user that development is still in progress. We need to show  the map. 

          It would be nice to have the # of ratings place holder implemented here.

     - [x] Criteria ratings page : From the location info on the map, when the user clicks on an accessibility category, show the Under Development popup instead of the current list of criteria!

- Release version:
     - [ ] Create Demo version 0.0.1 for the first demo. To be released by January 31rst if possible. To be added at the bottom of the page. Aligned to where we would put the Copyright. 

For more info, see the [Demo Release Plan & Schedule Milestone](https://github.com/hhaccessibility/hhaccessibility.github.io/milestone/5)

**Comment by joshi1983** [comment]
@Blandine-AA please list exactly what extra pages should have "Under Development" on them.  This isn't clear when all pages are somewhat under development.

Also, where should the 0.0.1 go?  Should it be documented somewhere for the public to see?  Is that something for the Information Site?

**Comment by Blandine-AA** [comment]
@joshi1983 ,
I have updated the initial message with the info on where the version number should be andthe list of pages that need to be tagged. Hopefully I have covered all of them. Let me know if you have questions or find other that I missed.

I don't think we need to add extra info on the Info page for now. We can choose to publish or not a release note on the info page when we get to demo version 0.0.2, but will update the version number on the new demo release.

Hope this is a bit more clear :).

**Comment by joshi1983** [comment]
I checked the Profile save because it is working like commented on in #110.  I'll try to keep the discussion of the profile on #110 so this one doesn't get noisy.  Given all the business coming up at the end of the month, I'll probably get this demo made early next week and it won't receive any updates until the next demo happens at least a month later.

**Comment by joshi1983** [comment]
@Blandine-AA I finished most of this issue.  There is an independent demo deployment now.

There was no copyright for almost a month.  If we add it back in, who should it be copyrighting to?  JMCC was there before.

**Comment by Blandine-AA** [comment]
Thanks @joshi1983  for the update.

I didn't say that we need to add the copyright. I mentioned it just to indicate where to pput the version as you asked. Maybe another lace for the versonis more suitable, bt it is the only place that came to mind when answering your questions :)

Regarding the copyright, we will need to think about it and see with JMCC. But thinking about it again, on top of my head, copyright should be to AccessLocator, which by default is currently owned by JMCC. 

Hope this helps

**Comment by Blandine-AA** [comment]
@joshi1983 , this hasn't been been fixed yet under the demo environment. you needed  to show 'Under development' instead of the list of criteria. http://demo.accesslocator.com/location-report/30/universal/3

Also, having the rating and distance in the demo version wasn't needed. Having the requirement above is more important.

I have updated/unchecked the requirements in the initial issue description that are not completed

**Comment by Blandine-AA** [comment]
Version number not implemented, but closing this as we are working on the next milestone for demo version 0.0.2
