### ISSUE TITLE
Demo : Problem when signing in with Google

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#180]
When trying to sign in with Google from the demo domain demo.accesslocator.com, **I am redirected to the development domain app.accesslocator.com.** 
Please fix so that when using the demo domain, we stay on it.

Same thing happens when clicking on the Facebook. But this is going to have a the "Under development" popup anyway.

@joshi1983 , since I don't know if it is related to the domain name or the Google support implementation, I assign this to you to assign to @brucelau-github  eventually.

**Comment by joshi1983** [comment]
Regarding the facebook comment, Bruce has it almost working properly too so it'll probably get in the demo for end of month rather than the "Under development" message.

**Comment by brucelau-github** [comment]
It should work now.

**Comment by brucelau-github** [comment]
for facebook : Your app is currently live and available to the public.

**Comment by joshi1983** [comment]
@brucelau-github I changed the APP_URL in .env on Digital Ocean and that fixed the facebook redirecting to app.accesslocator.com.  

I'm getting a new problem with Google authentication, though.  Any chance the settings are referring to app.accesslocator.com specifically for authentication?  If so, maybe we can add demo.accesslocator.com or the various other subdomains of accesslocator.com to the accepted domains.
![image](https://cloud.githubusercontent.com/assets/11838191/22044006/737b2afa-dce0-11e6-82a5-cfe665fa3745.png)

**Comment by Blandine-AA** [comment]
@brucelau-github @joshi1983 

Also, whether using FB or Google to connect from app.accesslocator.com, I am redirected to demo.accesslocator.com. I should stay on app.accesslocator.com

**Comment by joshi1983** [comment]
@Blandine-AA yes, I knew of that problem but that's better than always being redirected to app.accesslocator.com, right?  I just thought people seeing the intended behaviour from demo.accesslocator.com was more important because we're encouraging people to visit that site from accesslocator.com.

I can probably fix the problem of always redirecting back to demo.accesslocator.com tonight but @brucelau-github can you fix the error I found in an earlier comment?  I'm guessing it'll be a setting that you used in your Google authentication.  Since you worked on it, I think you'll fix it faster than I can.

**Comment by joshi1983** [comment]
I gave up on having this resolved for the January 32 demo release and showed a popup on demo.accesslocator.com instead under the Google link.

app.accesslocator.com has no such message so @brucelau-github can fix it more easily.

**Comment by brucelau-github** [comment]
I have fixed the error on Google and it might work after a couple of minutes.

**Comment by brucelau-github** [comment]
@joshi1983  I have tested on our server and it works now. And I change them back to javascript:link. it is ready to use.

**Comment by brucelau-github** [comment]
about the app or demo link. it depends on APP_URL setting in .env file.

**Comment by joshi1983** [comment]
@brucelau-github good stuff.  I tested Bruce's changes too and it is working.  demo redirects to demo.  app redirects to app.  I think this is done and ready to close.  @Blandine-AA if you agree, please close.
