### ISSUE TITLE
Testing : Round1 testplan

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#185]
Write test plan & testcases to coover the following areas:
![image](https://cloud.githubusercontent.com/assets/20052162/22159200/d4722744-df0d-11e6-8b4f-e0526232d5b4.png)
[AccessLocator Testing Round1-testplan.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/724220/AccessLocator.Testing.Round1-testplan.docx)

**Comment by joshi1983** [comment]
Are you forgetting the contact page at [demo.accesslocator.com/contact](http://demo.accesslocator.com/contact)?

**Comment by Blandine-AA** [comment]
@joshi1983,
It wasn't the intent to have users testing  on the demo environment.
Testing will be more frequent than demo. So, it makes sense to me to have a separate testing environment for the short period of time we do the testing.

Can't you just fork a build to the test environment? No extra work will need to be done from the app environment. Except for a code submission freeze of a day or 2.

Regarding the contact form, i didn't write a specific testcase for it, but I have a line that asks to send some feedback using the contact form.
I ran all my testcases on the app environment.

**Comment by joshi1983** [comment]
@Blandine-AA you want the same 'Under Development' messages from demo on test, right?

**Comment by Blandine-AA** [comment]
@joshi1983 , for the test environment, no need to have the "under development" specifically added. What ever is in the app at the time of the cut off will be.

For this round, I have changed the test plan to use the demo environment, and sent it to Anne and Tracey. So, let's just move on :)

**Comment by Blandine-AA** [comment]
Closing this issue as there is nothing left to do on it.
