### ISSUE TITLE
Open Data : Winter Hackathon Challenge

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#192]
As part of the Winter Hackathon organized by Hackforge and the University of Windsor, we are having AccessLocator challenges for the students. The Hackathon Theme is Open Data.

As lead design, @joshi1983 has agreed to work on defining the challenges. This issue is to share what the challenges are.

**Comment by joshi1983** [comment]
I've been sharing a Powerpoint presentation with @Blandine-AA and @stephanosm through email.

**Comment by joshi1983** [comment]
Here are the Powerpoint slides for the challenge:
[AccessLocator Open Data Challenge.pptx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/737828/AccessLocator.Open.Data.Challenge.pptx)

Here are some more details shared with interested participants:
[OpenStreetMapLocationsDownloader.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/737832/OpenStreetMapLocationsDownloader.docx)

**Comment by joshi1983** [comment]
I think "Lead Design" could be misinterpreted as more of a graphic design or UX design position.  "Lead Developer" seems like a more accurate and understandable title for my role on AccessLocator.

**Comment by joshi1983** [comment]
Since the challenge is over and the challenge has been shared, I'm closing this issue because it seems complete.
