### ISSUE TITLE
Sign Up : Email validation

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#199]
When a user creates an AccessLocator account, we need to validate the email entered before the user can use it to sign in

@joshi1983, please review and assign accordingly

This is related to #58.

**Comment by brucelau-github** [comment]
I have pushed this issue. it may need your suggestion for further amending the code. @joshi1983

**Comment by joshi1983** [comment]
I've given feedback on the pull request for @brucelau-github to tweak.

**Comment by joshi1983** [comment]
The work from @brucelau-github has been merged.  @Blandine-AA you can check on app.accesslocator.com by signing up a new user using the first name, last name...  just don't sign up using facebook or Google.  I'll leave it up to @Blandine-AA to decide if remaining changes are needed.

A minor thing I'd suggest is also a "Your email has already been confirmed." message when clicking an emailed link that has already been confirmed.  This would reassure the user that he already completed the email confirmation step.

**Comment by joshi1983** [comment]
@brucelau-github do you have time to work on this?

From what Blandine is saying, it sounds like a little change is needed to the SignInController.php and sign in process.  From what I remember, your changes set a email_verification_time that would need to be checked to be null.  This shouldn't affect any third party authentication.

**Comment by brucelau-github** [comment]
yeah. I could fix this issue.

**Comment by joshi1983** [comment]
#58 and #199 should probably be closed at the same time so if one is ready to close, it'll be good to close the other.

**Comment by Blandine-AA** [comment]
@joshi1983 , it this fix merged? @brucelau-github  said that it was completed. If so, please set it to "Ready for Testing" and assign to @kimficara

**Comment by joshi1983** [comment]
This is merged yes.  It is ready for testing.  I'll update labels and assignee now.

**Comment by kimficara** [comment]
PASS for e-mail validation.
