### ISSUE TITLE
Open Street Map : Locations retrieval

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#201]
As a follow-up to the Winter Hackathon, more work seems to be needed to retrieve the locations geographical information.

Here is Josh's answer to my question if we had some results from the hackathon team: 

> Yes, some tangible results from the students at the hackathon but **the code should be improved over the coming weeks to collect more locations and more information on each one.**  So far, it is just 40 locations with name, longitude, latitude, and phone number.  I told them that I'd help them get more done this Saturday during my usual 10am to 12 noon hours in CAW.  **OpenStreetMap has enough data that we should be able to categorize the locations well after more work.**  OpenStreetMap has a lot more detail than any other data source I tried importing from for AccessLocator so far including every street light, street, coordinates around sides of buildings...  **It doesn't have much accessibility information, though.**

**Comment by joshi1983** [comment]
This is a little progress update after this morning's meeting with 2 VIP students and the hackathon team.

@balraj18 has half of the location categories/tags from the home page being populated.  He'll start extracting information from "way" elements soon which will let us collect information on maybe 20 or 30% more locations.

**Comment by joshi1983** [comment]
The CSV file to seed data tool is ready for @balraj18 's OpenStreetMap tool that turns OpenStreetMap XML data into a CSV file.  When @balraj18 's work is done, we'll be ready to bring lots of new Windsor-area locations into our seed data.

When I say "seed data", I mean the data that we have every time we completely recreate our database.  It is basically the data we start a demo with.

**Comment by Blandine-AA** [comment]
After this, I think we need to expand the data retrieval to at least Canada and the US.

**Comment by joshi1983** [comment]
I merged code written by @balraj18, @sidhunavroop and me and added roughly 300 extra locations to the database for http://app.accesslocator.com.

There are a few problems like "University of Windsor" is repeated a few times but it should be good for now.  There were a lot of highways, streets, railways, traffic lights, bus stops, webcams, crosswalks... that were filtered out since I thought we wouldn't want to rate them.

**Comment by Blandine-AA** [comment]
There is a lot more locations now in the app co;pared to demo 0.0.1
