### ISSUE TITLE
User Profile : Change "Accessibility Interests" to "My Accessibility Requirements"

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#208]
Feedback from update meeting with JMCC on Feb. 3rd

**Comment by areebakamal** [comment]
completed. #211

**Comment by joshi1983** [comment]
I'm pretty confident this is complete.  It looks like a really simple and clear requirement and it is complete so I'm closing the issue.  You can see the changes on [app.accesslocator.com](http://app.accesslocator.com)

**Comment by joshi1983** [comment]
I'm reopening for testing.

**Comment by Blandine-AA** [comment]
Passed
