### ISSUE TITLE
Search by category : location search results not properly filtered

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#209]
Testing result for TC2 of testplan #185 

- [ ] Step1 failed: It doesn't just show bus stations - seems to be a general list
- [ ] Overall : search list needs to be fixed with lists showing items based on wording when searching by keywords

**Comment by joshi1983** [comment]
What was expected and how was the actual result different from that?  

If you type "bus station", the results are any location containing "bus" or "station".  Do you expect it to be just "bus" AND "station"?
![image](https://cloud.githubusercontent.com/assets/11838191/22717141/66db143a-ed67-11e6-8790-cfcadf9c0111.png)

The only known issue for searching is #101 (filtering by search location and radius).

**Comment by joshi1983** [comment]
I was wanting an answer to my question from 20 days ago but will implement what I think is a little closer to what the user expected by using an AND instead of OR between the keywords.  Hopefully this change moves the discussion forward more than doing no change at all.

**Comment by stephanosm** [comment]
Is it possible to have both with sorting the AND first? I am thinking the
case where the are synonyms e.g. a user searching with BUS STOP (instead of
Bus Station) meaning the station, so you want to include that in the list
as well. So, the AND results should be listed first and then the OR results.

**Comment by joshi1983** [comment]
@stephanosm sorting by match quality would make more sense if we didn't already have such explicit sorting features.  The "table"/spreadsheet view shows sorting by name, accessibility rating, and distance.  If we sorted by what I'd call "match quality" as in most keywords matched first, it would be difficult to keep that consistent with how results by location tag or category.  The same map and table views are used for both ways of filtering locations.

**Comment by kimficara** [comment]
STEPS TO TEST ISSUE #209:

1.  Navigate to the Access Locator home page.  If you're on a different page you can click the AccessLocator Logo in the top left corner of the page or the home tab in the top right corner.
2.  To search by category, leave the location and keyword field blank and select a category box.
3.  This will bring you to the search results page.
4.  You can select a location to view more information, the ratings and the map.
5.  To search a new category, navigate back to the home page and restart from step 2.

**Comment by kimficara** [comment]
The only issue I had when testing this task is the fact that I cannot enter a location or keyword to filter through the category search results.  Is the search designed to use just the text fields or the category buttons and not both at the same time? 

I also tested the "AND" search feature that John implemented and did not find any issues with it.

**Comment by joshi1983** [comment]
I'll summarize how I intended it to be:
- The search location and radius is used in all searches regardless of if it is for keywords or location category.  The search results are always filtered down to a distance range from the search location.  You can adjust the maximum range by saving a new "Search Location" -> "Distance (km)" in your profile and staying signed in.
- There is no mixing of search keywords and location category for now.  It is strictly one or the other.

I'm not sure if this is causing any confusion but the search location is being saved as the map on the home page updates.  It is placed close to the keyword input yet it is just as related to the location tags below as it is to keywords.  If this is confusing, would it be an improvement to move the map on the home page down to between the keywords and location categories?
