### ISSUE TITLE
Investigate open data in Windsor

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#21]
Investigate if there are any existing open data (in Windsor to start) that we could use for our baseline data.

**Comment by Blandine-AA** [comment]
This is the [City of Windsor, multi-year accessibility plan :](http://www.citywindsor.ca/cityhall/Accessibility/Documents/city-of-windsor-multi-year-accessibility-plan.pdf)

The [City of Windsor open data catalog](http://www.citywindsor.ca/opendata/pages/open-data-catalogue.aspx) does not provide any accessibility information. At least none that is easy to access/retrieve

**Comment by Blandine-AA** [comment]
I have contacted the City of Windsor and we might work out something to get their help with accessibility data collection. More to come...

**Comment by Blandine-AA** [comment]
A meeting is scheduled Feb. 14 with the various departments of the City of Windsor.

**Comment by joshi1983** [comment]
I'm closing this because the issue is for work that was done over a year ago and nothing came of it.  

The City of Windsor's open data catalog was made use of even in the 2016 Hacking Health event that initiated AccessLocator and we didn't get any new accessibility information from the City of Windsor since then.

**Comment by joshi1983** [comment]
I'm closing this because the issue is for work that was done over a year ago and nothing came of it.  

The City of Windsor's open data catalog was made use of even in the 2016 Hacking Health event that initiated AccessLocator and we didn't get any new accessibility information from the City of Windsor since then.
