### ISSUE TITLE
Presentation page: update for demo 0.0.2

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#210]
At the end of the current milestone, we will need to update the AccessLocator.com landing page with:

- [x]  new demo version 0.0.2
- [x] release note - add new menu?

**Comment by joshi1983** [comment]
I guess we could put release notes as comments under this issue for most changes visible to the end user.

**Comment by Blandine-AA** [comment]
Sounds like a good idea to document them as we go here, and later update the info page !

**Comment by joshi1983** [comment]
This is how I'd briefly describe the changes implemented between demo 0.0.1 and 0.0.2.

#221: Used address to control centre of location search radius and visualized address on home page
#209: Filtered location search results down to a radius around an address
#208: Renamed "Accessibility Interests" to "My Accessibility Requirements" on the user profile
#205: Visualized search location and radius on Map views/pages/home
#201: Imported roughly 300 new locations from Open Street Map
#184: Profile photo upload was adjusted to upload directly from the profile page instead of redirecting to a devoted page

**Comment by Blandine-AA** [comment]
Here is what should appear on the Release Note on the web page

NEW FEATURES (version 0.0.2)
1. Category selection more visible
1. Visual search radius around location address
1. Enhanced filtering of location search result
1. Renamed "Accessibility Interests" to "My Accessibility Requirements" on the user profile
1. Emhance profile photo upload functionality
1. Added around 300 new locations from Open Street Map
1. Added map and table views for location search results

**Comment by Blandine-AA** [comment]
@areebakamal,

Could you please update the web page with above release note?
Make a proposal on how and where you want it done.  I was thinking of having a menu or button "NEW FEATURES", or some think like that that catches the user eye.

**Comment by Blandine-AA** [comment]
@areebakamal, from the minutes. To put on the info web page ! 
> In the release notes, we will write future scope for the Rating feature. Something like... “Available soon”.

**Comment by areebakamal** [comment]
What I had in mind: adding an additional page with a tab next to 'home' and 'contact'. Like you suggested, we can call it New Features. 
On the new page, we would have the latest release note on top, and keep updating as a new entry as we have newer versions in descending chronological order.

**Comment by areebakamal** [comment]
@Blandine-AA You mean in the caption for the following images, write Available Soon? or under 'New Features' as point 8? 
![image](https://cloud.githubusercontent.com/assets/23005093/23929027/8e4321ae-08f9-11e7-9dee-dbf2f26834a1.png)

**Comment by Blandine-AA** [comment]
@areebakamal, under 'New Features' as point 8.

**Comment by areebakamal** [comment]
![image](https://cloud.githubusercontent.com/assets/23005093/24028675/49203b16-0aa7-11e7-93a6-c2c68d0ca6d8.png)

Any changes or should I upload?

**Comment by areebakamal** [comment]
or

![image](https://cloud.githubusercontent.com/assets/23005093/24031356/9a43f904-0ab8-11e7-88b1-b0377b5bc2c5.png)

**Comment by joshi1983** [comment]
@areebakamal don't let this stop you from uploading your changes but here is a suggestion.

- I'd suggest sticking to the white background used in the contact and home page for consistency's sake.
- If you want attention brought to the release notes list, you could use a thick border, maybe 2 or 3 pixels, around the list.
- An alternative to a border would be a box-shadow like used in the http://accesslocator.com/presentation page for framing the demo video.

Here's a roughly how I suggest making it look.  Don't copy the sloppiness of the border in the mockup:
![image](https://cloud.githubusercontent.com/assets/11838191/24042380/14aca4fa-0ae8-11e7-8d66-6fbe2f5d1ce2.png)

**Comment by areebakamal** [comment]
I used the blue from the second half of the home page.

Okay I will update.

**Comment by Blandine-AA** [comment]
@areebakamal ,

Looking at your sketch and @joshi1983 comment, I think it will look nicer if it was done like a ppt slide with some design. 
Attached file is what I have in mind.... Of course design can be improved to match @joshi1983 comments above and make it more appealing.
[Release notes.pptx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/851061/Release.notes.pptx)

**Comment by areebakamal** [comment]
![image](https://cloud.githubusercontent.com/assets/23005093/24069376/1dde9ff2-0b7d-11e7-9f75-b863ca4dc18b.png)

I've updated the website at accesslocator.com.
