### ISSUE TITLE
User profile: State/Province Data Collection

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#217]
As a step toward a region hinting feature in the profile page(#212), we'll need to collect data on all states/provinces/territories and their associated countries.  At minimum, we want the information for Canada and USA but if you can get it for all countries, that would be better.

Note that this issue isn't asking for you to make the database table(#216) and this issue was split to give another developer the chance to work on data collection.   When this is complete, your work will need to work with their work, though.

Find a source of public domain or safe for our use-licence data that associates every "territory", "state", "province", "region" with their corresponding countries and find a way to represent that in our seed data files.

- [x] Find a source for the region data that is public domain or safe for us to use.  wikipedia or a public github repository could have it.
- [x] Add a seed file in hhaccessibility.github.io\app\database\seeds\data\region.json to represent all the collected region information.  The file must be valid JSON and set every attribute and assume the attributes to be id, country_id, and name.  The JSON structure must be similar to other files in that directory.
- [x] Create a pull request.  Do not merge the pull request, though.  It will be reviewed within a day later and potentially ask you for specific improvements.

These changes will be combined with work from #216 such that 'php artisan db:seed' inserts all the regions.  Testing with php artisan db:seed for inserting region data isn't necessary for this issue since this data collection may be done before the region table actually exists.

**Comment by joshi1983** [comment]
Thanks @kimficara for your pull request.  I merged her pull request and am closing this issue because it looks complete.

**Comment by Blandine-AA** [comment]
Re-opened for testing

**Comment by Blandine-AA** [comment]
Re-opened for testing

**Comment by Blandine-AA** [comment]
Re-opened for testing

**Comment by joshi1983** [comment]
@Blandine-AA this subtask can't be tested by the same people as you might think because the UI is unaffected by it.  This was a part of a larger feature that hasn't been completed yet and definitely won't be done in time for the March demo release.  #216 and #212 are needed before this is testable by end users. 

I suggest keeping this one closed.
