### ISSUE TITLE
Home page: Add Google Map to visualize search address and gather the corresponding longitude/latitude

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#221]
The location search features filter down to within a specific radius of a specific location.  The profile allows you to change the search radius but there is no way to change the search location in a way that impact the filtering process.

Google Maps JavaScript apis let you turn free text describing a location into a longitude and latitude that best guesses where you're referring to.  A marker on a map centred on that location is also a great way to visualize the search location.

- [x] This issue is asking you to add a Google Map on the home page like the following:
![image](https://cloud.githubusercontent.com/assets/11838191/22912283/7f65b5a8-f232-11e6-8dd0-d00c7a673a51.png)

- [x] Add setLatitude and setLongitude methods to app/app/BaseUser.php.  See setAddress for an example of how to switch between saving in the temporary session or saving to the database's user table.

- [x] Create a new API for saving the latitude, longitude and address(location search text).  This will likely involve adding a new method to the app/app/Http/controllers/HomeController.php for your new API and adding a reference to it from app/routes/web.php.  Use either HTTP POST or PUT for the new API because it'll be saving a new value instead of reading or deleting information.

- [x] Send HTTP requests using JavaScript to a new API you created from the home page.  hhaccessibility.github.io\app\resources\views\pages\home.blade.php maintains most of the HTML for the home page.  You could add JavaScript there or to a new external JavaScript file in hhaccessibility.github.io\app\public\js.  You'll have to pass a _token parameter to the API which you can print into a script tag of a view using something like:
`var csrf_token = '{{ csrf_token() }}'; 
`
- [x] Test saving the longitude and latitude to session when not signed in.
- [x] Test saving longitude and latitude to the user table record when signed in.

**Comment by e1cerebro** [comment]
1. What would the default location be if the user has not registered on the app?
2. Is jQueryAjax method of API allowed in this context for savinf for saving the latitude, longitude and keywords?

**Comment by joshi1983** [comment]
The Windsor City Hall is used like a default.  It is written as a placeholder until anything is typed in.  We'd rather the text be blank than have any default address text, if that's what you mean.  BaseUser has some logic that handles that default so that blank is treated as Windsor city hall.

Yes jQuery would be good for the ajax functionality.  The $.ajax method is what I'd use.  Using the underlying XHTTPRequest instead of jQuery functions can be a little annoying because some versions of IE need alternatives.  Note that public/js/jquery-3.1.1.js is in the project already and if you want to use jquery, include that instead of referencing another version from an external website like a Google cdn.

**Comment by joshi1983** [comment]
I mentioned the _token parameter in the issue because you'll have to specify it in your non-GET ajax requests.

**Comment by Blandine-AA** [comment]
Is help still needed on this one or the current assignment is sufficient ?

**Comment by joshi1983** [comment]
I think Christian is still working on it.  It probably won't be done in time for the March demo but Christian is working at it and emailing or chatting with me every couple days about it.  I doubt adding an extra person to this will get it done faster.

**Comment by e1cerebro** [comment]
I will be done with it before the next meeting.

**Comment by Blandine-AA** [comment]
@JaveriyaKhan, please test this feature today if pssible. Thanks !

**Comment by JaveriyaKhan** [comment]
Hello Blandine,
I have checked the functionality and some points to summarize:

1) Default location is the Windsor, when I enter the any location for example University of Windsor, so the map takes me to exact location of University of Windsor. I am bit confused dose it show the latitude/longitude when I click on the bubble. If yes, I did not get the latitude/longitude, however search takes me to exact place. (Please correct me if I am wrong)

![image](https://cloud.githubusercontent.com/assets/23346995/23675852/b3a9889a-0348-11e7-92b6-c8c30c69cd36.png)

2) I can set the search location distance from my profile page according to my need. For example I have set the 10 Km distance and I am searching the number of locations present for category Financial so it gives me all the locations present under the specified distance( 10Km).

![image](https://cloud.githubusercontent.com/assets/23346995/23676224/ff75cbc0-0349-11e7-9727-a124819e251e.png)

3) I can also do custom search, for example I have entered the Downtown in the search by keyword field.

![image](https://cloud.githubusercontent.com/assets/23346995/23676361/701778f6-034a-11e7-857f-199a04217dde.png)

And the result is

![image](https://cloud.githubusercontent.com/assets/23346995/23676379/86eb16aa-034a-11e7-8b62-a78b655cab4d.png)

4) At last it gives the independence to user to search by any keyword according to his/her need. And map location and distance working fine.

**Comment by e1cerebro** [comment]
From the issue description, the red marker is not supposed to take the user to any location.

**Comment by e1cerebro** [comment]
From the issue description, the red marker is not supposed to take the user to any location.

**Comment by Blandine-AA** [comment]
@JaveriyaKhan, regarding:
> If yes, I did not get the latitude/longitude, however search takes me to exact place. (Please correct me if I am wrong)

The user is not supposed to see longitude and latitude. Those are internal information, but the Location red marker should move to the location you entered.

Also, at this point I don't think that there is a feature defined for when you double click on the location marker. It is not supposed to be active. Even though it could be in the future.

**Comment by JaveriyaKhan** [comment]
Thanks Blandine for the explanation, when we enter the location so bubble moves to the location also bubble is fixed and does not move from there, which was described in the above mentioned testing feature.

**Comment by joshi1983** [comment]
It looks like Zoya has tested #221 and given feedback on this.  @Blandine-AA should #221 be closed now?

**Comment by Blandine-AA** [comment]
@joshi1983, if @JaveriyaKhan feels that the test PASSED or FAILED based on all the feedback provided, then she should follow the process to update the issue accordingly. 

Please do not update, @JaveriyaKhan should update it.

**Comment by joshi1983** [comment]
Sure thing.

**Comment by JaveriyaKhan** [comment]
Sure
