### ISSUE TITLE
Discovery Activity : Accessibility Criteria : Baseer & Zoya

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#226]
Find guidelines here : https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/Disability-criteria-discovery-activity-description

Then submit your results here by Friday Feb. 24th for all to have access to it and review

You will need to do all categories.

**Comment by baseer110** [comment]
I have attached a Accessibility Survey for Chrysler building which is located at Windsor Downtown. 

[Survey_ChryslerDowntown.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/802763/Survey_ChryslerDowntown.docx)

**Comment by baseer110** [comment]
Accessibility Survey for Devonshire Mall which comes under the category of shopping and entertainment 

[Survey_Devonshire.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/802768/Survey_Devonshire.docx)

**Comment by baseer110** [comment]
Accessibility Survey for Holiday Inn located at Windsor Downtown which comes under the category of accommodation.  

[Survey_HolidayInDowntown.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/802771/Survey_HolidayInDowntown.docx)

**Comment by baseer110** [comment]
Accessibility survey for Scotia bank located at Windsor Downtown which lies under the category of financial.
  
[Survey_ScotiaBankDowntown.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/802777/Survey_ScotiaBankDowntown.docx)

**Comment by baseer110** [comment]
Accessibility survey for Shoppers drug mart located at ouellette & wyandotte cross section which lies under the category of Shopping.
[Survey_ShoppersDrugMart.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/802785/Survey_ShoppersDrugMart.docx)

**Comment by baseer110** [comment]
Accessibility survey for Starbucks located at Windsor downtown which comes under the category of restaurant.

[Survey_StarbucksDowntown.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/802788/Survey_StarbucksDowntown.docx)

**Comment by baseer110** [comment]
I have a question that whenever you visited any hotel like holiday Inn so there is Wifi available for only who checked in there not for guests so In that case what should write for free Wifi ? or we should have another field regarding free wifi for guests ?

**Comment by Blandine-AA** [comment]
@baseer110, Good question. What do you suggest?

**Comment by Blandine-AA** [comment]
@baseer110,

Thanks for doing the Survey, but remember what @joshi1983  and I said... The goal of the discovery is not to fill the surveys as those data will not be used, but to evaluate the criteria that we use. How easy was it for you to answer to the questions? Are they clear enough? Are you taking any photo to help explaining the criteria that are not clear or that could help understanding the criteria?

As a reminder, this is an excerpt of our emails to @JaveriyaKhan  and yourself.
From Josh 
> Remember that the goal is to improve the question list.  The task isn't to rate as many locations as possible but to put the questions to a practical test see if any improvements are needed to make them clearer, new questions added, questions merged, or any other improvements you find.  Rating locations is a means to a different end goal than data collection.  Since the questions you're answering will be tweaked and the meaning changed, we won't make much use of the rating data you collect.

From me
> because it is a team activity, and **as a team you will challenge each other when doing the discovery TOGETHER. There should be only ONE report per team.** Remember, because you work "full-time", you need to cover all 12 categories and at least all criteria in the list. You may propose extra criteria to add to the list based on your discovery and interviews.

Covering all categories is just for you to be able to evaluate the same criteria from a different perspective and provide a more objective feedback.

I would expect recommendations and/or questions for the overall survey. 

Hope this helps,

**Comment by JaveriyaKhan** [comment]
We have find out some extra questions by researching on the united nations website. We have taken out some questions which might be helpful for our survey.

resource : http://www.un.org/esa/socdev/enable/designm/AD5-01.htm
1) ELEVATORS

a) Insufficient opening time interval

1) PLATFORM LIFTS
1. PROBLEM IDENTIFICATION
Changes in level between indoor and outdoor areas. 
Changes in level inside a building. 
Insufficient space for ramps. 

2) STAIRS

PROBLEM IDENTIFICATION
Steep staircases. 
Poorly designed steps that hinder foot movement.

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Tecumseh Mall, here are the some points to summarize:

[Survey_Tecumseh_mall.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/809485/Survey_Tecumseh_mall.docx)

1) We found that the criteria is mentioned are sufficient  and it covers all the points.
But we want some clarification on the some of the points like:
a) Ceiling track lift available
b) Large weight capacity change table in private area
c) Ceiling track lift available in medical office
d) Assisted Listening Devices available -- like what devices can be used 

We noticed in mall that, it is quit equipped for the people who are on wheelchair but we found that its very difficult for the visually impaired people. The mall is not equipped for the visually impaired people. There is no Braille signage present at the exit doors.
1) Automatic doors
![image2](https://cloud.githubusercontent.com/assets/23346995/23442089/80914ae6-fdf4-11e6-9142-c8f295ad6611.JPG)

2)Curb cuts that are even with paved surface  

![image3](https://cloud.githubusercontent.com/assets/23346995/23442100/91dc56f6-fdf4-11e6-9c5a-632958d67d15.JPG)

3)Large print written information available 

![image4](https://cloud.githubusercontent.com/assets/23346995/23442106/9be1e3d2-fdf4-11e6-880d-c0f1be71f9a7.JPG)

4)Wide doorway - width over 38”( Allows wheelchair access)
![image5](https://cloud.githubusercontent.com/assets/23346995/23442111/a28c9538-fdf4-11e6-9f2b-26312cb4dece.JPG)

5) Wide aisles 

![image](https://cloud.githubusercontent.com/assets/23346995/23442284/91435aea-fdf5-11e6-9c06-f0bb9ffe2821.png)

**Comment by Blandine-AA** [comment]
@JaveriyaKhan, regarding 

> 1. We found that the criteria is mentioned are sufficient and it covers all the points.
But we want some clarification on the some of the points like:
a) Ceiling track lift available
b) Large weight capacity change table in private area
c) Ceiling track lift available in medical office
d) Assisted Listening Devices available -- like what devices can be used

I guess if you want some clarification, it means that the questions are not clear enough. So, what type of information would want to see? What are you looking for? What question comes to mind when reading the questions that makes it no clear?

**Comment by JaveriyaKhan** [comment]
Actually we do not know what is "Ceiling track lift available" is that mean platform lift? 
What is the Large weight capacity change table in private area?
What is Ceiling track lift available in medical office?
We do not know about this criteria, we even asked this questions to the person who works in the restaurant, office building. 

If you can give a small explanation about this questions so it would be very helpful for us.

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Edifice Paul Martin Building (Public Service), here are the some points to summarize:
[Survey_Edifice_Paul_Martin_Building.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/815830/Survey_Edifice_Paul_Martin_Building.docx)

The building is quite equipped for the people on wheel chair. Building has automatic doors, ramp. It also have the big bathrooms equipped all the facilities needed for the people on the wheelchair . But they do not have much facilities for partially impaired people. The elevators are equipped with the braille signage
on the buttons but no audio in the elevators to tell about the floors. 

Actually we are not allowed to go inside the building we took the most of the information from the people who are working in the office in the building. This building is secure building so we didn't allow to access the place. However people assisted with the information on the basis of that we have filled the data.

We got the access to take the photos from outside.

/home/atish/Downloads/image3(1).JPG
/home/atish/Downloads/image2(1).JPG
/home/atish/Downloads/image1.JPG

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Starbucks (Restaurant), here are the some points to summarize:

[Survey_Starbucks_Downtown.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/815843/Survey_Starbucks_Downtown.docx)

Starbucks is well equipped for the people on the wheelchair but it lacks the facilities for the blind and people with hearing problem.

We noticed that starbucks do not have the parking but the public parking is present the behind the building. There is no brightly marked curbs present. It has automatic entrance gate, wide area access for the people with the wheelchair. No unisex washroom available as it is a small place.

1) No brightly marked curbs

![image4 1](https://cloud.githubusercontent.com/assets/23346995/23538782/db88865c-ffa3-11e6-9418-a26b38502c0d.JPG)

2) Automatic doors

![image5 1](https://cloud.githubusercontent.com/assets/23346995/23538788/e8cefea4-ffa3-11e6-900f-9775c4b466e2.JPG)

3)Removable chairs 

![image6](https://cloud.githubusercontent.com/assets/23346995/23538790/f05ab050-ffa3-11e6-9567-efc286a51635.JPG)

4) Enough place for wheelchair to move around

![image7](https://cloud.githubusercontent.com/assets/23346995/23538796/01f9e0a6-ffa4-11e6-95a1-2442a33716ab.JPG)

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Scotia Bank Downtown (Financial ), here are the some points to summarize:
[Survey_Scotia_Bank_Downtown.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/815870/Survey_Scotia_Bank_Downtown.docx)

Scotia Bank is not equipped for the partially impaired people and the people with hearing problems. No braille signage present at the exit doors also no facilities for the people with hearing problems and we also noticed that there is no washrooms available to use for the customers.

1) No brightly marked curbs 

![image1](https://cloud.githubusercontent.com/assets/23346995/23539074/a40a53ba-ffa6-11e6-8eca-ec769d1d22f7.JPG)

2) Automatic doors

![image2](https://cloud.githubusercontent.com/assets/23346995/23539083/b3316400-ffa6-11e6-8c8c-97b656f38b51.JPG)

3) Chair with armrests 

![image3](https://cloud.githubusercontent.com/assets/23346995/23539096/cd738c44-ffa6-11e6-8c94-e075ee5e4ed8.JPG)

4) low counters height

![image4](https://cloud.githubusercontent.com/assets/23346995/23539145/136912be-ffa7-11e6-8e3b-7855219e93f4.JPG)

5) Large public area

![image5](https://cloud.githubusercontent.com/assets/23346995/23539149/1971bc88-ffa7-11e6-9a58-c242c99be919.JPG)

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Holiday Inn Downtown (Accommodation), here are the some points to summarize:
[Survey_Holiday_Inn_Downtown.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/815932/Survey_Holiday_Inn_Downtown.docx)

Holiday Inn is well equipped with all the facilities for the people with disabilities. They have automatic entrance gates, hearing aide facility they also have alarm bell, flash door bell for visually impaired and Text Telephone or TTY for the deaf people. 
The cafeteria is also have wide aisles for the movement of wheelchair properly and special assistance also available.
We noticed that they do not have the designated parking for the disable people however we searched for the place but we did not locate the area. Elevators are not having the visual and audible indicators also no automatic verbal announcement indicating going up/going down. No brightly marked curbs.
We didn't get the chance to see the washrooms, but the front desk representative told us that washrooms are well equipped with the facilities needed for people with disability.

1) Parking lot with no designated parking for the disable people

![image6](https://cloud.githubusercontent.com/assets/23346995/23539908/2ac40c02-ffac-11e6-943d-1b0aee94e23a.JPG)

2)Automatic Doors

![image7](https://cloud.githubusercontent.com/assets/23346995/23539910/2fd69624-ffac-11e6-8294-c86244ec94d0.JPG)

3) Large public area

![image8](https://cloud.githubusercontent.com/assets/23346995/23539915/339dbf08-ffac-11e6-9ef2-f1fbff681948.JPG)

4)Elevator buttons with the braille signage 

![image9](https://cloud.githubusercontent.com/assets/23346995/23539920/37d5dfa6-ffac-11e6-96d6-e82706259fb9.JPG)

5) Exit doors with no braille signage

![image10](https://cloud.githubusercontent.com/assets/23346995/23539925/3bea4e1a-ffac-11e6-8f25-f4757d9e26a4.JPG)

**Comment by joshi1983** [comment]
Those images look quite useful.  When the location image gallery feature is working, we could include a lot of these images as seed data so we have some images in the gallery to show people.  We could also use some of these images if we end up creating explanation pages for each of our checklist questions.  Maybe a gallery of images associated with each checklist question could help explain what each question is looking for to users who can see.

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Lambton Tower, University of Windsor (Education), here are the some points to summarize:
[Survey_Lambton_Tower.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/822027/Survey_Lambton_Tower.docx)

Lambton tower is quite equipped for the people on the wheel chair. It lacks the facilities for the partially impaired people and people with the hearing problem. But building has the bright signs available on the entire building so people with the hearing problem can identify the place with the signage. No much facility for partially impaired people, braille signage available at the exit doors.

![image1](https://cloud.githubusercontent.com/assets/23346995/23622233/e380d754-026b-11e7-974c-dbe0b623c4a0.JPG)

![image2](https://cloud.githubusercontent.com/assets/23346995/23622234/e38126be-026b-11e7-96e9-e7c490974a8d.JPG)
![image3](https://cloud.githubuserconten
![image5](https://cloud.githubusercontent.com/assets/23346995/23622321/2e6aa20e-026c-11e7-9155-ae375bde016c.JPG)
t.com/assets/23346995/23622306/1ef4ae64-026c-11e7-824b-79ba6a837ce5.JPG)
![image4](https://cloud.githubusercontent.com/assets/23346995/23622317/2879d220-026c-11e7-9de1-5f152754d4bb.JPG)
![image6](https://cloud.githubusercontent.com/assets/23346995/23622354/48ecc7ec-026c-11e7-945e-c219de819e57.JPG)
![image7](https://cloud.githubusercontent.com/assets/23346995/23622359/4f604798-026c-11e7-8e05-dbd12effd1cd.JPG)

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Assumption Park (Parks), here are the some points to summarize:
[Survey_Assumption_Park.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/822087/Survey_Assumption_Park.docx)

Assumption park is not properly equipped for people with disabilities.Park has the parking facility for people on wheel chair. Bright signs are available but no facility for partially impaired people and people with hearing problems. Also there is no access to washroom, we noticed that washrooms are closed from long time and there is no designated path to reach to washroom for people on wheel chair.

![image1](https://cloud.githubusercontent.com/assets/23346995/23623224/397f687a-026f-11e7-9c38-fd349a3fd3b5.JPG)

![image2](https://cloud.githubusercontent.com/assets/23346995/23623225/397fa5ec-026f-11e7-881e-cbd717dbf4b0.JPG)

![image3](https://cloud.githubusercontent.com/assets/23346995/23623238/50ee34dc-026f-11e7-85ba-b30e9344eb51.JPG)

![image4](https://cloud.githubusercontent.com/assets/23346995/23623244/58f4238a-026f-11e7-87b4-9c5716be0af9.JPG)

![image5](https://cloud.githubusercontent.com/assets/23346995/23623257/6721e802-026f-11e7-8bdb-fbdbd8ed0089.JPG)

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Windsor Bus Terminal (Transportation), here are the some points to summarize:
[Survey_Windsor_Bus_Terminal.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/822128/Survey_Windsor_Bus_Terminal.docx)

Windsor bus terminal is equipped with the basic facilities needed for people with the disabilities. We noticed that this place is having all the facilities needed for the people on wheel chair. But less facility for visually impaired and people with the hearing problem. 
But we also noticed that this place has braille signage available at the exit doors.

![image1](https://cloud.githubusercontent.com/assets/23346995/23623950/f4d98450-0271-11e7-85ff-ef96364ea583.JPG)

![image2](https://cloud.githubusercontent.com/assets/23346995/23623981/17834aae-0272-11e7-8fef-9bac533fb479.JPG)

![image3](https://cloud.githubusercontent.com/assets/23346995/23623989/1eca58e8-0272-11e7-858b-b48765d15e9e.JPG)

![image4](https://cloud.githubusercontent.com/assets/23346995/23624018/2fc9d506-0272-11e7-9ccb-642c7e220f82.JPG)

![image5](https://cloud.githubusercontent.com/assets/23346995/23624026/379d91dc-0272-11e7-9bd3-27396515def0.JPG)

![image6](https://cloud.githubusercontent.com/assets/23346995/23624034/42e064ac-0272-11e7-9c53-d7279531ece1.JPG)

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Windsor Art Gallery (Arts & Entertainment), here are the some points to summarize:
[Survey_Windsor_Art_Gallery .docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/822186/Survey_Windsor_Art_Gallery.docx)

This place is having well facilities for the people with the disabilities. It has the map information of building with braille information so that people with partially impaired can access the building easily. Also this place provides the wheel chairs who needs this and they provide special assistance for people with disabilities. 

![image1](https://cloud.githubusercontent.com/assets/23346995/23624804/041542da-0275-11e7-8e99-c1d57ed4e34b.JPG)

![image2](https://cloud.githubusercontent.com/assets/23346995/23624810/0abd1d1a-0275-11e7-9c79-d7c139d9d949.JPG)

![image3](https://cloud.githubusercontent.com/assets/23346995/23624813/1113b3ea-0275-11e7-914d-9309941dc450.JPG)

![image4](https://cloud.githubusercontent.com/assets/23346995/23624814/111f586c-0275-11e7-9ca0-0630c685f2a5.JPG)

![image5](https://cloud.githubusercontent.com/assets/23346995/23624837/22925630-0275-11e7-9338-7e66e1bec858.JPG)

![image6](https://cloud.githubusercontent.com/assets/23346995/23624857/30fd1282-0275-11e7-8049-9a3f7f906232.JPG)

![image7](https://cloud.githubusercontent.com/assets/23346995/23624844/28ff0b9e-0275-11e7-8677-faea59304c17.JPG)

![image8](https://cloud.githubusercontent.com/assets/23346995/23624868/39a71b12-0275-11e7-92cf-80dd13814b6f.JPG)

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Filipino Community Center, 935 Northwood Street (Association & Organization), here are the some points to summarize:
[Survey_Filipino_Community_Center.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/822229/Survey_Filipino_Community_Center.docx)

This place is having basic facilities for the people on wheel chair. It has no facilities for partially impaired and people with the hearing problems.

![image1](https://cloud.githubusercontent.com/assets/23346995/23625549/8f2319ae-0277-11e7-9950-57ff4f7dbb7b.JPG)

![image2](https://cloud.githubusercontent.com/assets/23346995/23625553/963c62a4-0277-11e7-89e4-9bbeedb08fb4.JPG)

![image3](https://cloud.githubusercontent.com/assets/23346995/23625560/9d14a230-0277-11e7-85c7-c1a5c51102c3.JPG)

![image4](https://cloud.githubusercontent.com/assets/23346995/23625565/a28e8316-0277-11e7-9b5c-bd6bd10e5baf.JPG)

![image5](https://cloud.githubusercontent.com/assets/23346995/23625570/a9898a76-0277-11e7-8d31-23abf3f8df80.JPG)

**Comment by baseer110** [comment]
Accessibility survey for Windsor Regional Hospital (Health care), here are the some points to summarize:

Windsor regional hospital is having all the facilities for the people with the disability. Actually when we approached to the human resource department for the more information for accessibility options available in the hospital. They said us that they will provide the information on the mail but we did not hear anything from them despite we visited two times to hospital. So we put the information as we noticed by us. 
However the hospital is having all the basic facility for the people with the disability. But we noticed that for visually impaired people the facility lacks for them. As there is no braille information is available for them to access the building. 

Here are the images of the hospital.

![image1](https://cloud.githubusercontent.com/assets/4041079/24056989/1c28d7a6-0b1c-11e7-8323-00206840fd42.JPG)

![image4](https://cloud.githubusercontent.com/assets/4041079/24056995/269a6dd0-0b1c-11e7-9a49-b21f75d3edc1.JPG)

![image3](https://cloud.githubusercontent.com/assets/4041079/24056996/269bc432-0b1c 11e7-9867-13dde6e22fc8.JPG)

![image2](https://cloud.githubusercontent.com/assets/4041079/24056997/269caef6-0b1c-11e7-9cc5-73cfd1b9fc84.JPG)

![image9](https://cloud.githubusercontent.com/assets/4041079/24057021/4504a024-0b1c-11e7-86c8-8f9f696b5731.JPG)

![image8](https://cloud.githubusercontent.com/assets/4041079/24057023/4506e3ac-0b1c-11e7-8621-4b75f92aa8a3.JPG)

![image7](https://cloud.githubusercontent.com/assets/4041079/24057024/45073b68-0b1c-11e7-849f-ae116a195e3e.JPG)

![image6](https://cloud.githubusercontent.com/assets/4041079/24057022/450696a4-0b1c-11e7-8f17-a669e8dbdf81.JPG)

![image5](https://cloud.githubusercontent.com/assets/4041079/24057025/45074496-0b1c-11e7-87b1-4220da72d8de.JPG)

**Comment by JaveriyaKhan** [comment]
Accessibility survey for Empire Muscle (Sports & Recreation), here are the some points to summarize: 
[Survey_Empire_Muscle.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/851462/Survey_Empire_Muscle.docx)

The Empire Muscle Gym has very limited accessibility options available for the people with disabilities. There is no automatic doors available at the entrance door, washrooms. No grab bars in the washrooms.

However the gym staff available for assistance for people with the disability. Staff is friendly with the people with the disabilities.

![image3](https://cloud.githubusercontent.com/assets/23346995/24057820/20796372-0b1f-11e7-8550-630c71fa25f7.JPG)

![image2](https://cloud.githubusercontent.com/assets/23346995/24057821/207e24a2-0b1f-11e7-8ef8-fc1bcd7f4a07.JPG)

![image1](https://cloud.githubusercontent.com/assets/23346995/24057819/2079222c-0b1f-11e7-9994-ee97df1926e8.JPG)

**Comment by Blandine-AA** [comment]
Re-opening the issue as closing it does not allow review and team discussion.

**Comment by Blandine-AA** [comment]
@baseer110 , @JaveriyaKhan , this is a  lot of work done for this discovery activity. Great job!

It will be interesting to share your experience with the rest of the team at next meeting. and we will review some of your proposals

I hope you feel like you better grasp of what we are trying to build and the challenges people with disabilities face on a daily basis.
