### ISSUE TITLE
Discovery Activity : Accessibility Criteria : Balraj, Navroop, Amolbir, Avi & Sukhamrit

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#227]
Find guidelines here : https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/Disability-criteria-discovery-activity-description

Then submit your results here by Friday Feb. 24th for all to have access to it and review

**Comment by joshi1983** [comment]
@Blandine-AA Did you get the feedback on this yet from @balraj18 , @sidhunavroop, and @rickyboparai ?

**Comment by Blandine-AA** [comment]
@joshi1983, no feedback from @balraj18 , @sidhunavroop, and @rickyboparai ?

**Comment by rickyboparai** [comment]
[Accessibility App Survey JMCC_16Feb2017 (1).docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/840356/Accessibility.App.Survey.JMCC_16Feb2017.1.docx)

**Comment by Blandine-AA** [comment]
@balraj18 , @sidhunavroop, and @rickyboparai, This is not what was requested in this tasks. You filled the survey, but there is no indication of the building that was evaluated, neither your reflexions on the proposed criteria list. The goal of the discovery exercice is to improve the criteria list not to do the survey. There are other people who did the survey.

So, I am re-opening this issue.

Read the directions provided and if you cannot do the task, then let @joshi1983 and myself know. 
Also, when submitting your **report**, change the file name, as it makes it confusing with the original criteria file name. You can the example of what the other team member did.

As developer, requirement analysis and understanding is as important as programming.

**Comment by Blandine-AA** [comment]
@joshi1983 , it looks like Amolbir is not on github!

**Comment by joshi1983** [comment]
@Blandine-AA yes I emailed him asking that on March 12 but haven't seen a reply yet.  I replied and forwarded those emails to you for your information.  I'll bring it up to him in tonight's meeting too.

**Comment by gillbalraj** [comment]
Under the elevator category, I seems like these two fields have the same meaning- "Elevator has room for wheelchair to turn" and "No room for wheelchair to turn Enter straight/out straight  "

**Comment by rickyboparai** [comment]
![img_2461](https://cloud.githubusercontent.com/assets/25445443/24279346/b32735c8-101f-11e7-842c-e9ac57455c66.JPG)
![img_2462](https://cloud.githubusercontent.com/assets/25445443/24279347/b3275c06-101f-11e7-8fe5-8c080c21e408.JPG)
![img_2465](https://cloud.githubusercontent.com/assets/25445443/24279350/b329498a-101f-11e7-9f84-1c1af947ee93.JPG)
![img_2447](https://cloud.githubusercontent.com/assets/25445443/24279351/b32aba7c-101f-11e7-9095-f2e347f9fa5e.JPG)
![img_2450](https://cloud.githubusercontent.com/assets/25445443/24279349/b328befc-101f-11e7-8984-5122af8bc1f0.JPG)
![img_2451](https://cloud.githubusercontent.com/assets/25445443/24279348/b3289468-101f-11e7-90fe-2e8e395b56d1.JPG)
![img_2452](https://cloud.githubusercontent.com/assets/25445443/24279354/b3347120-101f-11e7-8053-068b070b63df.JPG)
![img_2456](https://cloud.githubusercontent.com/assets/25445443/24279353/b333b032-101f-11e7-8531-418d813a8f64.JPG)
![img_2458](https://cloud.githubusercontent.com/assets/25445443/24279352/b3339458-101f-11e7-9547-52133eccc870.JPG)
![img_2460](https://cloud.githubusercontent.com/assets/25445443/24279355/b337e800-101f-11e7-941e-ecefec0d4dc0.JPG)

**Comment by Blandine-AA** [comment]
Thanks @gillbalraj  for the feedback. You raised interesting points. More explanations on the pictures will be useful too.

**Comment by Blandine-AA** [comment]
Thanks @rickyboparai for the photos, but more explanations on the pictures will be useful. What criteria are you evaluating here? Is it any problem?

**Comment by rickyboparai** [comment]
[aquatic centre_Downtown.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/866831/aquatic.centre_Downtown.docx)

**Comment by rickyboparai** [comment]
I was editing everything and now everything is done. Hope you will like it.

**Comment by Blandine-AA** [comment]
Thanks @rickyboparai for the effort to finish this task and provide your feedback. We will discuss your (and all of you) experience doing the activity and finalize the criteria list at tonight's meeting.
