### ISSUE TITLE
Discovery Activity : Accessibility Criteria : Chris, Rumana & Areeba

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#228]
Find guidelines here : https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/Disability-criteria-discovery-activity-description

Then submit your results here by Friday Feb. 24th for all to have access to it and review

**Comment by areebakamal** [comment]
I reviewed Essex Building. 
[Accessibility App Survey JMCC_16Feb2017.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/800931/Accessibility.App.Survey.JMCC_16Feb2017.docx)

•	The building is quite big and is divided into different sections. There’s a physics wing, chemistry wing and then the area where the Computer Science rooms are. When it comes to the following criteria: “Wheelchair accessible counters at reception/service has under counter clearance”, technically it doesn’t apply as there are no reception or service areas. However, when it comes to chemistry labs, there are counters that would be applicable to the end user. I was thinking maybe for larger buildings we could divide it like Essex-Physics or Essex-Chemistry. Not sure how that would play into the database. 
•	I then thought it might get complicated as that sort of data is probably not available and dropped the idea altogether. However, a more feasible idea is that I do think that we should do subsections for all applicable buildings in University of Windsor. As a potential student, I would definitely want to know if where my classes will take place is an accessible area or not if it's a subsection of a building. If my preference for a major was strong, I would search for another University. If location was important to me, I may pick a major where classes and labs take place in an accessible environment. 
[Accessibility App Survey JMCC_16Feb2017.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/800935/Accessibility.App.Survey.JMCC_16Feb2017.docx)

•	For the elevator category, perhaps the first question should be is there an elevator. Once the user hits no, then that category should be greyed out/ skipped.
•	“Sensor hand dryer”..maybe we should put “working sensor hand dryer” or ‘sensor hand dryer in service”
•	 Closed captioning on display screens criteria.. maybe add (CC) after “closed captioning. 
•	“Curb cuts are brightly marked “I think we should add “tactile paving” and under the ‘i-information button’ maybe should one of the images below. 
![800px-truncated_domes](https://cloud.githubusercontent.com/assets/23005093/23328181/73c0cd22-fae9-11e6-9971-99a04cd2be10.jpg)
![9e38618de767f7ded737e91395a95594](https://cloud.githubusercontent.com/assets/23005093/23328182/73c3764e-fae9-11e6-8c60-306942079518.jpg)

**Comment by areebakamal** [comment]
Rumana's review is here: https://github.com/hhaccessibility/hhaccessibility.github.io/issues/230

**Comment by Blandine-AA** [comment]
@areebakamal @RumanaHakeem ,

Issue 230 is not the place to submit the criteria reviews. It is for the existing apps evaluation only. I**f Rumana did a separate review, it should be submitted under this issue**. so, I have remove the comment added in 230.

**Comment by RumanaHakeem** [comment]
Hi Bladine,
I got confused between the two issues. posing my review here now.
Thanks.
[Accessibility App Survey JMCC_16Feb2017.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/801586/Accessibility.App.Survey.JMCC_16Feb2017.docx)
![whatsapp image 2017-02-24 at 18 05 55](https://cloud.githubusercontent.com/assets/22264264/23335427/73d3b21c-fb83-11e6-8997-620209456f98.jpeg)
![whatsapp image 2017-02-24 at 18 05 55 1](https://cloud.githubusercontent.com/assets/22264264/23335429/73d4be0a-fb83-11e6-80d8-1adef34a89d3.jpeg)
![whatsapp image 2017-02-24 at 18 05 56](https://cloud.githubusercontent.com/assets/22264264/23335431/73d72398-fb83-11e6-978b-83b17e0108aa.jpeg)
![whatsapp image 2017-02-24 at 18 05 56 1](https://cloud.githubusercontent.com/assets/22264264/23335428/73d3cf72-fb83-11e6-8bce-e95e76ce1c05.jpeg)
![whatsapp image 2017-02-24 at 18 05 58](https://cloud.githubusercontent.com/assets/22264264/23335430/73d5cb42-fb83-11e6-8579-e91ccc5e0f09.jpeg)
![whatsapp image 2017-02-24 at 18 06 01](https://cloud.githubusercontent.com/assets/22264264/23335432/73d82bda-fb83-11e6-8890-25c62cb6fb79.jpeg)
![whatsapp image 2017-02-24 at 18 15 50](https://cloud.githubusercontent.com/assets/22264264/23335433/73e133a6-fb83-11e6-87c1-3b438a1972a0.jpeg)

**Comment by RumanaHakeem** [comment]
The location is Tim Hortons at 2220 Wyandotte St E, Windsor, ON N8Y1E7 . From my research I observed that the categories chosen for the criteria evaluation are good enough to evaluate a particular place. However, a few terms were not familiar to me.If the terms can be made simpler, it would be an enhancement.

**Comment by Blandine-AA** [comment]
@RumanaHakeem,
Please specify the criteria that were not clear to you. That's the goal of the exercice :). You also need to specify to what criteria the pictures you posted apply.

**Comment by Blandine-AA** [comment]
@e1cerebro , you haven't provided any feedback on this activity. Is it because you didn't do it or you did it with @areebakamal  and/or @RumanaHakeem ?

**Comment by e1cerebro** [comment]
I did it with Areeba, but she uploaded the report with her GitHub account.

**Comment by Blandine-AA** [comment]
@e1cerebro , when asked Areeba, she didn't mention that you did it together. On the contrary! 
So, It is not a matter of uploading the report with someones github account. when it is a team project, it has to be a team report and Areeba's report wasn't a team report. Thus, there was no evidence for us that you did the activity with her or somebody else.

Do you have any feedback to provide from your perspective?
