### ISSUE TITLE
Home page : Zoom when pointing on categories

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#236]
- [ ] After the first round of testing, the user would like to see the category box zooming out when pointing on it, so that it clearly shows what is going to be selected.
- [ ] Also see how the details in the info box can be integrated and made more visible for the user. See #122 !
- [ ] Consider impact on screen readers

![image](https://cloud.githubusercontent.com/assets/20052162/23435894/a1d57902-fdd6-11e6-9d73-49d96ac321d5.png)

**Comment by joshi1983** [comment]
The following change was deployed to [http://app.accesslocator.com](http://app.accesslocator.com):
![image](https://cloud.githubusercontent.com/assets/11838191/23582315/f3ae725c-00f5-11e7-952d-359f94947c07.png)

The hover background was set to pure black and the font size was increased a little while hovering to make the hover state move noticable.

**Comment by joshi1983** [comment]
The new #242 will address some of the problems from this issue.

**Comment by joshi1983** [comment]
This issue is very similar to #122.  It is arguably a duplicate.

**Comment by Blandine-AA** [comment]
Makes the trick. Ok for me :) !
