### ISSUE TITLE
User Profile: Fix bug with browser cache concealing updates to newly uploaded photos

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#237]
On the user profile, upload different images a few times and eventually you'll run into a seemingly random cache management bug where the new image doesn't appear immediately.  When you press CTRL+SHIFT+R, you'll see the new image.

Adjust the image source to be different every time the page loads but that would mean the cached version is never used and is therefore using bandwidth less than optimally.  One way this could be implemented is by moving the background-image from app.scss to some inline styles set using JavaScript that appends a random string or current time to the URL.

Here are the suggested steps for tackling this task:
- [x] Reproduce the bug on your computer.
- [x] Investigate a solution and solve the problem in a simple way.  Adjusting the background-image URL using JavaScript to append the current time in milliseconds should work.
- [x] Make a pull request for the simple solution.

**Comment by Blandine-AA** [comment]
@areebakamal , do you want to continue working on this?

**Comment by areebakamal** [comment]
Would something like this work? 
![image](https://cloud.githubusercontent.com/assets/23005093/23882022/72693e16-0834-11e7-9f0d-c8c5cc623a7f.png)

**Comment by areebakamal** [comment]
@Blandine-AA I can try it over the next couple days and will reassign if it's incomplete.

**Comment by joshi1983** [comment]
@areebakamal yes including a time from now could work.  The path could be something like '/profile-photo?' + new Date().getTime().

That simple solution would get this issue mostly done the quickest.  I would recommend implementing something like that to start.

I mentioned some more challenging things too but they might not be worth the effort and complexity they would add.

Would you like to take this issue on after finishing #210?

**Comment by joshi1983** [comment]
I merged a pull request similar to what Areeba mentioned.  It implements the simplest solution.  I also removed mention of a more complex solution from the issue's description because that would be too complex to be worth explaining to developers and having to maintain.

**Comment by kimficara** [comment]
@joshi1983 , when I created an account and signed in for the first time the profile picture was automatically set as Dr. Stephanos.  I changed the picture 5 times and went to different pages and signed out and back in between and there were no issues there, just when I originally created my profile.

**Comment by joshi1983** [comment]
Yeah that is a funny side effect of me not clearing out old image files when recreating the database when deploying changes.  I'll update the way I deploy so that users will have no profile photos when they create new accounts.  For now, they could get a previous user profile from an old version when a new user reuses an old user id.

**Comment by kimficara** [comment]
I created a new account and the default picture was properly set this time.  I also uploaded about 10 different pictures and had no issues there either.

**Comment by joshi1983** [comment]
I created a couple scripts on the host called clear-db-files which should be run every time the database is recreated.  As long as I remember to run them appropriately and maintain them, this won't happen again.

I'm closing because both the cache issue and the deployment mistakes should be fixed now.
