### ISSUE TITLE
Replace logo graphics with scaled versions of our new SVG

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#238]
There are some very subtle differences between the current logo graphics and our new SVG that we want to completely eliminate.  This task won't require any programming but some usage of graphic editing software such as Photoshop or GIMP.

This will include the following subtasks:
- [x] Replace the favicon at hhaccessibility.github.io\app\public\favicon.ico with a 16 by 16 ico formatted version on a white background
- [x] Replace the logo used in the top-left of every page.  This is at hhaccessibility.github.io\app\public\images\logo.png and should be 56 by 56 pixels with a transparent background.

The new logo is at [https://github.com/hhaccessibility/hhaccessibility.github.io/files/805613/logoeditedsvg.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/805613/logoeditedsvg.zip).

**Comment by Blandine-AA** [comment]
@joshi1983, since @RumanaHakeem laptop is not setup for programming, can this be assigned to her?

**Comment by joshi1983** [comment]
It helps that no coding is required but she won't be able to test her changes.  @RumanaHakeem do you have graphics software for this task?  For submission, you could zip up the 2 images(favicon.ico and logo.png) and attach them to a comment like you did with the presentation site or you could use git and make a pull request that replaces those files.

@RumanaHakeem do you want to take this on?

**Comment by RumanaHakeem** [comment]
Sure, I'll do it.
Thanks.
Rumana.

**Comment by joshi1983** [comment]
@RumanaHakeem how's it going?  Any trouble loading, scaling, or attaching the graphics?

**Comment by RumanaHakeem** [comment]
Hi Josh,
I am done with it. Attaching the zipped folder with the files.
Thanks.
[images.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/836204/images.zip)

**Comment by joshi1983** [comment]
I committed and merged Rumana's work and the new logo graphics are on both [demo.accesslocator.com](http://demo.accesslocator.com) and [app.accesslocator.com](http://app.accesslocator.com).

I'm closing this issue now because the issue is complete.
