### ISSUE TITLE
Create promotional video for Digifest

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#240]
A wiki article was started on the scripts at https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/Promotional-Video-for-Digifest that will be adjusted to describe what we want.

**Comment by joshi1983** [comment]
@stephanosm do you think you can find a club who may voluntarily develop this video for us?  @areebakamal that was your suggestion in our meeting, right?

**Comment by stephanosm** [comment]
I will ask next week to see who can help us.

**Comment by joshi1983** [comment]
@JaveriyaKhan was assigned also to start writing a script for this video.

**Comment by stephanosm** [comment]
I am in discussion with the Media department of the school to create the video for Digifest. I am waiting for more information on the dates and possible cost.

**Comment by Blandine-AA** [comment]
From @stephanosm last update, there will not be any video created for Digifest. Closing this issue!
