### ISSUE TITLE
Home page: show description of hovered location category show at bottom of browser

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#242]
Test feedback showed that the location categories on the home page had descriptions that were too small to easily read.  We want to instead add an element at the bottom of the web browser that appears when hovering over a category that describes the category in large font.

Here is how it looks now:
![image](https://cloud.githubusercontent.com/assets/11838191/23582739/c8a9d3e0-00fe-11e7-9842-252d2c41aa17.png)

Here is a rough illustration of how we want it to look:
![image](https://cloud.githubusercontent.com/assets/11838191/23582960/1eeb0ade-0105-11e7-801d-0215d25c30d7.png)

The HTML for the home page can mostly be found in hhaccessibility.github.io\app\resources\views\pages\home.blade.php.

**Suggested implementation and subtasks**
- [x] Create a JavaScript file in a location like public/js/home.js that removes all the title attributes from the location category elements in the document but keeps those stored in a variable.  Bind to mouse events so that when the user hovers over a category, an element is added to the bottom of the screen that shows the corresponding description.  These bindings can be done using jQuery's bind method or JavaScript's addEventListener instead of changing the HTML to keep our JavaScript more [unobtrusive](https://en.wikipedia.org/wiki/Unobtrusive_JavaScript). 
- [x] Test the new description element at very narrow resolutions.  You can do this by resizing your web browser down to 300 or 350 pixels wide.  Check that the description element doesn't prevent anyone from accessing the lowest categories.  Scroll up and down and verify that the description element will always stay on the bottom of the web browser.  It shouldn't move with the rest of the page.
- [x] Clean up the implementation.  Use hhaccessibility.github.io\app\resources\assets\sass\app.scss for any CSS you use such as setting position to fixed and bottom to 0 for the category description element.  Minimize use of inline styles or positioning elements using JavaScript by defining that in app.scss.
- [x] Make a pull request but don't merge it.

This is related to #236.

**Comment by Blandine-AA** [comment]
@joshi1983, can this be assigned to @jasjeetsinghsra?

**Comment by joshi1983** [comment]
@Blandine-AA @jasjeetsinghsra requested to work on the same issues as Sukamrit to start with and his laptop still isn't set up so he's not ready to work on anything yet so I doubt he'd be ready for this for another couple weeks at least.

**Comment by Blandine-AA** [comment]
Ok @joshi1983 ! Please, then assign this to whom you see fits. Thanks !

**Comment by joshi1983** [comment]
I'll probably assign this early next week or possibly in this week's meeting.

**Comment by joshi1983** [comment]
This was assigned during Saturday morning's meeting to Avi.

**Comment by joshi1983** [comment]
@avneetdhillon how is the discovery activity and app research going?  Will you be ready to work on this in the next few weeks?  What's keeping you quiet?

**Comment by avneetdhillon** [comment]
HelloSorry I can't attend last few meetings, but I am working on my issues. As this is my last semester and was little busy with university procedures and few exams. Now I am done with these things and will be working again on my issues. I am totally free after couple of weeks and will be able to devote full time to AccessLocator. I am very close on solving discovery activity. I hope you will understand my situation.Thanks
RegardsAvneet Singh Dhillon 

    On Monday, 27 March 2017 7:23 PM, Josh Greig <notifications@github.com> wrote:
 

 @avneetdhillon how is the discovery activity and app research going? Will you be ready to work on this in the next few weeks? What's keeping you quiet?—

**Comment by joshi1983** [comment]
How are the discovery and app comparison tasks going, Avi?  It has been 3 weeks since we last spoke.

If this isn't be done by Friday, April 21, I'd like to take it over so it is done before the Digifest event and can be part of our demo 0.0.3 release.  Other issues can be assigned later if you become confident that you'll have the time to promptly finish them but I want to keep our current issues moving forward regardless of your schedule.

**Comment by joshi1983** [comment]
I discussed this with @gillbalraj and he's taking it over for now.  If he can't finish by Tuesday, I'll take it over to make it available at digifest in case anyone wants to comment on it.

**Comment by joshi1983** [comment]
I won't have time to take this over tonight.  I'll be helping Balraj tonight set up his laptop and releasing demo 0.0.3 instead.

**Comment by joshi1983** [comment]
I tested not using a mouse and the hover text didn't show when giving focus to the location tag links by tabbing through the screen.  I'll probably get this change done tonight.

This is almost ready for testing.  I just wanted to do another couple little things before putting the "Ready for testing" label back on.

Here are some ideas for testing:
- Test on your mobile device(s) to see that the hover element positions properly at the bottom of the page and that the link URL doesn't overlap the actual text
- Test reading the hover text to see that enough time is given to complete reading before the text fades away.  Is it showing too long?  If it stays too long, it could be wasting space.
- Test that the original description/title text can be read by a screen reader.  It was removed for aesthetic reasons but there would be other ways to bring it back if the change hurts the effectiveness of screen reader software.

**Comment by joshi1983** [comment]
This is ready for testing.  The testing instructions are given in the previous comment.

**Comment by sidhunavroop** [comment]
the background looks good with 70% opacity.
But what I feel is that rather displaying what is under that category at the end of the page it should be displayed with that particular category when we bring the cursor on that particular category.

**Comment by Blandine-AA** [comment]
@sidhunavroop , you suggestion was the original design but the size of the text was too small, making it difficult to read. That's why the design was changed this way, not only it is more readable, also it doesn't clutteres the screen. I believe it s also more screen-reader friendly. Correct @joshi1983 ?

**Comment by Blandine-AA** [comment]
@stephanosm, I tested this on my laptop and it works fine. I don't have a smartphone to test on it. Could you please test it on your cellphone? Thanks!

**Comment by stephanosm** [comment]
I am not sure how you hover with a phone   :-)
If I keep the button pressed I get the option to open in new window, etc. The hover text appears at the bottom but not very clearly. It stays reasonable time and then goes away.

**Comment by Blandine-AA** [comment]
@stephanosm , I use the tabulation with the tablet to move from field to field

**Comment by stephanosm** [comment]
I think it's not too bad....we should pass it.
