### ISSUE TITLE
User profile: convert region input into datalist

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#254]
We have the region data in the AccessLocator database now but we don't have a user-interface on the profile page to make use of it.  Adjust the user profile to use a data list and populate the list with region names matching the selected country.

Here is an interactive demo showing the datalist:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist

This breaks down to the following steps:
- [x] Add a new method in hhaccessibility.github.io\app\app\Http\Controllers\ProfileController.php and add a route to it from routes/web.php.  This API should use HTTP method 'get' to download the regions data in JSON format.  You should query them from the region database table.  This could be tested by going to the new route using a web browser and looking at the data.  Use the route "api/regions". You can check [http://app.accesslocator.com/api/locations](http://app.accesslocator.com/api/locations) as an example of a similar API.
- [x] Modify hhaccessibility.github.io\app\resources\views\pages\profile\profile.blade.php to change region's input to assign a list attribute and add a datalist element.  You might want to add some hardcoded options and test in a web browser to see that the input and datalist are linked properly.  In the end, you should leave the datalist element empty, though, because JavaScript should be responsible for populating its options.
- [x] Modify public/js/profile.js to include the functionality to replace the datalist options every time the selected country changes and on initial load.  This will include using jQuery's ajax or get method to call the new api and download the regions.

The new feature should look something like this after typing N in the region field:
![image](https://cloud.githubusercontent.com/assets/11838191/23828324/aac4f410-069c-11e7-808f-e93598820570.png)

This issue is the final part of #212.

**Comment by joshi1983** [comment]
@jasjeetsinghsra and @rickyboparai, are you guys feeling ready to take this on?  It'll involve both JavaScript, ajax, some PHP and tie in with the region table you added recently.

**Comment by rickyboparai** [comment]
we accept it

**Comment by joshi1983** [comment]
Nice.

**Comment by Blandine-AA** [comment]
@rickyboparai , you should pu work on this task on hold until the 2 other initial tasks are completed. They were due in February.

@jasjeetsinghsra , you can continue working on this.

**Comment by joshi1983** [comment]
@rickyboparai and @jasjeetsinghsra when do you think you will likely have this done?  Are you confident to have this done before finishing the VIP program, Sukhamrit?

**Comment by rickyboparai** [comment]
@joshi1983 hi josh jasjeet is having his final exams in first week of april and mine are from second week of april so I will work till first week and he will work afterwards and eventually we will finish this issue by second week of april. Is this fine with you? This is final exams time of everyone. Thanks

**Comment by joshi1983** [comment]
Is that a yes?

**Comment by rickyboparai** [comment]
My vip will finish on 10th april and issue will be finish by 15 th.

**Comment by joshi1983** [comment]
This is broken into 3 subtasks.  Are you going to finish the first subtask by April 10?

This is the task I'm referring to:
Add a new method in hhaccessibility.github.io\app\app\Http\Controllers\ProfileController.php and add a route to it from routes/web.php. This API should use HTTP method 'get' to download the regions data in JSON format. You should query them from the region database table. This could be tested by going to the new route using a web browser and looking at the data. You can check http://app.accesslocator.com/api/locations as an example of a similar API.

**Comment by joshi1983** [comment]
@jasjeetsinghsra do you have questions about this?  I basically did the first subtask on my laptop in the last meeting to show @rickyboparai how to do it.  The only way this becomes really difficult to do is if you don't ask questions.  I can answer anything.

**Comment by jasjeetsinghsra** [comment]
Hi  Josh

My last exam ends on 12. i have exams on 7th 10th and 12th. I will be in
touch with sukhamrit and let you know if I have any doubts on 12th evening.

Regards
Jasjeet

**Comment by Blandine-AA** [comment]
Good luck @jasjeetsinghsra with your exams. I consider that you are off the project from the 4th to the 12th

**Comment by joshi1983** [comment]
This is April 20 and I told Sukhamrit in a Good Friday meeting that I'd take over this issue if it wasn't done by today so I unassigned Jasjeet and Sukhamrit and assigned myself.

**Comment by joshi1983** [comment]
Most of this is complete now except implementing a workaround for Safari.  I added a subtask for that.

**Comment by joshi1983** [comment]
I created a separate issue for the Safari workaround.  I suggest testing this using any browser other than Safari.
To test, do the following:
1. Sign in and open the profile.
1. Pick Canada and type "On" in the State/Province input and notice that only the Canadian provinces and territories show.
1. Pick United States and type something and notice only US states show.

**Comment by intherightdirection** [comment]
This portion when beginning to type made the correct options available in drop down as far as Canada and US go. Upon testing, I ran into another issue which I believe to be on ISSUE 212 so I will mark this as Next Meeting Review for now, and I will attempt to add comment on ISSUE 212.

**Comment by joshi1983** [comment]
@Blandine-AA I won't have time to finish this and the other issues by Saturday morning when I will need to switch to demo release time.  

Let me know how or if we want this feature turned off due to the Failed Testing label you added for the demo 0.0.4 release.

**Comment by Blandine-AA** [comment]
@joshi1983 , I suggest to discuss this with Jared at tomorrow's meeting. Since the problem he found is already covered by issue #212 , we wouldn't need 2 issues to track it. I put "Failed Testing" because Jared has set it for discussion on the next meeting.

Once you agree on what to do with both issues, you can update this issue accordingly.

You have my suggestions already.

**Comment by joshi1983** [comment]
I'm closing this as #212 was closed.  Reasons for closing are in #212.
