### ISSUE TITLE
User Profile : uploading large profile images leads to unclear validation message

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#261]
Based on feedback from #184 testing, we want a clearer message to appear when uploading images that are too large to be processed.

![image](https://cloud.githubusercontent.com/assets/11838191/24065396/f7164dd4-0b40-11e7-8304-755b014ad756.png)

**Comment by Blandine-AA** [comment]
Set a limit on the photo size and have a check before loading the photo so that the user knows ahead of time if his photo meets the size criteria.

**Comment by joshi1983** [comment]
I'll probably get this fixed Monday or Tuesday evening.

**Comment by joshi1983** [comment]
The problem turned out to be limits in memory and upload file size in our PHP configurations.  There were no code changes to fix this but some changes were made to php.ini.  

These changes intentionally maintain limits because we don't want our web application shut down for everyone because someone uploads some outrageously large image.  This does raise the limits considerably, though.  This should help users who upload directly from a digital camera.

Here are a few of the configuration changes:
`upload_max_filesize = 2M`
to
`upload_max_filesize = 20M`

and
`memory_limit = 128M`
to
`memory_limit = 256M`

In the Digital Ocean droplet using SSH.

To test this change, I suggest the following steps:
1. Sign in on [app.accesslocator/signin](http://app.accesslocator/signin) to access your profile.
1. Upload a large image.  By large, I mean 8 to 12 megapixels.  The file size can be between 2MB and 6MB.

**Comment by Blandine-AA** [comment]
@joshi1983 , 20M for a file size seems quite a lot to me. why would some one load a 20 M file as a photo profile? A max limite size of 2M for a profile photo is more than enough. I strongly recommend to keep it!

I can't comment on the memory limit, as I do not understand the impact. I will need some explanation to be able to provide some feedback.

**Comment by joshi1983** [comment]
2M is what it was at before and someone gave feedback that the validation message wasn't clear when uploading large images.  The only way to get a clearer message is to increase the limits.

All of the uploaded graphics are scaled down to roughly 10kb to 50kb so we don't maintain close to even 2MB after the download process completes.

The cases this can apply to were if someone takes a selfie with their iPhone or tablet.  It looks like a typical iPhone photo can be from 2MB to 3.5MB according to:
https://www.google.ca/search?q=5420+Outer+Dr%2C+Windsor%2C&oq=5420+Outer+Dr%2C+Windsor%2C&aqs=chrome..69i57.325j0j7&sourceid=chrome&ie=UTF-8#q=iphone+photo+file+size&*

**Comment by Blandine-AA** [comment]
@joshi1983 , I understand the requirement. What I am saying is that if the photo size is greater than a certain size, we should tell the user that it is too big for what it is needed. This can be seen on many successful apps. We should not just increase the limit size to accommodate all files' sizes.

If a typical iPhone photo is between 2 and 3.5 MB, then let's put the limit to 3.5MB.

**Comment by joshi1983** [comment]
@Blandine-AA I removed the Ready for testing label because there's a couple more things I want to do on this.  Based on your feedback I lowered the limit to 5MB.  You asked for 3.5MB and I'll do that if I figure out how to change the "failed to upload" message to something better like "image is too large".

**Comment by passionInfinite** [comment]
@joshi1983 @Blandine-AA  5MB is fine and I have made checking of the file size and file type before sending it to the server. PR number #579  should fix this issue and it is ready for testing.

**Comment by joshi1983** [comment]
I merged and deployed Hardik's work to app.accesslocator.com.  It is probably best to hold of testing of this until #523 is totally complete, though.  Laveen is fixing a popup that appears when navigating away from the profile or uploading an image.

**Comment by passionInfinite** [comment]
@joshi1983 I guess this should be close now. We already have that popup issue let it be open and close this issue.

**Comment by joshi1983** [comment]
@passionInfinite the popup bug mentioned in #523 will slightly interfere with testing for this but it will be easier to test this as a single change.

This can be closed when someone other than you(Hardik) and I test it.  @M4ttoF or @singlaneha2205 do you want to test?

The procedure I suggest for testing would be:
1. Sign in.
1. Upload a file larger than 5MB in file size(not 5 mega pixels).
1. Check that a clear message says the file is too large.
1. Upload a file smaller than 5MB.
1. Check that the image uploaded without error messages or problems.

Note that like @passionInfinite was mentioning, there is another bug that causes a dialog like 
![image](https://user-images.githubusercontent.com/11838191/42336207-fdd5ecf2-8050-11e8-991d-40367922373c.png) to appear when it shouldn't.  If you see this, it doesn't mean that #261 isn't complete or failing the test.  The other issue, #523 should cover fixing this.

**Comment by singlaneha2205** [comment]
@joshi1983 I tested the above scenario and was able to get successful error message conveying "Photo should be smaller than 5MB" when I was trying to upload a photo of 5MB and then was able to successfully upload the photo less than 5MB size. Can refer to screenshot attached for your reference.
[Photo Upload.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/2168254/Photo.Upload.docx)

**Comment by joshi1983** [comment]
Thanks for testing it, @singlaneha2205 and updating the labels.  You can paste images in the comment section too.  That might be easier than making a separate docx file and attaching that.

I'm closing this issue since it successfully completed testing.
