### ISSUE TITLE
Search result page : Optimize colours and fonts for mobile devices

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#265]
Stephanos mentioned in feedback for #135 that the location links looked difficult to read on his mobile device.  "I tried to test it from my Mobile and I see another problem, that the results are not clearly visible. The font color is too light and difficult to read."

- [x] Use darker text colour when the results appear on narrow displays or mobile devices.
- [x] Increase font size slightly ideally for physically small screens.   Since it is difficult to detect the physical size of a screen, you might use the screen width instead.
- [x] Test that there remains a good hover effect on typical desktop screen resolutions to highlight the location about to be clicked
- [x] Create a pull request but don't merge it
- [x] Test on real mobile devices and get feedback from Stephanos to see if the problem still exists

**Comment by joshi1983** [comment]
@stephanosm I darkened the text colour and increased the font size by 5% for narrow screens.  Is the table view still difficult to read on your device?

I tested with:
- a Samsung CE0168 tablet using Android and a Chrome browser
- a BLU Advance 4.0 L Android phone with a Chrome browser

**Comment by stephanosm** [comment]
The text size is good, but the the color needs to be darkened more. The results remain unclear.

**Comment by joshi1983** [comment]
@stephanosm can you make a screenshot from your mobile device to show how it looks for you?

This is what the screen looks like to me:
![image](https://cloud.githubusercontent.com/assets/11838191/25047467/dd5eec78-2104-11e7-80ff-9bd09b2040cd.png)

**Comment by stephanosm** [comment]
Mine here. 
![screenshot_2017-04-14-11-45-32](https://cloud.githubusercontent.com/assets/22602396/25048200/24dcdc3c-2109-11e7-85c4-e183ebca4265.png)

**Comment by stephanosm** [comment]
It looks very clear on a PC but the actual on the mobile is not clear that much. I noticed yours is more bold

**Comment by joshi1983** [comment]
That screenshot is pretty helpful.  It looks like the font isn't loaded properly on your device.  Even the menu items and AccessLocator are far too thin on your phone.

Is that a Samsung Android phone?  What type and version of phone is it?  That information should help me reproduce the problem.

**Comment by stephanosm** [comment]
LG model G4

**Comment by joshi1983** [comment]
Blandine's tablet had a similar problem with the fonts.

I removed usage of a Google font called "Didact Gothic" and it should be using Arial now.

@stephanosm can you try again at [app.accesslocator.com](http://app.accesslocator.com) ?  Thoroughly refresh if you can in case the browser cache prevents you from seeing the updates.

**Comment by stephanosm** [comment]
I refresh but I still can't see any difference

**Comment by joshi1983** [comment]
Did you thoroughly refresh?  In Chrome on Windows, there's a CTRL+SHIFT+R for a thorough refresh which clears cache.  There's a different CTRL+R which does a reload without clearing cache.

To verify that the cache of the css file was cleared, please go to http://app.accesslocator.com/css/app.css and check that the @import url(https://fonts.googleapis.com/css?family=Raleway:300,400,600); line is removed.
demo shows:
![image](https://cloud.githubusercontent.com/assets/11838191/25229405/1348a0b6-259e-11e7-856d-76a2fbbc853a.png)
app should show:
![image](https://cloud.githubusercontent.com/assets/11838191/25229433/35eaf2fe-259e-11e7-8629-31aa905c8cf7.png)

Can you follow instructions here to make sure the cache is cleared?
http://www.tech-recipes.com/rx/5663/android-how-to-clear-browser-cache-history-form-data-andor-cookies/

Also, be sure to visit app.accesslocator.com and not demo.accesslocator.com since only app has these changes.

**Comment by stephanosm** [comment]
It has already been refreshed.

![screenshot_2017-04-20-18-01-18](https://cloud.githubusercontent.com/assets/22602396/25254473/bdc1a218-25f3-11e7-9738-ba0491a76d59.png)

**Comment by joshi1983** [comment]
I wasn't able to reproduce it on my devices but one of my coworkers could and it is fixed on his phone for now.  It looks like I mistakenly set the font to be the opposite of bold... super thin.

@stephanosm can you try now?

**Comment by stephanosm** [comment]
Looks good now !

**Comment by joshi1983** [comment]
I closed because it is fair to consider this passed by Stephanos' testing.
