### ISSUE TITLE
Add an FAQ to the app

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#266]
This issue is to track Kim's recommendation (see file) after her research on existing accessibility apps.
[Kim - AccessLocator.Recommendations.pdf](https://github.com/hhaccessibility/hhaccessibility.github.io/files/862677/Kim.-.AccessLocator.Recommendations.pdf)

**Comment by joshi1983** [comment]
I merged a pull request and deployed the new FAQ feature to http://app.accesslocator.com/faq for review.

Here is a screenshot.
![image](https://cloud.githubusercontent.com/assets/11838191/24326636/fbdd6c0a-1188-11e7-8709-a86342ce2819.png)

**Comment by joshi1983** [comment]
I removed the "Future release" because I implemented the change for this nearest release, demo 0.0.3.

**Comment by stephanosm** [comment]
there are a couple of corrections:
"gathers" appears twice
on the same line, should the "back with you" be "back to you"?

**Comment by joshi1983** [comment]
@stephanosm thanks for finding those mistakes.  I'll proofread next better next time.

I removed the erronious "gathers" and replaced "back with you" with "with everyone".
![image](https://cloud.githubusercontent.com/assets/11838191/24327733/e5de5c7a-11a6-11e7-8ae2-73b8d8f48216.png)

**Comment by joshi1983** [comment]
Since we have an FAQ feature, can we remove the "Our Vision"?  It seems like if we ever have something to call our vision, it can fit nicely as a question answer instead of needing a full page.  It also makes the application look needlessly incomplete to have "Under Development" under a menu item when we have and continue to have no plan for what to write in there.

**Comment by stephanosm** [comment]
agree

**Comment by joshi1983** [comment]
I removed the "our vision" menu item now.

**Comment by joshi1983** [comment]
@kimficara was this what you expected?  Do you have any edit requests for the question list or the answers?  Any tweaks to how it should look?

**Comment by kimficara** [comment]
The FAQ is exactly what I expected!  The questions so far are all great, I think we could definitely add a lot more and eventually group them into different sections.

WheelMap has a great FAQ list, I noticed our questions were taken from their first list section.  I went through the rest of their list and filtered out the questions that are not applicable to AccessLocator.  Here is the list of questions that I think we should eventually add to our FAQ:

•	Why can’t I find some places on wheelmap.org?
•	How do I rate a location?
•	Why should I upload photos of a place? What should the photos show?
•	How do I upload photos of a place?
•	How can I delete a location rating?
•	How do I register with AccessLocator?

Feel free to add any other questions that come to mind!

**Comment by kimficara** [comment]
PASS

(I will not close the issue in case anyone else would like to add more questions for the future)

**Comment by joshi1983** [comment]
The requested questions and answers have been added, @kimficara.  Do they still look good?  Thanks for the review.  That pushes the work forward quite nicely.

**Comment by kimficara** [comment]
looks great!

**Comment by joshi1983** [comment]
I'm closing because Kim and I are both happy with calling this issue complete.  This issue is linked to the demo 0.0.3 milestone which should help when we write release notes.
