### ISSUE TITLE
Photo upload : need to show when the photo is loading

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#267]
When uploading the photo, there is no information showing that the upload is in progress. You wonder if anything is happening except for the browser tab going round and round, but this could also mean that there is an internet problem.

So, we need a message or a temp hour glass or other icon in the photo space to show the user that upload is in progress.

**Comment by joshi1983** [comment]
I merged and deployed a fix for this.

Here is a screenshot of the upload photo progress indicator.
![image](https://cloud.githubusercontent.com/assets/11838191/24333409/8bd58c42-1225-11e7-8846-6971a90b14a2.png)

The test procedure I suggest for this is:
1. Go to [app.accesslocator.com](http://app.accesslocator.com) and sign in to see the profile.
1. Upload a photo and notice the indication that an upload is in progress.

**Comment by kimficara** [comment]
The indicator works in Chrome but not Safari.  In Safari, the old picture remains on the screen until the new one is loading.

**Comment by joshi1983** [comment]
Great find, @kimficara, thanks.  I'll try to reproduce that problem in Safari on Windows and go from there.

**Comment by joshi1983** [comment]
@kimficara can you check again?  

I found a a problem in Safari on Windows where the file chooser wasn't showing up at all.  I was able to fix that.

Did things get darker in the photo rectangle while it was uploading in Safari?  Even if the animated circles don't show, the darkening indicates something is happening which helps.  I had a problem where the circle animation wasn't showing in an old version of Safari on Windows.

**Comment by kimficara** [comment]
In safari the picture now gets darker and the circles are displayed however the animation is not working.  It looks much better with those two effects and even though the animation isn't working, the uploads I have been testing have been so quick that you wouldn't even get a chance to see the animation in action.

I tested it in Chrome again to make sure everything was working there and there were no issues.  

I'll leave it up to you to decide whether this is a pass, I would think so.

**Comment by Blandine-AA** [comment]
PASS. I will open a new issue to follow-up with the Safari functionality.

**Comment by joshi1983** [comment]
That new issue sounds good, @Blandine-AA.
