### ISSUE TITLE
Location Report: clicking generic google link doesn't show search results

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#268]
When we don't have an associated URL for a location stored, we link to Google search with the location's title as keywords.  We just don't do a perfect job of this.  The user still needs to click a button to see the results.

An example of this problem can be seen at:
http://app.accesslocator.com/location-report/564

Go to https://www.google.ca/?q=Doubletree+Guest+Suites+Fort-Shelby+Hotel+ and it won't show the results until you click Google's search button.

- [x] Find a way to show the search results immediately.  Ideally, this will be just by formatting a URL.
- [x] Make AccessLocator use your solution for every location that doesn't have a specific URL in the database.  This should involve adjusting the implementation of getExternalWebURL in hhaccessibility\hhaccessibility.github.io\app\app\Location.php

**Comment by joshi1983** [comment]
@gillbalraj did you get anywhere with finding a link to google that shows the search results?

**Comment by joshi1983** [comment]
This is progressing quite slowly so I looked into it more.

Adding the /search does what we're after.
http://www.google.com/search?q=Google+tutorial+create+link

This was mentioned at:
http://stackoverflow.com/questions/36205013/is-it-possible-to-link-directly-to-google-search-results-using-href

This concludes the subtask 1.  @gillbalraj let me know when you're ready to implement the change so you can learn more about how to update the project and submit changes.

**Comment by joshi1983** [comment]
@gillbalraj will you get this done by April 20?  I'd like it to be working on app.accesslocator.com before the Digifest event in case people there use app.accesslocator.com and find this bug.  If you can't, let me know and I can take over.

**Comment by joshi1983** [comment]
@gillbalraj if you don't get this done by Friday, April 21, I'd like to take over and do the last subtask on Saturday or Sunday so that it is ready for the Digifest event.

**Comment by joshi1983** [comment]
I finished the last task on this and the linking feature is now available at [app.accesslocator.com](http://app.accesslocator.com).

For anyone testing this, here is a procedure I suggest:
1. Go to a location that has no preconfigured website address such as [Dieppe Gardens](http://app.accesslocator.com/location-report/347).
1. Click the Google link to search for that location on Google.
1. Notice that the search results appear immediately.  Prior to this issue's work, the results would not appear immediately.

**Comment by stephanosm** [comment]
passed!

**Comment by joshi1983** [comment]
Thanks for testing @stephanosm
