### ISSUE TITLE
CSS Validation finds invalid characters in app.css

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#269]
CSS validation is finding problems in our generated CSS.  app.css is generated using gulp off of hhaccessibility.github.io\app\resources\assets\sass\app.scss.

Over 3000 lines of it is from the third party bootstrap SASS and this is the part that is generating errors.
```

// Bootstrap
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
```

Find out why Bootstrap is translated to invalid CSS and if we can do anything about it.

Use the following validator to fix the problems and test that it works:
https://jigsaw.w3.org/css-validator/#validate_by_input
Since you won't be able to update app.accesslocator.com as you work on this, use the direct input feature of the validator to copy and paste content from css/app.css of your local site.

Here is a screenshot showing a few of the problems at the time of writing this issue:
![image](https://user-images.githubusercontent.com/11838191/33917745-ee040a08-df7d-11e7-9d29-aa0f7bcfa27a.png)

**Comment by joshi1983** [comment]
This may be helpful for the problem:
https://stackoverflow.com/questions/32496807/error-invalid-utf-8-when-compiling-sass-with-import/32496978

**Comment by joshi1983** [comment]
Mi Sook's fixes were merged but they focus on the non-bootstrap-related validation problems.  There are still some problems caused by including Bootstrap from app.scss.

**Comment by joshi1983** [comment]
@passionInfinite do you want to tackle this?

**Comment by passionInfinite** [comment]
@joshi1983  This is already resolved you just have to update your node-sass dependency and it will work. Check it out on your local machine and update me if it doesn't work. I will show you some way to do it.

**Comment by passionInfinite** [comment]
Check PR #580

**Comment by joshi1983** [comment]
Yes, you're right about it nearly being resolved.  Your pull request fixes the last little problem.

**Comment by joshi1983** [comment]
Since this issue can only be tested by using special tools and an awareness of CSS but our testing is usually done by less technical people, I'm going to skip asking for someone else to test this and just close this.

The validation can be run on app.accesslocator.com from: https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fapp.accesslocator.com%2Fcss%2Fapp.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en
