### ISSUE TITLE
Photo upload : add feature to delete uploaded photo

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#276]
After a user uploads a photo on the profile, (s)he may want to remove it.

This issue breaks down into the following subtasks:
- [x] Add a method to hhaccessibility.github.io\app\app\Http\Controllers\ProfilePhotoUploadController.php for deleting the corresponding image file.  Add a route to it in hhaccessibility.github.io\app\routes\web.php.
- [x] Make appropriate HTML or JavaScript changes to hit the new delete method.  This will probably involve adjusting hhaccessibility.github.io\app\resources\views\pages\profile\profile.blade.php and hhaccessibility.github.io\app\public\js\profile.js.

**Comment by joshi1983** [comment]
@areebakamal where do you suggest putting the delete option?  Didn't you want an X link or button somewhere?

**Comment by areebakamal** [comment]
Maybe something like this:

![6e64a4f961e27a821feb8071da9fe0a4_female-user-icon-clip-art-clipart-user-icon_300-300 copy](https://cloud.githubusercontent.com/assets/23005093/24683156/69b8e134-196b-11e7-86b8-a13a50e24bc0.jpg)
![6e64a4f961e27a821feb8071da9fe0a4_female-user-icon-clip-art-clipart-user-icon_300-300](https://cloud.githubusercontent.com/assets/23005093/24683157/69bfffaa-196b-11e7-8f48-59e3d69ed712.png)

**Comment by Blandine-AA** [comment]
@areebakamal , are you working on this? If yes, please assign it yourself and change the label to "Working on it".

**Comment by joshi1983** [comment]
@areebakamal you don't want the "Change Photo" text anymore?

What do you think of having a "Change Photo" at the bottom and add a "Remove Photo |X|" at the top?

**Comment by areebakamal** [comment]
@joshi1983 yeah that sounds good!

**Comment by joshi1983** [comment]
Like @Blandine-AA asked, did you want to take this on or do you feel busy with exams or some other AccessLocator work to focus on this yet, @areebakamal ?

**Comment by areebakamal** [comment]
I will work on the other 2 issues (background photo & search page UX) and
also have exams starting on the 10th till the19th. You can assign this one
to someone else.

**Comment by joshi1983** [comment]
@amoldhillon can you work on this?  As usual, let me know if you have questions.  You can email me, comment here, wherever you prefer.

**Comment by amoldhillon** [comment]
Thank you Josh. I will do my best in this and if i have any problem i will
mail you.

**Comment by joshi1983** [comment]
@amoldhillon how's this coming?  I didn't see any messages from you and your last week of the VIP extension is next week.

Are you coming to the meeting tomorrow?

**Comment by amoldhillon** [comment]
@joshi1983 hello Josh. I am not sure if I am coming tomorrow or not. But I am working on this issue right now. Just getting familiar with PHP and HTML. It is taking much more time than I expected. But I'll definitely come up with the solution by this Monday or Tuesday. If I encounter any problem in this I'll drop you  mail. Thank you.

**Comment by joshi1983** [comment]
Thanks for replying to the question.

There isn't enough time to get really confident with PHP and HTML so you'll have to approach this differently.

Here are some small steps that should get you started.

Here is the HTML that you'll need to modify:
``
			<div class="photo-display" onclick="selectImageFile()">
				<div class="uploaded-photo">
				</div>
				<div class="progress-element"></div>
                <p>Change Photo</p>
			</div>
``
You could start by just changing the "Change Photo" caption to show some random characters and reloading the profile to see the change in your web browser.  

Play around with that until you can add an 'x' button above the uploaded photo element.  You won't need to know any PHP to add the x button.  You may need to get the basics with what HTML tags are but I'm pretty sure you already know that.

It won't work from these changes alone but those changes will get you away from merely reading to start actually writing the fix for this issue.

**Comment by amoldhillon** [comment]
After adding the 'x' button using html, how can I proceed further? I think it is with amending java script file? Which part of it?
Thanks

**Comment by joshi1983** [comment]
Make a pull request with just the x button added and no functionality behind it.  I'll review and give feedback on that.  Do that before working on the JavaScript.

Various steps using git are documented at:
https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/git-commands

Specifically for you, this sequence of instructions and commands will get you to push up your work:
Open a terminal/console.
change directory to hhaccessibility.github.io\app
git branch issue-276
git checkout issue-276
git add resources/resources/views/pages/profile/profile.blade.php
git commit –m “profile: added x button to photo upload feature”
git push origin issue-276 –f



After you make a pull request, you can work on the first subtask which is to make the delete photo function available on the server.  You'll need to do this before doing subtask 2, the JavaScript changes because the JavaScript will need to talk with the server to complete the job.

**Comment by amoldhillon** [comment]
I just finished this. How to start with first subtask?

**Comment by joshi1983** [comment]
Yeah start making that controller.  Thanks for the pull request.  I'll review it tonight.  I'll test it and might merge with tweaks.

**Comment by joshi1983** [comment]
@amoldhillon the pull request was merged with tweaks to make it look more like the "Change Photo" text at the bottom.  Your work was linked to the @rickyboparai user.  I'm happy you're working together but I also want the pull requests linked to the assigned user so when you push up, try to use the amoldhillon credentials.  If you didn't type in email and password, did you share ssh key files with each other?

This should help you finish the last 2 subtasks together:
Also, for the remaining tasks, you could cover both by turning the new Remove Photo element into an anchor, "a" tag with its href pointing to your new delete route and controller method.  Have the controller return a redirect to '/profile'.
- [ ] Start by having it just run your method and redirect to the profile without deleting anything.  Test that clicking the link looks like it just reloads the profile.
- [ ] Add some code to your controller method that calculates the path.   It should basically do unlink(ProfilePhotoUploadController::getProfilePhotoPath());
- [ ] Test the feature deletes the photo and resize the browser to check that the feature looks good in mobile devices.
- [ ] Make a pull request.

@areebakamal it is implemented to look pretty different from your mockup but it seemed weird to me to have the remove look so different from the Change Photo.  What do you think of having both links share a common dark bluish background and white text like your mockup for "Remove Photo |X|"?

Here's how it looks on app.accesslocator.com:
![image](https://cloud.githubusercontent.com/assets/11838191/25432573/ed171d6e-2a52-11e7-88d7-42a0e04adebd.png)

**Comment by Blandine-AA** [comment]
Graphic chart/feel should remain consistent for change and remove photo actions

**Comment by amoldhillon** [comment]
I made a controller but need helps in routing. Can you help me with the syntax in the ()?
Route::get();
Route::post();

**Comment by amoldhillon** [comment]
And in "a" tag href, i will put something like "ProfilePhotoUploadController.php" or concerned class or function?

**Comment by joshi1983** [comment]
Use get because that'll work well with the 'a' tag.

You could write something like this:
Route::get('profile-photo-delete', 'ProfilePhotoUploadController@delete');

The href for your 'a' element would need to match the route you specify.  If you wrote the above line in web.php, href="/profile-photo-delete" is what you'd put in the profile.blade.php file.

Did you get latest changes yet?  I changed your button into a "p" element before merging it and want you to modify from that point onward to avoid change conflicts.

**Comment by joshi1983** [comment]
@amoldhillon had trouble making the pull request but he emailed the files he updated and I made the pull request on his behalf.

This should be ready for testing now.  @areebakamal are you up for it when you come back from Digifest?  Aside from your testing, I'm also curious if you'd want the labels to look more similar to your mockups.

**Comment by areebakamal** [comment]
> @areebakamal it is implemented to look pretty different from your mockup but it seemed weird to me to have the remove look so different from the Change Photo. What do you think of having both links share a common dark bluish background and white text like your mockup for "Remove Photo |X|"?

Yeah I think it's a good idea. The colors though should be shades of gray..light gray background with dark gray text. The background should extend to match the width of the photo and the entire button can be clickable. Kind of like this:
![image](https://cloud.githubusercontent.com/assets/23005093/26044228/1427e5ce-3911-11e7-8568-3478e8b099d5.png)

The remove functionality works fine on the desktop and Samsung Note mobile device.

An uploading bug: the photos that are in portrait mode are uploading at -90 degrees rotated. I also tested on the phone and the same problem persists. Landscape photos upload correctly.

**Comment by joshi1983** [comment]
The light gray background was added as Areeba suggested.

It now looks like this:
![image](https://cloud.githubusercontent.com/assets/11838191/26286849/8ccacd4a-3e3c-11e7-9fd8-68ee08fc6301.png)

The text is grayish but with a little extra blue.

**Comment by joshi1983** [comment]
@areebakamal you commented on the orientation of the images.
> An uploading bug: the photos that are in portrait mode are uploading at -90 degrees rotated. I also tested on the phone and the same problem persists. Only photos in landscape view upload correctly.

Can you attach a photo that gets rotated like you're saying?  I'd like to reproduce the problem.

**Comment by Blandine-AA** [comment]
@kimficara , will you have time to test this by Saturday? If yes, please assign it to you and remove @areebakamal. Thanks!

**Comment by areebakamal** [comment]
@Blandine-AA I can test it now.

**Comment by Blandine-AA** [comment]
@areebakamal, Ok Then! I'll assign another issue to @kimficara !

**Comment by areebakamal** [comment]
@joshi1983 The 'Remove' and 'Change Photo' buttons work great. I still cannot upload a photo that is taken in portrait mode. The dimensions of the portrait view sample image used for testing (didn't work):
![image](https://user-images.githubusercontent.com/23005093/26946278-ba4ea3bc-4c5c-11e7-8751-2ade65555f12.png)
The dimension for the landscape view photo used (worked):
![image](https://user-images.githubusercontent.com/23005093/26946335-e1edff30-4c5c-11e7-9f09-e38849a6f816.png)

**Comment by areebakamal** [comment]
PASS for photo deletion.

**Comment by joshi1983** [comment]
@areebakamal can you attach the photo file to a comment here?  

That would help me either reproduce the problem or discover that you're comparing with a much more sophisticated upload feature that analyses the photo's contents to guess the intended orientation.

**Comment by areebakamal** [comment]
![img_3835](https://user-images.githubusercontent.com/23005093/26963690-f01448d0-4cbb-11e7-85c2-78264781b7b7.JPG)
![screenshotx](https://user-images.githubusercontent.com/23005093/26963873-d00e2ece-4cbc-11e7-9649-3e39a028b12f.jpg)

**Comment by joshi1983** [comment]
I uploaded using Chrome and it came to the expected orientation.  Are you able to upload the files that you shared here in another browser and see it upload to the wrong orientation?

Here's some screenshots of what I see after uploading.
![image](https://user-images.githubusercontent.com/11838191/26970422-5b3d7b48-4cd7-11e7-9cb7-a66e0e1ffc2d.png)

![image](https://user-images.githubusercontent.com/11838191/26970465-84cdec18-4cd7-11e7-92f2-d4aed9b5bd21.png)

**Comment by joshi1983** [comment]
Blandine, Areeba said the photo deletion passed here so I'm tempted to make a new issue for this orientation stuff and close #276.

**Comment by Blandine-AA** [comment]
Pass for original intended functionality.
