### ISSUE TITLE
Location search: add keywords to location tag search filtering

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#289]
On the home page, if someone were to type a keyword like "comfort" and hit "Accommodation", it was only filtering the "Accommodation" part of the intended search.  We want the keywords to also be used to filter results.

In the end the following scenario should test that this feature is working:
1. Go to the home page at [app.accesslocator.com](http://app.accesslocator.com)
1. Type 'Windsor, Ontario' for the search location.
1. Type 'comfort' in the keywords field.
1. Click 'Accommodation'.
1. You should see locations that contain 'comfort' such as 'Comfort Suites'.  You should not see names like 'Best Western Plus' because that doesn't contain the word 'comfort'.

**Comment by kimficara** [comment]
Has this feature been implemented yet @joshi1983?  I tried testing it out and it didn't seem to be working

**Comment by joshi1983** [comment]
Yes, it has been implemented and ready for testing.  It is funny to call something this trivial a feature but yeah the spelling was fixed as far as I can see on app.accesslocator.com.

**Comment by kimficara** [comment]
@joshi1983 It doesn't seem to be working for me, it's doing what it used to do and displays all locations from that category regardless of what my search word it..

**Comment by joshi1983** [comment]
Can you thoroughly refresh the page or empty your web browser cache?  In Windows, I use CTRL+SHIFT+R to thoroughly refresh.  If everything is refreshed properly, the link should include the keywords.  I made the following screenshot with Chrome and it shows the link's URL when I hover over a link:

![image](https://cloud.githubusercontent.com/assets/11838191/25000984/5eed4022-2011-11e7-9970-320007efbbde.png)

**Comment by kimficara** [comment]
It worked after I cleared my cache, thanks for the advice!

I tested many different combinations of searches and they all worked for me.  

PASS

**Comment by kimficara** [comment]
closing this issue since it passed its testing
