### ISSUE TITLE
Get reliable website hosting

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#29]
Before much of the website can be constructed, we need a web hosting service to publish the web application.  This could be paid hosting from a company like GoDaddy or hosting from the University of Windsor.

**Comment by Blandine-AA** [comment]
Dr Stephanos is looking at which one is the best: University or his personal server. Will keep you posted once decision is made.

**Comment by joshi1983** [comment]
Blandine and I are working on this.  We hope to get a host before Monday.

**Comment by joshi1983** [comment]
I emailed a recommendation to use Digital Ocean.

**Comment by Blandine-AA** [comment]
Looks like Monday will be the earliest. Haven't received any answer yet from Dana.

**Comment by joshi1983** [comment]
Could you call them Monday afternoon if there's no reply by 12 noon?

**Comment by joshi1983** [comment]
Jerome Hachey from JMCC registered accesslocator.com and .accesslocator.org using Godaddy this morning.  I didn't check if any other similar domain names were registered yet.  

I'll call Jerome tomorrow to guide through the process of getting hosting service from Digital Ocean.  

The domain registration details are shown at:
http://whois.domaintools.com/accesslocator.org
http://whois.domaintools.com/accesslocator.com

**Comment by joshi1983** [comment]
Jerome and I discussed this morning.  I have an account to access the digital ocean account as a "Team" member and access the godaddy account through delegation.  I'll investigate them in more detail over the coming few days with the goal of getting accesslocator.com pointed at our new host so everyone can see something related to us when going to accesslocator.com.

**Comment by joshi1983** [comment]
accesslocator.com hosts our web application now.  I'm calling this a success and closing the issue.
