### ISSUE TITLE
Home page: fix misspelling of 'Accomodation' to be 'Accommodation'

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#290]

**Comment by joshi1983** [comment]
The test procedure for this is very simple.
1. Go to the home page at [app.accesslocator.com](http://app.accesslocator.com)
1. Check the spelling of the Accommodation link to see that the 'm' was added.  You could also double check that it is the correct spelling.

**Comment by kimficara** [comment]
"Accommodation" is fixed and I looked through the whole website to check for any other typos and I think we're all clear, well done @joshi1983!

**Comment by kimficara** [comment]
Closing the issue since it passed its testing.
