### ISSUE TITLE
Home page: increase height, add zoom buttons, and remove streetview

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#297]
During a meeting around 3pm on Friday, April 16, 2017, Meagan and Blandine mentioned that it would be an improvement to add zoom buttons to the home page's map and increase its size slightly.

These changes would include:
- [x] Increase map height
- [x] Add zoom buttons
- [x] Remove streetview options from maps on location search, location report
![image](https://cloud.githubusercontent.com/assets/11838191/25071364/c6802a9c-2282-11e7-8653-8b7a61d667c4.png)

To test this, you'll need to visit all 3 types of pages.
1. Go to app.accesslocator.com and see that the map 210 pixels instead of its old height of 150 pixels.
1. Hit one of the search options like the 'Accommodation' link and see that the draggable man for streetview is not showing on location results.
1. Click one of the resulting locations to see the location report.  The draggable streetview character should be removed from there too.

**Comment by joshi1983** [comment]
@kimficara can you test this too?

**Comment by kimficara** [comment]
The increased height makes a big difference (in a good way).  All three changes look great and I didn't find any issues while testing them out.

PASS

**Comment by kimficara** [comment]
@joshi1983 I wasn't sure if I should close this issue since it has the enhancement tag.

**Comment by joshi1983** [comment]
Closing the issue seems fine to me.  I'll ask Blandine later if she wants to manage the demo 0.0.3 release.

**Comment by Blandine-AA** [comment]
@joshi1983 , Why wouldn't I want to manage release 0.0.3? As I mentioned in a previous meeting, 0.0.3 will be postponed to a later date. I'll look into this next week.
