### ISSUE TITLE
Menu: Indicate active menu items

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#299]
Many websites mark navigation menu items differently when you visit the corresponding pages.  We want the same feature in AccessLocator.

Here are a couple examples of the indicator in action.  It includes a soft border and black text.
![image](https://cloud.githubusercontent.com/assets/11838191/25178242/0280185c-24d3-11e7-8f28-ef26075664d8.png)

![image](https://cloud.githubusercontent.com/assets/11838191/25178262/1d87f818-24d3-11e7-98f8-5972f50353cd.png)

**Comment by joshi1983** [comment]
@kimficara are you available to test this?

**Comment by kimficara** [comment]
Looks great! 

PASS
