### ISSUE TITLE
Create a rough UX design sketch

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#30]
Blandine and Dr. Stephanos Mavromoustakos will be drawing a rough UX design sketch.

**Comment by joshi1983** [comment]
Areeba(areebakamal) should probably get assigned to this when she becomes available in the Assignees list.

**Comment by areebakamal** [comment]
![wireframeflowoption1](https://cloud.githubusercontent.com/assets/23005093/19815598/a114969a-9d11-11e6-842c-564fa53d82eb.jpg)

**Comment by areebakamal** [comment]
![option2forrating](https://cloud.githubusercontent.com/assets/23005093/19815960/44a33c20-9d13-11e6-8af5-1324ca3d79ef.jpg)

**Comment by areebakamal** [comment]
![threeoptionsforrating](https://cloud.githubusercontent.com/assets/23005093/19816029/957fea9e-9d13-11e6-89ea-93181ecd62ea.jpg)

**Comment by areebakamal** [comment]
![option3ratingsthumbsupthumbsdown](https://cloud.githubusercontent.com/assets/23005093/19816372/fe80f99c-9d14-11e6-9854-37e3d2ebd926.jpg)

**Comment by joshi1983** [comment]
Here are some UX sketches I'm copying on behalf of Rumana.

Rumana wrote: "These are the pages that will appear to the user . The first image has a list of all the areas that he can rate, like parking. Each area has a rate button beside it,. Clicking on that button takes the user to image 2, where he has various factors that he can rate i.e lighting and so on. He has 4 options ( Y-Yes , N-No , NA-NotAnswered , N/A-Not Applicable) where yes is a postive response, no is a negative one, Not answered is when he cannot decide between Yes/No and not applicable is when he thinks that that particular factor doesn't influence his rating."

![image](https://cloud.githubusercontent.com/assets/11838191/20239701/78f3dbac-a8d4-11e6-9ed3-72981c301de2.png)

![image](https://cloud.githubusercontent.com/assets/11838191/20239706/b06b5484-a8d4-11e6-9a66-65d93a51f21d.png)

**Comment by areebakamal** [comment]
[Attempt1Ratingsss.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/587387/Attempt1Ratingsss.zip)

**Comment by areebakamal** [comment]
image
image
image
image
image

**Comment by areebakamal** [comment]
![7ratebuildingdecv3](https://cloud.githubusercontent.com/assets/23005093/21532864/c2852d4e-cd22-11e6-9d97-98b90b465731.jpg)
![7ratebuildingparkingviewww](https://cloud.githubusercontent.com/assets/23005093/21532865/c28a752e-cd22-11e6-95a8-fa92a3999492.jpg)
![7ratebuildingplaceoffering](https://cloud.githubusercontent.com/assets/23005093/21532866/c28d7c88-cd22-11e6-813c-4d434b059e2b.jpg)
![7ratebuildingplaceoffering2](https://cloud.githubusercontent.com/assets/23005093/21532867/c2945e72-cd22-11e6-9790-018102064f05.jpg)
![7ratebuildinguploadimages](https://cloud.githubusercontent.com/assets/23005093/21532868/c29761c6-cd22-11e6-9de2-702c424a88ee.jpg)
![7ratebuildinguploadimagesviewww](https://cloud.githubusercontent.com/assets/23005093/21532869/c29a1074-cd22-11e6-84d5-6489be58c216.jpg)
![mapssss3](https://cloud.githubusercontent.com/assets/23005093/21532983/072ad790-cd24-11e6-9408-66bcc72819a7.jpg)

**Comment by Blandine-AA** [comment]
Thanks Areeba for the latest updates.

Just few quick comment, 
1. We should be consistent in the wordings we use. Use "Location" instead of "Place" for example.
2. Use "Rate" only. We don't need to be specific. It it is a park, we are not going to say "Rate Park". Everything is a location. so, we want to stay simple.

**Comment by areebakamal** [comment]
Yeah I couldn't decide which one to use, Location Offerings or Place Offerings. Location offerings could also mean actual locality advantages. In Google Maps, the place holder for search is called "Place' where you type in the place you want to search. So that's where Place Offerings comes from. 
I'll change it to one or the other to be consistent.

**Comment by areebakamal** [comment]
Here's the updated design for maps: 

![criteriapage about building](https://cloud.githubusercontent.com/assets/23005093/21584877/707dda56-d082-11e6-8625-40d5166f24b2.jpg)

**Comment by areebakamal** [comment]
![criteriapage about building](https://cloud.githubusercontent.com/assets/23005093/21584888/ec6d6b68-d082-11e6-84b1-ce087dc034b9.jpg)

**Comment by joshi1983** [comment]
I'm closing because this issue doesn't describe work that we want to complete.  Even when it is closed, people can refer back to it, continue to comment...  It will just be clearer to anyone looking for work that this issue is the wrong place to check.
