### ISSUE TITLE
Finalize the accessibility checklist

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#31]
Since the Hacking Health event, we've learned more about the information we want to maintain on each building but haven't created a revised list of questions.  Create a revised list of questions that will remain quite solid until November's demo.  

This list will be difficult to change after data importers get adjusted to automatically fill them out for locations.

**Comment by Blandine-AA** [comment]
Checklist needs to be refined some more by the JMCC team.  Attached is the current criteria checklist and the profiles.
[combined profile and criteria checklist.pdf](https://github.com/hhaccessibility/hhaccessibility.github.io/files/553170/combined.profile.and.criteria.checklist.pdf)

**Comment by joshi1983** [comment]
When you use the word "Location", you mean the same as "building", right, Blandine?

**Comment by joshi1983** [comment]
I asked this in an email but I think the question fits to this issue too.

How should the needs of the user affect the accessibility calculation on buildings?  It seems like if the user didn't require a specific feature like a ramp, it shouldn't hurt the rating of a building as much as a required feature that the building doesn't have.  We could give required features triple weight in the calculation.  What do you think?

**Comment by Blandine-AA** [comment]
Hi Josh,

Great question and we discussed that yesterday and figured that if a criteria is not in the user profile, the values related to that criteria should not be used in the calculation for his specific view. Then, there is no point to give extra weight to some features. That way, things are kept simple.

So, not only the view of the criteria is personalized based on the profile, but also the review.

Hope this answers your question.

**Comment by Blandine-AA** [comment]
Yes, "Location" in the requirement document means building.

**Comment by joshi1983** [comment]
Blandine, from our last meeting, it seems like "location" is actually a broader term since it includes parks that may have no building in them.  It seems like we should rename "building" to "location" in both UI and internally to prevent confusion.  Does that sound good with you?

**Comment by stephanosm** [comment]
Josh you are right. Location is the broader term and it should be used instead of building. Location can cover anything, e.g. building, park, event place, etc

**Comment by joshi1983** [comment]
I renamed "building" to "location" throughout the database and various source files so it is consistently "location" from now on.

**Comment by Blandine-AA** [comment]
Meeting next week Dec 14th, for demo and to discuss the requirements questions in this thread.

**Comment by joshi1983** [comment]
@Blandine-AA the checklist was finalized already right?  I'm confident enough that I'm closing this issue.

**Comment by joshi1983** [comment]
Is the question categories sorted by chronological order of how you'd experience them? I can see people parking, then entering, then seeing open public areas, then maybe using an elevator...

Is this why JMCC and @Blandine-AA listed them in that order?
