### ISSUE TITLE
Presentation page: update for demo 0.0.3

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#313]
Update the AccessLocator.com presentation page

- [x] Deploy demo version 0.0.3 - @joshi1983 
- [x] Update release version - @joshi1983 
- [x] Add release note to New Features page - @areebakamal 

 List of closed issues in [release 0.0.3](https://github.com/hhaccessibility/hhaccessibility.github.io/milestone/11)

**Comment by joshi1983** [comment]
I should have the 2 subtasks complete late tonight.  I can probably give my suggestion for release notes text around then too.

If anyone wants to take over what to write for release notes, the issues closed under the demo 0.0.3 are pretty much the changes to note.

**Comment by Blandine-AA** [comment]
Release notes (0.0.3) - @areebakamal 
Added an FAQ menu
Improved Category selection UX design
Added State/Province/Territory selection in user profile
Enhanced photo upload functionality - Show animation when photo is uploading
Added functionality to use search point and distance to filter all search results

@joshi1983 , please check above list if you are happy with it. I didn't put all the issues.. Just the visible ones.

**Comment by joshi1983** [comment]
1. good.
1. sounds good if you mean #289.  
1. I'd word it more like "Added typeahead for State/Province/Territory in user profile".  The region input was there before.  The only difference was popping up options that match the selected country.
1. good.
1. The point and radius was supported in demo 0.0.2.  You could say "Added zoom buttons to search location selector".  Another point could be "Fixed bugs with map zoom for location search and location report".

**Comment by Blandine-AA** [comment]
Final release notes (0.0.3) 
1. Added an FAQ menu
2. Improved Category selection UX design
3. Added type ahead functionality for State/Province/Territory in user profile
4. Enhanced photo upload functionality - Show animation when photo is uploading
5. Added zoom buttons to search location selector
6. Fixed bugs with map zoom for location search and location report

@areebakamal, thanks for updating AccessLocator.com web page

**Comment by joshi1983** [comment]
0.0.3 is on [demo.accesslocator.com](http://demo.accesslocator.com) now.  @Blandine-AA was there some testing you wanted to do?

**Comment by Blandine-AA** [comment]
Quick test of demo 0.0.3 and it is ok as is.

**Comment by Blandine-AA** [comment]
@joshi1983 : It looks like Areeba has uninstalled her local AL server setup and won't bee able to make the changes on the AL présentation page. Since she is travelling this morning, can you take over and update the New Features page with the 0.0.3 release notes?

**Comment by joshi1983** [comment]
@Blandine-AA yes but it might take me until Thursday night to do since I'm having Internet trouble at home.

**Comment by joshi1983** [comment]
I'll try to fix this responsiveness problem on the presentation site too:
![image](https://cloud.githubusercontent.com/assets/11838191/25446875/f44b37ea-2a80-11e7-9312-7fd1a0a06819.png)

**Comment by joshi1983** [comment]
Presentation site now has the new release notes.

![image](https://cloud.githubusercontent.com/assets/11838191/25509579/0215cdd8-2b88-11e7-8d59-f1edd595bc94.png)

The responsiveness problem mentioned was fixed to look like:
![image](https://cloud.githubusercontent.com/assets/11838191/25509602/2aab4246-2b88-11e7-8669-f2778673d450.png)

**Comment by Blandine-AA** [comment]
Good @joshi1983 , but we need to be consistent with the release notes titles. Keep the same title format as for 0.0.2.

For the photo, I think the border is too thick. Need to have somebody else view on this before making any change. @areebakamal and @meaganvpark could provide some feedback.

**Comment by joshi1983** [comment]
I'll update when we're more confident in how to change it.

To help discussion about this, here are a couple reasons for the 2 main differences I see in the titles:
- The reason for the underlining difference is to clarify that one is a link and the other is not.
- The reason for the "New" being removed from the 0.0.2 is just because it isn't very new anymore.  We could remove the word "New" from both titles if you like.  That would be more consistent.

**Comment by Blandine-AA** [comment]
I understand and it is good to have a direct link on the demo app for the latest release. But then shouldn't that be a blue underline as the standard way of showing links?

We could remove "New" altogether if it is confusing, but it is not because a feature is not new anymore in the new release that we need to change the history of the app. Those features are still new in 0.0.2. 

Thinking some more about it, how about "Version x.y.z update"? The tab already says "New Feature", and not all the updates are "Features".

**Comment by joshi1983** [comment]
"Version x.y.z updates" sounds good to me too.  If that makes you confident, I'll do it.

Regarding the underlining, I found this information from a user-experience website, https://www.nngroup.com/articles/guidelines-for-visualizing-links/:
- To maximize the perceived affordance of clickability, color and underline the link text. Users shouldn’t have to guess or scrub the page to find out where they can click.
- Assuming the link text is colored, it’s not always absolutely necessary to underline it.
    - There are two main cases in which you can safely eliminate underlines: navigation menus and other lists of links. However, this is true only when the page design clearly indicates the area’s function. (Remember: your design might not be as obvious to outside users as it is to your own team members.) Users typically understand a left-hand navigation rail with a list of links on a colored background, assuming it resembles the navigation areas on most other sites.
    - Exception: underlining is essential if you use link colors such as reds or greens, which cause problems for users with common forms of color-blindness.
    - Exception:  underlined links are important for low-vision users’ accessibility, so retain underlines if accessibility is a priority for your site or you have many users with low vision.

We could colour them too but for colour alone to work for colour-blind users, we'd need to change the brightness of the colour.  For example, a lighter blue for links.  The underlining would be sufficient regardless of colour blindness in my opinion.  If we change both underlining and colour, we'd definitely clarify that the title is clickable better than by merely underlining but the more difference, the less consistency we'd have.  What I did with the underlining alone was an attempt to compromise between those two goals(consistency and indicating clickability).

**Comment by joshi1983** [comment]
As mentioned in notes from https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/Development-Meeting-Notes-Friday,-May-12,-2017:

> We mentioned possibly replacing the AccessLocator team image on http://accesslocator.com/ to have the Digifest photo or something more recent because a lot of the team members from the 2016 Hacking Health event were no longer involved with the project

What do you think of this, @Blandine-AA?

**Comment by stephanosm** [comment]
I think it is better to have both. I am not sure how though. Either on home page or as a separate page under history/about. It is a good way to show the progress. Also, in the future we may have more events to add.

**Comment by Blandine-AA** [comment]
I suggest to add a "News" tab were we will have a blurb with a link to the related event and article a bout AccessLocator

**Comment by stephanosm** [comment]
We may also use Bootstrap (or something similar) to redesign the page with some modern theme add whatever is needed

**Comment by Blandine-AA** [comment]
I forgot to answer the question from the meeting minutes.

Neither of the picture reflects the current state of the team, but the HH picture represents the genesis of the project and better conveys the group of people involved in the project . so, it should remains the main picture for now.  

Regarding the redesign of the presentation page, I think it is not a priority for now and we don't have  resources for it less than 6 months after launching it. Eventually, we could have a team menu where we have team members info and a blurb about their responsibility on the project. This can be a student work!

@stephanosm , was it a feedback from Digifest that the presentation page wasn't "modern"?

**Comment by stephanosm** [comment]
no feedback about the homepage for not being modern. I just think it is perhaps time to redesign the page especially with some ready-made theme that takes less than a day to do so. A student can do this work.

**Comment by joshi1983** [comment]
If we decided to redesign the presentation site, mockups for a redesign optimized for the various screen widths from desktop, tablet, and mobile phones would be the first steps.  For now, we have a presentation site carefully optimized for various screen widths and it would be a step backwards to lose those optimizations.

I don't see the need for a redesign either.  It isn't like we have visitors hitting the presentation site often enough to be bored with how it looks.  The required work won't be just in creating new mockup images and reimplementing all the HTML but also the review and discussion with Blandine, Stephanos, Areeba, and me.  The skills and time redesigning and reimplementing the presentation site could be used to tackle issues on the main application.

**Comment by Blandine-AA** [comment]
I agree with @joshi1983 comments. There is no need to redesign the web page now!  If we start having crazy traffic on it, we might consider. Even them, it will be weighted against the app priorities. So,  I would rather put resources, even student ones, on the main app.

**Comment by Blandine-AA** [comment]
PASS
Opened #348 to track the launch of the demo from the "New Feature" tab, in a new window.
