### ISSUE TITLE
Rating: round up overall accessibility value

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#316]
In the table view of search results page, show the rounded value to "integer" of the accessibility rating. This should also apply where ever we display the overall rating value
![image](https://cloud.githubusercontent.com/assets/20052162/25433993/923575d4-2a58-11e7-965d-5bd48b46848d.png)

**Comment by joshi1983** [comment]
This is ready for testing on [app.accesslocator.com](http://app.accesslocator.com).  Did you want to check, @Blandine-AA ?  The only places I could think of that show the overall rating were the table view in your screenshot and the report on an individual location.  The report on an individual location was rounded to the nearest decimal point before but now rounded to nearest integer.

**Comment by Blandine-AA** [comment]
@joshi1983 Looks good to me.
When implementing the rating feature, we will have to remember this.
No need to move this fix to 0.0.3. Leave it for 0.0.4 release !
