### ISSUE TITLE
User Profile : Save button functionality not clear

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#318]
The check mark on the save button is misleading. It looks like the changes are saved when they are not.
When changes are saved the check mark shows or the save button is disabled/greyed out.
When changes are made to the profile,the save button become visible/enabled or  the checkmark should not appear, letting the user know that the changes need to be saved. 
![image](https://cloud.githubusercontent.com/assets/20052162/25436003/ed4b8b82-2a5f-11e7-88b4-8b6625a85206.png)

**Comment by joshi1983** [comment]
- I'm leaning more toward disabling than removing the button completely.  I have a feeling the screenreaders could handle the disable/enabling change better than removing and adding.
- The disabled state can be represented with a gray colour.  
- It seems like the checkmark should be removed at all times to simplify how people interpret the button.

**Comment by Blandine-AA** [comment]
I didn't suggest removing the button. I suggested removing the check mark.

I would recommend the enable/disable(grey-out) behavior as most people are used to that, and that will probably work best for screen readers.

**Comment by joshi1983** [comment]
I removed the checkbox because that was really quick and easy.  The remaining work seems good for a student volunteer.

Here is how I suggest breaking this down for a student volunteer:
- [ ] Create a new JavaScript file called something like public/js/profile_save_button.js and include the file by modifying in app/resources/views/pages/profile/profile.blade.php.
- [ ] Whenever any of the inputs change, make the profile's save button change to blue.  This could be implemented by listening to any change events on input and select elements in the profile.
- [ ] Clean up any inline styles that may be used in a pure JavaScript solution by toggling the class attribute for the button and updating resources/assets/sass/app.scss to change the button colour.

**Comment by joshi1983** [comment]
@Blandine-AA did you want a new reset button added to the form to reset all inputs back to how they were before the user started changing them?

**Comment by Blandine-AA** [comment]
@joshi1983 , "Reset" is misleading as it makes think that it is resetting to a certain default state. I would prefer "Cancel", as it clearly means that you are cancelling changes you just made. Then, because there is a save button,  you don't really need to cancel what you did if you change your mind. You just don't save it !

So, I really don't quite see the use case for the "Reset" button.

**Comment by joshi1983** [comment]
I agree.  I'll ask the reset button be left out.

**Comment by joshi1983** [comment]
This is ready for testing.  The work from Bruce was merged and deployed to [app.accesslocator.com](http://app.accesslocator.com).

You can test in the following way:
1. Sign in.  Check that the "Save Profile" button is initially disabled.
1. Change one of the inputs and click away.  See that the "Save Profile" button is enabled again.
1.  Change the input back to what it was.  See that the "Save Profile" button is disabled again.

**Comment by sidhunavroop** [comment]
i cleared my last name and replaced it with what is earlier was and the save button was disabled. so this is working perfectly fine

**Comment by Blandine-AA** [comment]
@sidhunavroop , @gillbalraj,  

If an issue has passed testing. You need remove the "Ready for Testing" label and add the word "PASS" in the comment and then close the issue.

In case the issue fails testing, you need to remove the "Ready for Testing" label and add the "Failed Testing" label and reassign to the developer.

Please update your testing assignments accordingly. BTW, emails were sent few months ago about managing the labels. They are also documented in the meeting notes.

Thanks,

**Comment by Blandine-AA** [comment]
@sidhunavroop why did you add the P1 label?

**Comment by sidhunavroop** [comment]
I had to put pass label. But I could not find it. So I thought may be P1 means pass.

**Comment by Blandine-AA** [comment]
@sidhunavroop, there is no pass label. Read again what I wrote in my comment.

P1, P2... are priority labels to set the time to fix issues.

**Comment by Blandine-AA** [comment]
PASS
