### ISSUE TITLE
Location Report: improved layout needed for mobile devices and small screen size

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#325]
The popup over the location report's map doesn't look good on narrow screen resolutions below 600 pixels wide.  Maybe we can put the popup content above or below the map on screens smaller than 600 pixels wide.

Here is how it looks at roughly 390 pixels wide:
![image](https://cloud.githubusercontent.com/assets/11838191/25559384/b086b2ea-2d06-11e7-9c50-fec36cf6bdf0.png)

@areebakamal what do you think of stacking the popup content above or below the map?  Also, do you prefer above?

**Comment by joshi1983** [comment]
I assigned to @areebakamal just to help get her attention.  I didn't mean that she should implement the solution just yet.

**Comment by Blandine-AA** [comment]
For mobile devices, we should stack the information above the map

**Comment by yashankit17** [comment]
Rating window is loading as in the picture initially and user have to slide the page or zoom out the page to see the complete window.

![](https://user-images.githubusercontent.com/32559887/31854962-030e029c-b66f-11e7-81e2-adc5ba3ff421.jpg)

**Comment by joshi1983** [comment]
Here is another screenshot from Yashankit's iphone:
![image](https://user-images.githubusercontent.com/11838191/32445061-9aaad282-c2d2-11e7-9c08-180b442bbd9e.png)

**Comment by Blandine-AA** [comment]
Check out this for reference:
https://www.smashingmagazine.com/2011/01/guidelines-for-responsive-web-design/

**Comment by Blandine-AA** [comment]
This issue will be used to track the responsive design work so that layout is properly adjusted for small size screens, whether it is on laptop or mobile devices.

- [ ] Create mockups as discussed during the Nov 10th meeting ( @princeseth )
- [ ] Review and validate mockups (@Blandine-AA)
- [ ] implement the mockups ( assign based on team availability)

**Comment by joshi1983** [comment]
Some work closely related to this issue have been implemented so this issue may need a scope adjustment.  Here are the closely related changes:
- #430 helped this by replacing category text with icons for narrow viewports(usually mobile devices).
- the questions have been stacked above the map for very narrow viewports(usually mobile devices).

Now the mobile layout looks like this:
![image](https://user-images.githubusercontent.com/11838191/34907482-1d93b470-f84d-11e7-9fda-d9497a96e1ff.png)

**Comment by Blandine-AA** [comment]
@joshi1983 while testing on my phone, I noticed that the info box is briefly displayed and autmatically replaced by the Rating/View screen. 

The user needs to have access to the info box (the new one) with all high level accessibility information including the rating and comments info.

**Comment by Blandine-AA** [comment]
Can't reproduce anymore.

**Comment by Blandine-AA** [comment]
Testing: PASS
