### ISSUE TITLE
Create data importer for yelp

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#329]
yelp.com has a lot of locations and for each location, there are items like 'wheelchair accessible' and 'wifi' which correspond with questions from our criteria checklist.

Create a tool using Python that can download location information for a given area and convert that information into CSV format.  The more columns of information the better but we'll be very interested in having a minimum of longitude, latitude, name, has wifi, is wheelchair accessible.

https://www.yelp.ca/biz/pho-orchid-toronto

![image](https://cloud.githubusercontent.com/assets/11838191/25597784/d533e628-2e9e-11e7-850f-1e04169a8423.png)

**Comment by Blandine-AA** [comment]
This seems related to #27, as AbleRoad uses and displays Yelp data location

**Comment by joshi1983** [comment]
@yepterence when you get past basics like how to download invidual pages using Python, make an importer for yelp.com.

Blandine mentioned that yelp shares some data with ableroad but that won't affect how these 2 importers work.  Both tools will need to operate quite independent of each other so it seems good to separate the responsibilities to different people.  Bruce will also be very busy with internship work soon.

**Comment by yepterence** [comment]
Got it. I'll keep you posted on my progress.

**Comment by Blandine-AA** [comment]
Because the two apps are intertwined, I agree that both their data are important. Nevertheless, for our use, the info gathered on a specific location from both streams will be "combined" into one.

**Comment by joshi1983** [comment]
There are still some fields that could be extracted for yelp but I think enough of this tool is working to consider this issue complete.
