### ISSUE TITLE
Create Maps prototype

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#33]
Create a small prototype that demonstrates that various points with latitude and longitude can be marked on a mapping service.  It seems like either Google Maps or Openstreetmaps would be best.

**Comment by joshi1983** [comment]
This is planned to be assigned to Bruce after his github account is added to the project.

**Comment by brucelau-github** [comment]
Okay. Got it.

**Comment by brucelau-github** [comment]
http://liu1ee.myweb.cs.uwindsor.ca/hhaccessibility/map.html
I have finish a basic web site with map but I still do not to how to upload them to our github repository

**Comment by joshi1983** [comment]
Good stuff Bruce!

The easiest way to just get those files up is likely to go to https://github.com/hhaccessibility/hhaccessibility.github.io/tree/master/web and click "Upload Files".  Try to add another subdirectory like "maps_demo" or "maps_prototype" and put the files in there.

How familiar are you with git?  These steps are likely more difficult to follow but you'll have to use git soon anyway:
- Open a terminal and cd to a directory where you want to work on the accessibility app.
- git clone https://github.com/hhaccessibility/hhaccessibility.github.io.git
- Add your new files to hhaccessibility.github.io/web/maps_demo
- git branch -b issue-33
- git add -A hhaccessibility.github.io/web/maps_demo
- git commit -m "Created a prototype for marking points in Google Maps"
- git push origin issue-33
- Go to https://github.com/hhaccessibility/hhaccessibility.github.io/branches in a web browser.
- Click "New Pull Request" on your issue-33 branch.
- Message me asking for it to be reviewed.  I'll review within a day and most likely merge to have your changes in the main repository.

When I get https://github.com/hhaccessibility/hhaccessibility.github.io/issues/34 done, we could start mixing your map work in with a more functional application.  I'll try to finish over the weekend so you can work with Laravel next week.

**Comment by brucelau-github** [comment]
I could not commit files to our repository. do you have any idea?
Username for 'https://github.com': brucelau.email@gmail.com
Password for 'https://brucelau.email@gmail.com@github.com': 
remote: Permission to hhaccessibility/hhaccessibility.github.io.git denied to brucelau-github.
fatal: unable to access 'https://github.com/hhaccessibility/hhaccessibility.github.io.git/': The requested URL returned error: 403

**Comment by brucelau-github** [comment]
you probably add me into the contributors.

**Comment by joshi1983** [comment]
You could be right about not being a contributor.  I added you as a contributor recently with write access but not sure if it'll solve your problem.  Can you try pushing again to be sure?

Did you get an invitation to be a contributor?

**Comment by brucelau-github** [comment]
yeah. I have committed the issue-33 branch. Thank you, Joshi.

**Comment by joshi1983** [comment]
Excellent, Bruce.  Thanks.  I merged your pull request so your work is now shown in the intended directory.  

The way you put your work on that branch and made a pull request seems great for how we mix the team's work together in future.

**Comment by joshi1983** [comment]
Hi Bruce,  this is unrelated to the maps prototype but I've been emailing a few times this week and haven't got any replies from you.  Are you getting emails in liu1ee@uwindsor.ca?  If you don't check 	liu1ee@uwindsor.ca frequently, is there another address that you check more often?

**Comment by brucelau-github** [comment]
sorry about that! 
--
Sent from myMail for Android Friday, 04 November 2016, 08:05AM -04:00 from Josh Greig  notifications@github.com :

**Comment by brucelau-github** [comment]
I got your email.  I am so busy with my homework last few days. Sorry about that.  not clear what I could do.  I have tried to build a developing environment on my machine. 
--
Sent from myMail for Android Friday, 04 November 2016, 08:05AM -04:00 from Josh Greig  notifications@github.com :
