### ISSUE TITLE
Use SVG in logo in modern browsers that support SVG images

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#339]
When zooming in lots or using a high pixel resolution device like the iPhone 6, 7, or 8, the logo looks a little blurry or pixelated.  It would look perfectly sharp if we used SVG instead of our small PNG image in these cases.  The vast majority of browsers used by our visitors will support SVG but it seems worth using PNG as a fallback for the minority of visitors on really old browsers.

The blurring and pixelation problem is obvious with this screenshot taken while zoomed in 500%.
![image](https://cloud.githubusercontent.com/assets/11838191/25997835/0ad9324c-36ec-11e7-9f51-d212b6163857.png)

The following snippet from https://css-tricks.com/a-complete-guide-to-svg-fallbacks/ should help us implement the fallback:
```
body {
  background: url(fallback.png);
  background: url(background.svg),
    linear-gradient(transparent, transparent);
}
```

This task will definitely involve updating resources/assets/sass/app.scss but may also involve some small graphics manipulation of logo images in public/images.

When the changes have been completed, make a pull request but don't merge it.

This is somewhat related to #238.

**Comment by stephanosm** [comment]
You may also want  to correct the favicon. It is different in the 3 sites: 1) demo, 2) AL 3} app

![capture1](https://cloud.githubusercontent.com/assets/22602396/25999146/fd7c0272-36f1-11e7-8a27-2b46b688eadf.JPG)

**Comment by joshi1983** [comment]
@stephanosm what URL is each tab on?  The white one is from http://accesslocator.com, right?

I prefer a consistently transparent background over the white background.  It looks like that inconsistency is what you're pointing out.

It may be good to try something like this to use SVG for the favicon.  I took the idea from https://diessi.ca/blog/a-guide-to-favicons-and-touch-icons/ if you need more context:
```
<link rel="icon" href="/images/logo.svg" sizes="any" type="image/svg+xml">
```
I hope browsers that don't support SVG for the favicon will still use the PNG, though.

**Comment by stephanosm** [comment]
Yes the White one is from  http://accesslocator.com 
The number 1 above is from demo and 2 from app. I prefer the transparent too.

**Comment by joshi1983** [comment]
@areebakamal can you update the favicon on the presentation to match the one from public/favicon.ico?  This would be in relation to what @stephanosm said above.

This issue is ready for testing now.  

Here are a few things I did to test it and you could do similar.
- Zoom in lots on the logo in [app.accesslocator.com](http://app.accesslocator.com) and seeing that it looks good.
- Applied the zoom lots step in various browsers and devices including:
    - Internet Explorer 11, Firefox 53.0.2 32-bit, Chrome 58.0.3029.110 (64-bit) on Windows 8.1
    - mobile phone.  The phone was a BLU Advance 4.0 L Android phone with a Chrome browser.  
    - Tested in a tablet.  The tablet was a Samsung CE0168 tablet using Android and a Chrome browser and its "Internet" browser

I don't have an old browser that didn't support SVG.  It would be nice to see that the PNG still loads when the browser doesn't support SVG.

**Comment by areebakamal** [comment]
I've updated the favicon on the presentation site.

**Comment by joshi1983** [comment]
Thanks @areebakamal.  I tested and see the favicon on the presentation site has the transparent background now.  A note to anyone else reviewing that change is that the favicon cache generally stays with the browser and doesn't clear easily.

If we can't find a problem with it, we may want to do this SVG trick to the logo on the presentation site too.  

The SVG I used is here:
https://github.com/hhaccessibility/hhaccessibility.github.io/blob/master/app/public/images/logo.svg

The original logo svg file you created was edited a little to fix some pixelation problems I initially saw in Chrome.  
Here are the changes to the logo svg file:
- A bunch of path elements and a single meta element looked unused so they were removed.
- The circular gradient colours were changed so the bright area blended more gradually into the rest of the circle.  That's how the logo was originally made in raster and one of the few minor differences from the initial SVG so I thought you might have wanted that.

**Comment by joshi1983** [comment]
As mentioned in an earlier comment, this is ready for testing.

Here are a few things I did to test it and you could do similar.
- Zoom in lots on the logo in [app.accesslocator.com](http://app.accesslocator.com) and seeing that it looks good.
- Applied the zoom lots step in various browsers and devices including:
    - Internet Explorer 11, Firefox 53.0.2 32-bit, Chrome 58.0.3029.110 (64-bit) on Windows 8.1
    - mobile phone.  The phone was a BLU Advance 4.0 L Android phone with a Chrome browser.  
    - Tested in a tablet.  The tablet was a Samsung CE0168 tablet using Android and a Chrome browser and its "Internet" browser

I don't have an old browser that didn't support SVG.  It would be nice to see that the PNG still loads when the browser doesn't support SVG.

**Comment by balraj18** [comment]
I tested the logo on Microsoft edge, internet explorer 9 & 11, chrome and iPhone 5& 7 it looks good on all of them.

**Comment by joshi1983** [comment]
I'm closing because it is safe to say that @balraj18 tested and concluded this as a pass.
