### ISSUE TITLE
Create file structure for Laravel PHP framework

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#34]
Get Laravel installed and part of the repository.  We probably also want a quick way to recreate the database and configure it differently for different host machines.

**Comment by joshi1983** [comment]
I'm hoping to get this done by November 5 so the rest of the developers have a place to implement changes instead of making very independent prototypes like Bruce is working on with issue 33.

**Comment by Blandine-AA** [comment]
Sounds good to me!

**Comment by joshi1983** [comment]
I merged the basic structure with pull request 36.  I'll make some new issues to cover the specific improvements I thought of while working on this to make it easier for other developers.
