### ISSUE TITLE
Presentation page : New Feature - Open demo in new window

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#348]
From the "New Feature" tab, when clicking on the latest release, demo should launch in a new window.

**Comment by joshi1983** [comment]
@areebakamal you're maintaining the presentation site, right?  This should just need an extra target="_empty" on the "a" tag.

**Comment by joshi1983** [comment]
This can be tested at http://accesslocator.com/releasenotes.

**Comment by Blandine-AA** [comment]
PASS
