### ISSUE TITLE
Create location data importer tools for Google Places/Maps

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#357]
Create an importer tool that generates CSV files.  This would be very similar to other importer tool tasks.
The Python code for this should be added to a directory like importers/google-places.

A good starting point seems to be looking at Google Place's HTTP API documentation is at:
https://developers.google.com/places/web-service/

**Comment by joshi1983** [comment]
@stephanosm emailed us about Google Local Guides.  Is Google Local Guides a different data source?  Does Google Places include the accessibility information from Google Local Guides?

Here's the video that Stephanos referenced:
https://www.youtube.com/watch?v=LYX5Hqucb3g&list=PLxzP3AVsi8HP-gqj--L2S8N_MWI5ySwJ7&t=115s&index=7

If Google Local Guides is confirmed to be a different data source, we should make another issue to import data from it.

**Comment by Blandine-AA** [comment]
Looking at google places API, it doesn't include accessibility informations. Looks like Google local guide informations are built into Google maps. Here is the article that talks about it:[ Google Maps now shows if a location is wheelchair accessible](https://www.theverge.com/2016/12/15/13968054/google-maps-twenty-percent-wheelchair-accessible)

**Comment by joshi1983** [comment]
It looks like there are some Python packages to help interact with Google's API's.  Some are mentioned at:
- https://pypi.python.org/pypi/python-google-places
- https://stackoverflow.com/questions/39124510/python-google-places-api-want-to-get-all-restaurants-at-a-specific-postion

**Comment by joshi1983** [comment]
I started working on this to help with #404.  I'm hoping that Google Places has enough address information to practically solve #404.

**Comment by joshi1983** [comment]
I merged a couple Google Places tools and some more location data with addresses, phone numbers, and external web addresses for Windsor.  They are deployed at app.accesslocator.com.

Since this is an internal tool for developers, I'm not sure how I'd suggest testing it.  It isn't part of the website but rather a tool that is run using Python.  This is only useful by developers.

**Comment by joshi1983** [comment]
I'm closing this and skipping the usual testing step because I can't think of a useful way to have this internal tool tested.  #404 is benefiting from this work and I'll give some form of testing steps with that.
