### ISSUE TITLE
Location Search view : problem with Radius field

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#360]
Why is it a Radius field in this page? What design discussion happened to have this and how was it decided? I don't remember having validated this... but I might have forgotten.
This needs to be discussed.

![image](https://cloud.githubusercontent.com/assets/20052162/26598281/d6641c7e-4542-11e7-8c0b-de39df7b565a.png)

**Comment by stephanosm** [comment]
any recommendations for this Blandine?

**Comment by Blandine-AA** [comment]
None yet as I need to first understand the intent for the implementation.

**Comment by joshi1983** [comment]
Did you see issue #260?  That radius input is the implementation of #260.

You referenced #260 from #205 on March 21.  Do you remember us discussing the need for having a search radius selection on the location search map?  Comments from March in #205 cover some of that discussion. The table view is basically just a screen-reader-friendly alternative to the map of location search results so if a radius can be selected on the map, it must be selectable from the table view in a screen-reader-friendly way like done in #260.

**Comment by Blandine-AA** [comment]
Thanks @joshi1983 for the summary to remind me of all the discussions around this.

So, here are my comments:
1. I was first surprised by the design, mostly because what was initially proposed was a progress bar not a field to enter value. Why has this changed? Implementation restriction? Screen reader compatibility? The look?

2. The radius field adjustment is only available from the table tab. It should be at a higher level with the location name and always be available whether you have a table or map view.

But, from what you say, the radius filter will be implemented differently on the map view and the table view?

**Comment by joshi1983** [comment]
It was made as a text input because of screen-reader compatibility, yes.  The text input makes it easier for screen readers to read the radius value and help the user type or use arrow buttons to change the value.

Yes, it would be different for the map.  The map is where the progress bar was mentioned.  Given that the map doesn't need to accommodate screen readers, it could be written in a much more aesthetically pleasing way and update the map display as you update the radius value rather than needing a full page refresh.  There are a lot of ways to do it.

**Comment by Blandine-AA** [comment]
@joshi1983 I see that you have improvved the radius field design on the table view. Can we split this into 2 issues, since the Map view will be implemented later and you have the table view done already?

**Comment by Blandine-AA** [comment]
Closing this as the radius field on the Map view will be implemented in #373 .

**Comment by joshi1983** [comment]
@Blandine-AA yeah I was just going to say that and then saw you closing here.  hehe  That was fast.
