### ISSUE TITLE
Rating Feature: Improve the Rating UX Flow

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#367]
The rating feature has been implemented in #200 , but we need to better integrate it in the rest of the application and improve the user experience flow.

**Comment by joshi1983** [comment]
To this effort, I suggest the following tasks be completed:
- [ ] Make the signin page show a message defined in the URL.  The message may be passed like "/signin?msg=You+need+to+sign+in+to+rate"
- Make the sign in redirect to a specified URL upon success.  THE redirect URL could be defined like "/signin?msg=You+need+to+sign+in+to+rate&redirect=/location-rating/00000000-0000-0000-0000-000000000434/6"
    - [ ] Make the sign in redirect work for the sign in form.
    - [ ] Make the sign in redirect work for Google authentication.
    - [ ] Make the sign in redirect work for facebook authentication.
- [ ] From the location report page, pass a msg and redirect URL from the rate link when the user isn't signed in.

**Comment by joshi1983** [comment]
@remnantmisook can you test this?

**Comment by remnantmisook** [comment]
I tested on my desktop and iphone, and it looks good.

**Comment by Blandine-AA** [comment]
PASS
