### ISSUE TITLE
Location Search: Radius input elements need to be more responsive

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#371]
The radius input elements wrap the "Update" button to a new line when the viewport width is under 769 pixels as shown here:
![image](https://user-images.githubusercontent.com/11838191/26973881-9f3e5bd2-4ce6-11e7-8eb7-5044d025f1da.png)

It would look better like this:
![image](https://user-images.githubusercontent.com/11838191/26974088-c4968b88-4ce7-11e7-87a1-c47492db59be.png)

This will involve adjusting _location_search.scss and probably involve adjusting spreadsheet.blade.php.

This is related to #260 because that issue added the radius input fields.

This was marked with P1(Priority 1) because this is associated with a feature released on 0.0.4.  We want to polish what we've released before moving on.

**Comment by joshi1983** [comment]
The location search has become much more responsive.  Here are a few screenshots from a few different viewport widths to show how it looks in Chrome on my laptop:
![image](https://user-images.githubusercontent.com/11838191/32987682-a7de5710-ccc0-11e7-8a06-333da542400a.png)

![image](https://user-images.githubusercontent.com/11838191/32987687-c322f800-ccc0-11e7-99d1-60039650da1b.png)

These changes can be tested by just going on app.accesslocator.com and resizing the width of the location search.  It would be useful to also test with mobile devices.

**Comment by yashankit17** [comment]
I have tested this and its working absolutely fine on all view-ports.

**Comment by joshi1983** [comment]
I'm closing this as Yashankit found no problem with it.  I made a new issue #444 for a suggested improvement he had, though.
