### ISSUE TITLE
Some uploaded photos use incorrect orientation

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#372]
Some photos taken by Areeba are uploading with the wrong orientation(90 degrees rotated).

This was initially discussed in #276.

This was marked as priority 1, P1, because it is associated with work released in demo 0.0.4.  We want to polish released work before moving onto new features.

**Comment by joshi1983** [comment]
This may be useful: https://gist.github.com/msurguy/5414812

**Comment by joshi1983** [comment]
From testing a bit, it looks like different software can show the same image in different orientations.  Some images are listed here: https://github.com/recurser/exif-orientation-examples which show this.

I suggest a new feature that lets the user rotate the image in 90 degree increments in a clock-wise direction.

The resulting UI could look like this:
![image](https://user-images.githubusercontent.com/11838191/35127336-b8ee58cc-fc7f-11e7-84af-02e89ad91677.png)

You could use CSS classes to get the rotate icon such as:
http://fontawesome.io/icon/repeat/

You could implement this by adding a new method in ProfilePhotoUploadController.php and have it rotate the profile image file.  Other methods in there already manipulate the image to validate the uploaded file.  You'd also have to add your new route in routes/web.php.

**Comment by joshi1983** [comment]
@remnantmisook you worked on this mostly but I added some minor changes.  Can you test the feature on app.accesslocator.com to see what I did?

**Comment by remnantmisook** [comment]
@joshi1983 yes I can see what you added, and they look good. Yes, currently rotate icon does not show when you navigate the profile, shows when you upload new profile, and the icon disappears after 20 secs. One thing I want to ask is then if I refresh the page, the rotate icon re-appears. Is it okay(bearable) ?

**Comment by joshi1983** [comment]
@remnantmisook nice catch.  Yeah, that's not ideal.  It isn't a really big problem but it would be nice to avoid having the refresh show the rotate feature again.  Ideally, it shows only after an upload or a rotate event.  Can you look into making an improvement for that?

Here are some thoughts to get you started on an improvement:
- Replacing the ? with # might make it easier because # marks the beginning of an internal anchor.  If there's no way to use JavaScript to remove the ? without reloading the page, it may be possible to remove an internal anchor from the address bar.

**Comment by joshi1983** [comment]
This is ready for testing again.  @remnantmisook's work was merged and deployed to app.accesslocator.com.

**Comment by Blandine-AA** [comment]
Testing: PASS
