### ISSUE TITLE
User Profile: Edge browser sometimes overlaps province/state suggestions with city

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#375]
@balraj18 ran into a bug that has been difficult to reproduce.  @balraj18 commented on it with #212.

Here is a copy of what Balraj ran into:
![image](https://user-images.githubusercontent.com/11838191/27005956-46957af8-4df7-11e7-867e-d7cecc463baf.png)

This was marked as P1 because it is a bug and because it is associated with a feature that has been released.

**Comment by Blandine-AA** [comment]
**P1** means that it needs to be fixed within 1 week once it has been assigned

**Comment by joshi1983** [comment]
ok, I was forgetting that and thought it meant "priority 1".

Do you think we should stick to that definition?  I wonder if considering P1 as top priority would work better for this project since it is elusive where that week started and will end without additional commenting and difficult to trust that it'll really be done by the required deadline.  If it meant top priority or high priority, it means people need to work on it before issues without it.

Also, what does the "P" mean when the definition is something like "must be closable within 1 week"?

**Comment by Blandine-AA** [comment]
yes P1 means Priority 1 and  all P1 will need to be fixed within 1 week after assignment. This is just so that it is easy to remember the due date. Otherwise, we might get to the end of the release and have a P1 issue still on someone's plate!

When I was working for Nortel, we had to fix all P1 within 24 h.

**Comment by joshi1983** [comment]
Since @passionInfinite had some changes merged that replaced an input with select for representing the province, this issue should be tested to see if it is still a problem.

**Comment by singlaneha2205** [comment]
@joshi1983 and @Blandine-AA I tested this issue and is working successfully for Chrome, Firefox. But I noticed an issue with the edge browser. The Country drop-down box is very much bigger in size. The countries displayed are only Canada and the United States but the size of the box is very big which can be interpreted as an empty list by the user. Refer to the screenshot below. But the size is fine chrome and firefox
![image](https://user-images.githubusercontent.com/40703592/42404430-fac2c470-8156-11e8-96ab-c74c52cd9b61.png)
![image](https://user-images.githubusercontent.com/40703592/42404435-113f5650-8157-11e8-990c-1ab1a091b595.png)
Also, the country list displayed is different in IE. Please refer the screenshot
![image](https://user-images.githubusercontent.com/40703592/42404469-56767d48-8157-11e8-9717-85ba358902dd.png)

**Comment by joshi1983** [comment]
This bug is now fixed.  

The home country, region, and city was moved to another page in November but that still left a bug in Edge where a lot of blank space showed in the country drop-down.  The empty space in the country dropdown was fixed with the deployment of a fix just now.
