### ISSUE TITLE
Presentation page: change New Feature tab to "Release Notes"

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#376]
Looking at the release notes web page, it occurred to me that we should rename the "New Feature" tab to "Release Notes". It will be more appealing.

**Comment by joshi1983** [comment]
@areebakamal did you want to do this?

You mean the menu item, right?
![image](https://user-images.githubusercontent.com/11838191/27056704-3f3b4c00-4f97-11e7-8a05-5833bf62083a.png)

Would you want all the titles within the Features page also renamed?
![image](https://user-images.githubusercontent.com/11838191/27056721-55347c66-4f97-11e7-9654-3959e04e96ab.png)

**Comment by areebakamal** [comment]
> Would you want all the titles within the Features page also renamed? @Blandine-AA

**Comment by Blandine-AA** [comment]
@areebakamal, just the first one, the tab title. Paragraphe titles can remain the same.

**Comment by Blandine-AA** [comment]
PASS testing
