### ISSUE TITLE
Sign Out :  add a tool tip description when the user hovers on the sign out icon

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#378]
Feedback from Kim: 
> The logo is great but I found myself hesitation and hovering over the logo waiting for confirmation.

The tool tip to say "**Sign out**".

**Comment by joshi1983** [comment]
By "tool tip", @kimficara are you asking for something like this?
![image](https://user-images.githubusercontent.com/11838191/27061187-1145eb3e-4fb0-11e7-87ea-34b5cfcb8735.png)

**Comment by kimficara** [comment]
that's perfect!  just something for the user to confirm that they are signing out.

**Comment by joshi1983** [comment]
That's simple enough.

It is ready for testing on app.accesslocator.com.
Testing instructions: Sign in and hover over the sign out icon to see the new tool tip.

**Comment by Blandine-AA** [comment]
PASS
