### ISSUE TITLE
Create location importer for uwindsor website

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#381]
Terence found some location information available on the University of Windsor's website and wanted to learn how to make an importer tool for it.

The page showing the locations is at:
http://web2.uwindsor.ca/pac/campusmap/index.php

After some inspection using Chrome's developer tools, the following XML document was being downloaded which should have most of the information needed for an importer.
http://web2.uwindsor.ca/pac/campusmap/markers.xml

This would involve using Python and [Python's lxml package](http://lxml.de/parsing.html) to convert the XML to a CSV file with fields for location name, latitude, and longitude.

This tool will help with gathering information on a few locations on the University of Windsor's campus and give Terence an opportunity to get familiar with creating location importers.

Beyond the minimal name, longitude, and latitude fields, the following fields would also be useful in the CSV file:
- [x] The URL which would be 'http://web2.uwindsor.ca/pac/campusmap/' + the nameURL attribute.
- [x] location description from the marker's mtext attribute.

**Comment by Blandine-AA** [comment]
- [ ] I suggest to also collect the 2 accessibility information/fields Entrance and washroom
- [ ] Also map the **Handi Transit Stop** as a location. Note: This is similar tto a bus stop and will go in the transportation category.

**Comment by joshi1983** [comment]
The bus station is in our data but not bus stops right now.  That can be adjusted, though.

Do you want all bus stops added and rate-able like any other location?  I guess they'd all be named "bus stop" and have blank addresses.

**Comment by yepterence** [comment]
I managed to collect the information regarding the building and their
location (lat/lng tuples), as well as the accessible locations (lat/lng
tuples) for the buildings, their washrooms and the text which gave
information on how to access the buildings.

I stored the information in a dictionary and I am currently trying to
figure out how to tabulate the information I had collected.

**Comment by joshi1983** [comment]
Great work, Terence.  

I suggest using Python's csv package to write the output.
An example using the csv package is in importers/toiletfinder.com/generate_csv.py.

You could write the file like any other plain text file by separating values with commas and separating each location with a line break("\n") but there are some special cases handled better by the csv package.  These special cases include things like when a value contains a comma and therefore needs to be quoted or encoded in a special way.

I'll be available to chat after 6pm tonight.  I could look at your code and help you make a pull request for it over gmail and TeamViewer.

**Comment by joshi1983** [comment]
Terence's work on the uwindsor importer is merged.  It included a name, latitude, longitude, URL, and description for each campus location.  

Locations such as emergency phones were filtered out because I thought we wouldn't want them listed as accessibility ratable locations.

**Comment by joshi1983** [comment]
We should look into this data source a little more before closing.

Blandine suggested the following in a previous comment:
- [ ] I suggest to also collect the 2 accessibility information/fields Entrance and washroom
- [ ] Also map the **Handi Transit Stop** as a location. Note: This is similar to a bus stop and will go in the transportation category.

The following fields should also be generated in the CSV:
- is_educational  - either TRUE/FALSE indicating that the location is for teaching and learning
- is_restaurant - either TRUE/FALSE used for locations that contain food services and restaurants
- is_accommodation - either TRUE/FALSE used for dorms and places people sleep

The categories are listed on the home page at http://demo.accesslocator.com/.

**Comment by joshi1983** [comment]
The seed data was updated to include all locations from the University of Windsor campus map importer.
This didn't include the accessibility information Blandine mentioned even though that would be helpful.  

This did include 2 handi transit stops, though.  I don't know if maintaining all bus stops is worth it but the handi transit stops are only 2 and closely tied to accessibility.

I have yet to create a tool for safely updating the location data on app.accesslocator.com to use it.  I could just drop and recreate the data with all the seed data in it but want to update the data on app.accesslocator.com the way I ultimately want to update it in demo when demo 0.0.5 is released so without dropping everything and recreating it.

**Comment by joshi1983** [comment]
The tool to merge location data into app.accesslocator.com data has been created as part of work on #404.  Since this is an import tool, it isn't directly testable on app.accesslocator.com.  Some of the imported locations may have duplicates but this can be tested and troubleshooted with work on #404.   Since I consider this complete and there's no way to test this through the app.accesslocator.com distinctly from testing #404, I'm closing this issue.
