### ISSUE TITLE
sign up: email validation doesn't work properly

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#382]
Email validation was implemented through #199.

After sign up, the screen indicates that a verification email was sent. **The user is still able to sign in and access the site as usual even without verifying**. This should not be allowed!

The email has to be verified first before the user can sign in.

**Comment by joshi1983** [comment]
This should be fixed so I'm marking this ready for testing.

**Comment by M4ttoF** [comment]
Confirmed that this worked, can change label

**Comment by passionInfinite** [comment]
@joshi1983  Close this if it works!

**Comment by joshi1983** [comment]
I'm closing as someone not involved with implementing the fix or reviewing it tested and found that it works.
