### ISSUE TITLE
Mobile: Contact form display issue

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#385]
Mobile (LG G4) - Contact Form - The Send Message button is cut off (only about half of the button is visible).
Make it auto-resizeable so that it is not truncated regardless of the screen size.

**Comment by joshi1983** [comment]
Did Meagan make a screenshot of this?  

Here is a screenshot from Chrome when a narrow width is used on the contact form.
![image](https://user-images.githubusercontent.com/11838191/27915805-47a68138-6235-11e7-803d-0ac018a32470.png)

Does she mean that it is cut off the bottom of that particular browser?

**Comment by Blandine-AA** [comment]
Is this on a mobile phone?
She didn't send a screen shot, but you can ask her?

**Comment by joshi1983** [comment]
My screenshot was from my laptop.

Yeah, I referenced Meagan's github account in the comment so she'll probably be emailed about it.

**Comment by Blandine-AA** [comment]
When we have verified that the Responsive design guidelines are applied, maybe this problem will go away.
Some screen shots made while testing the layout. Regardless if we are using the demo or development versions
1. Resizing horizontally, the CAPTCHA section does not resize properly.
![image](https://user-images.githubusercontent.com/20052162/32749107-48707ca0-c88c-11e7-83b0-e6fd22e69610.png)
1. Resizing vertically, even with the scroll up/down showing, the send button is right on the edge of the bottom of window. We need some blank space there.
![image](https://user-images.githubusercontent.com/20052162/32749260-d13307ba-c88c-11e7-8b85-f3b78c300fe0.png)

**Comment by joshi1983** [comment]
The following may be useful for anyone working on this:
https://stackoverflow.com/questions/27691411/change-new-google-recaptcha-width
https://github.com/google/recaptcha/issues/61
https://geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/

Ideally, this could be fixed with a setting officially documented and supported by recaptcha.  Unfortunately, it looks from my quick reading like some width-specific CSS may be needed to scale the box to smaller sizes.  This might interfere with the effectiveness of recaptcha but lots of people say that's the only way to make it work at all.

**Comment by joshi1983** [comment]
I merged some improvements to reduce the size of the recaptcha feature on the contact page when smaller screens are used.

These changes are deployed on app.accesslocator.com and ready for testing.

**Comment by Blandine-AA** [comment]
Doesn't work. Captcha is still truncated and does not resize

**Comment by joshi1983** [comment]
You're using app.accesslocator.com and not demo, right?
Also, can you give a screenshot of the failure?  Obviously I tested and haven't experienced the same problem so more information would help us resolve it or learn if mistakes were made in the test procedure.

**Comment by Blandine-AA** [comment]
@joshi1983 ,

Yes I used app.... and refreshed it many times. Tested on Chrome, same problems as before.
This is the slimest view I could get on my laptop. 
![image](https://user-images.githubusercontent.com/20052162/32797590-4fa338c8-c940-11e7-9c33-459993337748.png)

**Comment by joshi1983** [comment]
Thanks for the screenshot.  I'll test with Safari, an Android tablet, and an Android phone after work.

The keyboard shortcut to thoroughly refresh is CTRL+SHIFT+R.  In Chrome, you can also open an "Incognito Window" to rule out a caching problem.
![image](https://user-images.githubusercontent.com/11838191/32800334-01eec45a-c948-11e7-8a0a-39cdadef865e.png)

I'll test with the other devices and get back on this tonight.

**Comment by Blandine-AA** [comment]
@joshi1983 , after a force refresh (Ctrl+Shift+R), it looks much better for the CAPTCHA, but the second issue with the Send button right on the bottom is still there.
![image](https://user-images.githubusercontent.com/20052162/32813095-6d25a562-c976-11e7-89f6-5175192c7bb5.png)

**Comment by joshi1983** [comment]
A little space was added below the "Send Message" button so it looks better when you have to scroll to see the button.  It looks similar to this on a narrow width and height now:
![image](https://user-images.githubusercontent.com/11838191/32974744-a05e1478-cbce-11e7-9562-41c8afeaad38.png)

**Comment by yashankit17** [comment]
I tested it using different view-ports and different devices. Both the reCAPTCHA and 'Send Message' elements are now perfectly aligned according to the page width.

**Comment by joshi1983** [comment]
I'll close because Yashankit's testing didn't find any trouble.
