### ISSUE TITLE
Home Page: Click on Map Should Set Current Location

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#397]
From some of Yashankit's testing, he found the map on the home page intuitively unresponsive for when he clicks on it.  He expected the current location to move where he clicked.

We could make this work by introducing a special format for location text that indicates longitude and latitude coordinates.  This would mean that if someone clicks on the map, the "Location" field gets immediately filled in with coordinates of the clicked point like shown in the following screenshot:
![image](https://user-images.githubusercontent.com/11838191/32399129-ffb398fe-c0c9-11e7-932c-263d862b0155.png)

**Comment by joshi1983** [comment]
When a location description can be calculated very close to the clicked location, use that description instead of the (latitude, longitude) format.  In cases where the description can't be found very close to the location, use the (latitude, longitude) format described above.

**Comment by joshi1983** [comment]
@yashankit17 can you add some testing instructions to a comment here? Just give some steps to guide a user through how to see the changes you've made.  I suggest at least using the 2 cases but please elaborate into 3 or 4 small steps.

**Comment by yashankit17** [comment]
-> User can click on the map to select the current location in the address input field.
-> Clicked location will be mapped to a nearest address if there is any valid address within 100 m.
-> If the clicked location doesn't map to any valid address then coordinates are shown in address input field.
-> And the clicked location is preserved even when the user reloads page or come back to home from any page.

**Comment by joshi1983** [comment]
@balraj18 can you test this?

**Comment by gillbalraj** [comment]
Everything is working smooth as per described by @yashankit17. However, I observed another strange behavior of the **pin-point**. It stops moving after certain clicks(however the location in the address input field still changes).
It is shown in the screen-shot
![capture 1](https://user-images.githubusercontent.com/26493273/33233566-edd511e4-d1e5-11e7-8477-0916ddba9183.JPG)

**Comment by joshi1983** [comment]
@balraj18 I'm having some trouble reproducing the problem you mentioned.  Here's a video of what I see when using the click to move map feature from this issue:

I had to zip the file to include it in a comment on github:
[bandicam 2017-11-25 13-46-00-136.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/1503307/bandicam.2017-11-25.13-46-00-136.zip)

**Comment by balraj18** [comment]
okay,
check this out. it dsnt happen very often though.

**Comment by yashankit17** [comment]
@gillbalraj i watched the video you provided to show the issue but i didn't found where you are getting that issue i can see that it takes little pause to move the marker to clicked location but eventually marker was moving in all cases.
if you can tell which address you are talking about in that video than i can pay attention to that specifically.

**Comment by gillbalraj** [comment]
@yashankit17 @joshi1983 pay attention to the pin-points and address field between 30 to 45 seconds.

**Comment by yashankit17** [comment]
@gillbalraj But the video on this link is only of 26 seconds

**Comment by gillbalraj** [comment]
@joshi1983 @Blandine-AA  I tested various locations across Canada and States, its working as expected.

**Comment by joshi1983** [comment]
Thanks @gillbalraj.  I'll close the issue since it looks like this issue and every problem found from testing has been resolved.
