### ISSUE TITLE
Testing: create report on test results with screenreader

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#398]
Blind, visually impaired, and users with disabilities that make it difficult to read use screen reader software.

A free screen reader is available at: https://www.nvaccess.org/download/

The main question we want to know is: How difficult is it to use the application as a user who depends on a screen reader?

Specific use cases to focus the report around will include:
- Finding locations and learning how they rate
- Signing up for a new account, filling out the profile and checking that the user uses a screen reader
- Rating a location

**Comment by Blandine-AA** [comment]
To be tested on laptop or desktop AND mobile device

**Comment by yashankit17** [comment]
Hi Blandine

Please find the attached report on several issues i found while using the
app with NVDA screen reader.

Thank You

**Comment by joshi1983** [comment]
@yashankit17 I couldn't find the attached file in your comment.  Did you forget to attach?  I was emailed a report on mobile optimization problems, though.

**Comment by joshi1983** [comment]
@yashankit17 you emailed me a report on iphone testing.  That report is good for #399 but not for #398.

When you have a report for screen reader testing, you can add it by editing the comment and dragging the file into it.

**Comment by joshi1983** [comment]
This comment is some feedback on @yashankit17's report.  I'll comment on most of the report points in the order from the report here:
- Regarding the home page's address field, we tested in the November 10 meeting that there is a subtle reading of "address" when we tab to the address field.  It is tricky to hear but likely something a blind user would frequently look for.
- Regarding the user profile save button, did you try after making changes?  The save button is intentionally disabled unless a change needs to be saved as part of #318.
- The report mentions that we should use full names for all locations.  Do you have examples of locations that were abbreviated and shouldn't have been?
- For the reading of "Clickable clickable", I think that's a bug in the NV Access screen reader.  I couldn't find any markup problems in the home page that would justify it.  This bug seems to be reported here: https://github.com/nvaccess/nvda/issues/7430
- We shouldn't need to worry about using the arrow keys because blind users will use tab keys.

**Comment by yashankit17** [comment]
- Save Profile button is working fine if the user has made some changes to profile.
- There are several locations mainly high schools and elementary schools where names are given in abbreviated form like : F.W. Begley High School

**Comment by joshi1983** [comment]
I'm closing because:
- the requested report was made by Yashankit and included with a previous comment
- all reasonable improvements discovered by the testing have been implemented or included in other issues
