### ISSUE TITLE
Testing : Feedback using AL on iPhone

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#399]
Yashankit tested AL on iPhone and found the following issues (see attachment).
[iPhone Issues.pdf](https://github.com/hhaccessibility/hhaccessibility.github.io/files/1446515/iPhone.Issues.pdf)
The issues listed can be tracked separately to facilitate concurrent resolution. See #325 
Check out this for reference on responsive web design:
https://www.smashingmagazine.com/2011/01/guidelines-for-responsive-web-design/

**Comment by Blandine-AA** [comment]
The first issue reported in the document only shows on the demo version as is not related to the app itself. Opened issue #401 to track it

**Comment by yashankit17** [comment]
Testing report on Iphone after implementing recent modifications.

[New_Testing_Report.pdf](https://github.com/hhaccessibility/hhaccessibility.github.io/files/1556623/New_Testing_Report.pdf)

**Comment by Blandine-AA** [comment]
Created #527 to track the click responsivness for locations' categories.
All the other issues are fixed. PASS
