### ISSUE TITLE
Testing Rating: wrong timestamp (time) for comment

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#403]
submitted a rating with comment at nov 14, 2017 at 2 pm through the Profile. Then checked the report and the timestamp (time portion of it) in the comment is wrong: 2017-11-14 19:05:53
![image](https://user-images.githubusercontent.com/20052162/32799342-6ff0eb20-c945-11e7-9362-3269347242a4.png)

**Comment by joshi1983** [comment]
That's probably from an unexpected time zone.  Did you want to use Windsor, Ontario's time zone for now?

I guess later on, we might want to report in whatever the time zone associated with the location of interest but that's probably more complicated than we'd want to deal with right now.

**Comment by joshi1983** [comment]
The fix for this is deployed on app.accesslocator.com.

The testing steps I recommend are:
1. Sign in and pick a location to rate.
1. Add a comment saying what time it is.
1. Click 'Submit'.
1. Go back to that location and view your comment under 'View'.  See that it is the correct time.

**Comment by joshi1983** [comment]
I found a bug that I introduced in this work.  I'll troubleshoot it now before marking this ready for testing again.

**Comment by joshi1983** [comment]
The bug from previous comment seems to be fixed now.

Here is a screenshot from when I followed my own recommended test steps:
![image](https://user-images.githubusercontent.com/11838191/32987451-436a9164-ccba-11e7-905b-1823003080c1.png)

The testing steps I recommend are:
1. Sign in and pick a location to rate.
1. Add a comment saying what time it is.
1. Click 'Submit'.
1. Go back to that location and view your comment under 'View'.  See that it is the correct time.

**Comment by Blandine-AA** [comment]
@joshi1983 , regarding
> I guess later on, we might want to report in whatever the time zone associated with the location of interest but that's probably more complicated than we'd want to deal with right now.

I think it should be the time of the computer used to make the comment. Which normally should be the users current location time zone. No need to make it more complicated than necessary. We could reverse-engineer what is done on other web sites if needed. But I guess it is what you've already implemented. Correct?

**Comment by joshi1983** [comment]
For now, app.accesslocator.com is using Windsor's time zone regardless of the browser's time zone.

I like the idea of using the browser's time zone, though, so I'll make that happen.

**Comment by joshi1983** [comment]
I used the browser's time zone to display the comment submission times.

- I also sorted comments so the newest are at the top.  I vaguely remember this being requested in a meeting a while ago but we might have forgotten to make an issue for it.
- To mitigate the problem where if daylight savings time happened recently, the new time zone offset would be used even for dates earlier than the time change, I showed only dates for comments older than 1 week.  This means the misleading time format will last only up to 1 week after daylight savings time.

The testing steps I recommend are:
1. Sign in and pick a location to rate.
1. Add a comment saying what time it is.
1. Click 'Submit'.
1. Go back to that location and view your comment under 'View'.  See that it is the correct time.
1. Rate same location again and add a new comment under the same category.
1. Submit.
1. Go to View for the location and notice that your new comment is above the old comment.

**Comment by princeseth** [comment]
The Date-timestamp for comment displays actual time submission time both on desktop and mobile device.

**Comment by joshi1983** [comment]
I'm closing according to Prince's feedback.
