### ISSUE TITLE
Rating Criteria: Disabled answers should be greyed out and made less visible

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#405]
For the Not Required box that are disabled, the text also needs to be greyed out.
In the example below, for the Lit parking lotcriteria only the YES or NO values should be available. As there is light or not, you cannot say I didn't look :)
![image](https://user-images.githubusercontent.com/20052162/32801332-c2ee7590-c94a-11e7-82b2-837ddd57666f.png)

Tasks for this issue:
- [x] disable the "I Didn't Look" answer for the "Lit parking lot" criteria
- [x]  grey out text of the disabled answers for all the criteria having disabled answer buttons

**Comment by joshi1983** [comment]
A blind user would have a hard time verifying if the parking lot is lit or not so he might still want to click "Didn't Look".

**Comment by joshi1983** [comment]
I brightened up the text colour for the disabled buttons.  They look like this now:
![image](https://user-images.githubusercontent.com/11838191/32818048-00776194-c98f-11e7-83cb-ac0a29d06353.png)

This can be reviewed on app.accesslocator.com.

I'm still waiting for confirmation about if we care about letting blind users click "Didn't Look".

**Comment by Blandine-AA** [comment]
good point for blind users... If you can make it specific for blind users, then ok.

**Comment by joshi1983** [comment]
@Blandine-AA I could make it specific to the status of the screen reader checkbox on the user profile:
![image](https://user-images.githubusercontent.com/11838191/32908960-3c08f3c2-cad3-11e7-988f-98daf0666db2.png)

Does that sound good?

**Comment by joshi1983** [comment]
The 'Didn't Look' is disabled for users who don't use screen readers on specifically the 'Lit parking lot' question.

Here's how it can look when a blind user indicates that he didn't check for the lit parking lot:
![image](https://user-images.githubusercontent.com/11838191/32981960-57d686be-cc4a-11e7-9d3c-9bceda4a138d.png)

Here's how it looks for any user without the 'Screen Reader' box in the profile and save.
![image](https://user-images.githubusercontent.com/11838191/32981968-882e1944-cc4a-11e7-81a9-ace7a705244f.png)

This is ready for testing.  Do the following to test:
- Go to app.accesslocator.com (not demo.accesslocator.com).
- Sign in and go to rating feature for the Parking category.
- Thoroughly refresh your browser especially if you don't see the greyed out change on the button. 
 That's CTRL+SHIFT+R in Chrome.
- Try both states of the checkbox 'Screen Reader' on the profile and remember to click 'Save Profile'.

**Comment by joshi1983** [comment]
I checked off the "disable the "I Didn't Look" answer for the "Lit parking lot" criteria" task because it is complete according to some of the later comments about limiting it to users who don't use a screenreader.

**Comment by yashankit17** [comment]
i have tested this and seems to be working absolutely fine in all scenarios.

**Comment by joshi1983** [comment]
I'm closing because Yashankit said this passed.
