### ISSUE TITLE
Small Screen Layout: issue with the sign in page when clicking on Profile menu

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#406]
1- start is image 1 for the home page. This is the slimmest window possible on my laptop
2- image 2, I click on the profile menu. The layout is not adjusted to the window.
3- image 3, I resized the window and this is the slimmest window possible for the sign in page, even with a shorter username (Blandine for example)
4- layout is properly asjusted when clicking on the FAQ and Contact menus.
![image](https://user-images.githubusercontent.com/20052162/32813678-3db264d4-c979-11e7-834b-ed7063b97fc1.png)

**Comment by joshi1983** [comment]
In image 1, the home page looks pretty good, right?

I implemented some improvements to the Sign In layout at http://app.accesslocator.com/signin for very narrow viewports but I wouldn't call it ready for testing yet.

**Comment by joshi1983** [comment]
The sign in page should look similar to this when viewed with the viewport width from this issue's original screenshots.
![image](https://user-images.githubusercontent.com/11838191/32974667-f65280cc-cbcd-11e7-8d6d-c81105cbe869.png)

This is ready for testing at http://app.accesslocator.com/signin.  Remember to thoroughly refresh the browser with something like CTRL+SHIFT+R to see the changes.

**Comment by yashankit17** [comment]
Home page and sign in page looks good on all devices as well as on the narrowest view-port on all browsers.

**Comment by joshi1983** [comment]
I'm closing because @yashankit17 said this was passing.
