### ISSUE TITLE
Rating page: change Report button by View

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#408]
I find the word "Report" confusing and not intuitive.  "View" will better direct the user to what to do.
![image](https://user-images.githubusercontent.com/20052162/32846190-958326a0-c9f4-11e7-9d86-ded0929b9a10.png)

**Comment by joshi1983** [comment]
This can be tested by visiting a page like: http://app.accesslocator.com/location-reporting/466/2 and seeing that the button says "View" instead of "Report".

**Comment by yashankit17** [comment]
I tested this modification on several devices and using different window widths on the laptop browser.
its working completely fine on all links.

**Comment by Blandine-AA** [comment]
@yashankit17 , great work.

Now you should remove the "Ready for Testing" label and close it with the word "PASS" in the comment

**Comment by yashankit17** [comment]
i don't have access to edit labels and to close the issues.

**Comment by joshi1983** [comment]
I'll close the issue since @yashankit17 seems to have lower permissions.  I guess "read" access as a contributor means a few permissions on the issues are reduced.
