### ISSUE TITLE
Location Rating: Accessibility criteria layout on mobile devices or small size screens

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#409]
See issue #30 for the initial mockups.
Adjustments:
1. remove the +Rate and create and hyperlink on the accessibility criteria
![image](https://cloud.githubusercontent.com/assets/23005093/20239848/77b01b8a-a8d8-11e6-803a-dc48a5822d29.png)
1. When the user clicks on the accessibility criteria, open the rating options below the criteria to allow the user to rate. Of course "Didn't Notice" is now "Didn't Look"
![image](https://cloud.githubusercontent.com/assets/23005093/20239874/d5ae2a7e-a8d8-11e6-8760-930921ecff70.png)
![image](https://cloud.githubusercontent.com/assets/23005093/20239844/6bb8ba62-a8d8-11e6-8b21-74cfe5e87df2.png)

Tasks list:
- [ ] Create new mock-ups, that also include the current comment section ( @princeseth ) 
- [ ] Validate mock-ups ( @blandine-AA )
- [ ] Implement ( assign based on team availability)

**Comment by joshi1983** [comment]
I don't really like those mockups.  Are they from Areeba from several months ago?

Here's a few specific questions and comments I have about them:
- They look completely different from how the application looks on the desktop and that's pretty different from what was discussed in November 10's meeting.  This isn't only bad for consistency's sake. 
 It'll also be more work to implement the change.
- What happened to the menu button that pops out a listing of all categories?  We discussed it in the meeting and thought that's something we wanted.
- Why have the user click 2 things instead of 1?  On the desktop layout, they can rate each and every question by clicking or touching 1 thing per question, one of the Yes, No, ... buttons.  Here they have to click "+Rate" or an accessibility rating link and then enter a value.
- This expansion of elements on the screen may not be read by screen readers well since screen readers don't listen to document changes very well.  A full page load is much more reliable.

**Comment by Blandine-AA** [comment]
@joshi1983, 
Thanks for your feedback and taking the time to provide some mockups to explain your ideas.

Regarding your questions...
>- They look completely different from how the application looks on the desktop and that's pretty different from what was discussed in November 10's meeting.  This isn't only bad for consistency's sake. 
 It'll also be more work to implement the change.

First I don't appreciate the tone of this comment... Second, I opened this issues to track the discussion about the new mockups and I used the existing mockups to show @princeseth the layout that we needed for the criteria section so to create the new mockups. You should have also read the adjustment that I mentioned to guide for the creation of the new mockups. You would have realized that the functionality is not the same 

> - What happened to the menu button that pops out a listing of all categories?  We discussed it in the meeting and thought that's something we wanted.

This is not explained in this issue. There is another issue #410 to track the overall layout of that page.

> - Why have the user click 2 things instead of 1?  On the desktop layout, they can rate each and every question by clicking or touching 1 thing per question, one of the Yes, No, ... buttons.  Here they have to click "+Rate" or an accessibility rating link and then enter a value.

It looks more appealing on a smaller screen to have it the way I described with the hyperlink. Now, it could be a challenge to implement 2 different visuals as the screen size is reduced. Based on you next comment on screen readers, it might be good enough for now to maintain the same display as on full screen.

> Unlike the following image, I guess we could add the Submit button to the popup menu too.

Regarding the Submit button, I would suggest to have it on the left side of the Rate button, as the category menu is supposed to close once a category is selected.

Also, the Next button  and Comment section will be maintained where they currently are.

In the end, this was @Prince task to provide those mockups and I hope this discussion has clarified what needs to be done. So, I am looking for @Prince overall proposal on #410.

Hopefully I've answered all your questions...

**Comment by joshi1983** [comment]
Where is this: "the adjustment that I mentioned to guide for the creation of the new mockups."?  Is that a wiki or an email that I overlooked?

We talked in the October 10 meeting about a mid-November demo release and this is November 15 now.  I jumped on this a bit to get more things ready for release but I guess that's rushing things.

**Comment by Blandine-AA** [comment]
@joshi1983 , see the description of this issue... second line says "Adjustments", and I provided 2 adjustments.

Yes, you are rushing things out, as this work was assigned to prince, but if you want to take it over and do the mockups, because you want more things ready for the release, you are welcome to do so.

**Comment by joshi1983** [comment]
I read all of this issue's comments before commenting and that didn't answer the questions that I asked and left me with the impression that you were more happy with the 2016 mock ups than what was agreed in last Friday's meeting.

Anyway, I won't take this from Prince and will find some other issues to work on.  I want to stay involved with the design decisions because we can make better decisions as a team and with productive debate on areas of disagreement.  I'll try not to worry about when we're releasing until we happen to be ready to do so.

**Comment by Blandine-AA** [comment]
@joshi1983,  If I was more happy with the old design, I would just have said so, but I specifically mentioned the adjustments that were needed and had a task list to provide new mockups. Also, we had a discussion at the last meeting on the new design and for specific work to be done and assignments of who would do what.

I completely agree with discussion group, but it doesn't have to happen in a flash. No need to be stress people here! So, if you can find other work to do and just worry about that, that would be great!

My job is to manage the release and you shouldn't worry about that :) .

**Comment by princeseth** [comment]
Followings are the mockup for mobile devices or small screens.
1. When user click/hover on the horizontal bars, accessibility criteria menu will expand (with categories name arranged alphabetically)
![mobile2](https://user-images.githubusercontent.com/25910292/33296308-d61252be-d3a8-11e7-93ce-6b1e00e22243.png)

2. When user select particular accessibility criteria (say Amenities), each question under that category will be displayed as link
![mobile1](https://user-images.githubusercontent.com/25910292/33296380-50d4a3d0-d3a9-11e7-9965-304763afeb8c.png)

3. On selecting/clicking particular question (or link), the rating options will get open below each question for the users to rate.
![mobile3](https://user-images.githubusercontent.com/25910292/33296448-be9e6022-d3a9-11e7-8261-368fd5256b8e.png)


@Blandine-AA @joshi1983 Please share your feedback and let me know if any changes are required or if I missed any requirement. Thanks.!

**Comment by Blandine-AA** [comment]
Great work @princeseth !
A couple of comments:
1- the Submit button is missing. I think it should be added to the left side of the Rate button
2- Josh mentioned that hyperlinks don't work well with screen reader. So remove it and we will just have to show the answer options right away for each accessibility criteria. It will take more space, but it is fine as the user can scroll down a far as he wants.

**Comment by Blandine-AA** [comment]
Tested this as part of #463 and it is working well. 
The issue with the submit button will be discussed with #476.
PASS
