### ISSUE TITLE
Location Rating : New layout of the page for mobile devices and small screen size

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#410]
This is to track the work to for the new layout of the Location rating page. 
Provide a mock-up proposal for the overall page as discussed at the Nov 10, 2017 meeting. 
See issue #409 for the changes required to the accessibility criteria/questions layout.

**Comment by joshi1983** [comment]
@Blandine-AA can you specify what is remaining on this?  You mentioned this needs to be completed before a demo release.  Some changes were made to make the rating feature look ok on mobile devices.

**Comment by Blandine-AA** [comment]
Some issues with small screen size layout that were discussed but that seem to be missing in the existing issues.
- [ ] create an info menu or button to hide the address,  url and other informations that are currently fully displayed on small screens:
![image](https://user-images.githubusercontent.com/20052162/34965823-1bc4240c-fa25-11e7-8c5b-af546e0e9485.png)
- [ ] On screen capture above, location name is way too small. Needs to be more visible

**Comment by Blandine-AA** [comment]
PASS
