### ISSUE TITLE
Location View: use icons for location categories when screen is too narrow for full names

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#430]
During the November 10 meeting and in Yashankit's iphone testing report from #399, we noticed that location category names took too much space.  When insufficient space is available for the full names of each associated location category, we want to replace that text with icons.

When the icons show, we want the hover text to be the full name for each tag to give screen readers text to read and anyone having difficulty interpreting the icons.

Use vector graphics for the icons.  The best choice for now is probably Font Awesome.

Here is Yashankit's screenshot from his iphone with some red drawing attention to the location categories:
![image](https://user-images.githubusercontent.com/11838191/33233265-05d54b6a-d1e1-11e7-8e94-42c96403634d.png)

**Comment by joshi1983** [comment]
I added the icons and this is ready for testing now.

Here is an example of how the icons look:
![image](https://user-images.githubusercontent.com/11838191/33233488-91313734-d1e4-11e7-9c48-528cef321ca1.png)

For checking these changes, I suggest:
1. Go to a location's report that has a lot of categories such as [Devonshire Mall](http://app.accesslocator.com/location-report/30).
1. Resize the width of the browser down narrow enough where the buttons would otherwise wrap to a new line and see how the icons appear.
1. Check a couple other locations and see how the icons show for them.

**Comment by yashankit17** [comment]
[TESTING REPORT.pdf](https://github.com/hhaccessibility/hhaccessibility.github.io/files/1516415/TESTING.REPORT.pdf)
Please see the attached report of testing these modifications.

**Comment by joshi1983** [comment]
I couldn't reproduce the Universal/Personal wrap problem in Chrome on my laptop but I'll try that on an Android phone and see what might be doing that.

**Comment by Blandine-AA** [comment]
@yashankit17 , great work with the testing.

@joshi1983, beside the refreshing suggestion  for the Universal and Personal buttons overlap, the other issue is the overlap of the accessibility info window on the map. My initial suggestion is to have the info window below the map. I am curious to see what google map looks like on a smartphone for a location.

**Comment by joshi1983** [comment]
@Blandine-AA we'll definitely need to stack the question categories above or below the map on narrow viewports.  I'm a little more in favour of having the question categories above the map because that'll make it quicker to see.  The user may need to scroll to see all the content on really narrow screens and the map may be better to cut off than the accessibility ratings.

#325 might be a better place to discuss the mobile overall layout of that page.

**Comment by yashankit17** [comment]
@joshi1983  yeah issue related to icons was resolved when i refresh the window using CTRL+SHIFT+R
and that universal and personal button overlapping problem is only on iphones.

**Comment by Blandine-AA** [comment]
Then we will need to track the issue for iphones only.

**Comment by joshi1983** [comment]
@yashankit17 can you test this again on your iphone to see if "Universal" and "Personal" overlap each other still?  I'm not sure how you would thoroughly refresh but try to clear the browser cache if possible.

I deployed some changes that might have fixed it.  I wasn't able to reproduce the problem exactly but there it may have come from the iphone rendering some text for the Universal and Personal buttons a few pixels wider than the same text on a laptop.  If that's what happened, I implemented a couple things that should fix the problem.  I expanded the width of a containing element by 10 pixels and indicated that we don't want the elements to wrap to new lines.

**Comment by joshi1983** [comment]
Yashankit tested again and it looks fine.  Here's a screenshot from him:
![image](https://user-images.githubusercontent.com/11838191/34320858-749476fc-e7d0-11e7-9f27-3f9603ccf1a6.png)

I'm closing this because all issues brought up while testing have been resolved.
