### ISSUE TITLE
Research access.earth

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#437]
Learn about http://access.earth and how we might be able to use its data in AccessLocator.
- How many locations do they have?
- What accessibility information do they maintain on each location?

It may be useful to add a new import tool for it using Python and copying some of their accessibility information.  

It looks like the data source the following criteria is maintained by them which should answer some of our criteria questions:
- Accessible Parking
- Step free entrance
- Wide doors available
- Primary functions accessible
- Wheelchair restrooms
- In-room Accessibility
- Roll-in Shower

**Comment by M4ttoF** [comment]
I'll start researching it

**Comment by joshi1983** [comment]
Matthew's work was merged.  I'm closing this without any third party testing from someone like Neha because there is nothing she can test for it.  The tool isn't available on https://app.accesslocator.com and none of the data from the tool was included there.
