### ISSUE TITLE
Location Search: bind ENTER key to "Update" radius button

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#444]
Yashankit suggested to let the ENTER key be another way to update the location search radius on the spreadsheet view.  This seemed like an improvement to me too.

This would involve some JavaScript changes in public/js/location_search_table.js.

**Comment by joshi1983** [comment]
This is ready for testing.  The suggested test instructions are:
1. Go to home at http://app.accesslocator.com/
1. Click a location category/tag button like 'Restaurant'.
1. In the location search, thoroughly refresh the browser to clear cache.  This might be something like CTRL+SHIFT+R
1. Adjust the radius to something like 0.5 and with the cursor still in the radius input hit ENTER key instead of clicking the 'Update' button.
1. See that the ENTER key reloaded the page with the updated radius.

**Comment by princeseth** [comment]
I have verified this functionality, it is working as expected. The page gets reload and fetches new result with the ENTER key.

**Comment by joshi1983** [comment]
Thanks Prince.  I'll close as Prince found that this is working.
