### ISSUE TITLE
Profile: Province doesn't save

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#451]
@yashankit17 discovered a bug where the province doesn't save in the user profile.  This needs to be fixed.

**Comment by joshi1983** [comment]
Yashankit discovered this problem while using an iphone but it was reproducable in Chrome on a laptop so this should be testable for any device.

Here are some testing instructions:
1. Sign in.
1. Update State/Province to something different like Quebec.
1. Click out of it to make the "Save" button active at the bottom of the page.
1. Click the "Save" button.
1. Notice that the new Province or State is shown correctly in the input field.
1. Reload the page and notice that the Province or State is shown correctly in the input field.

**Comment by princeseth** [comment]
I have tested this functionality by adding and updating the province field. It is working as expected.

**Comment by joshi1983** [comment]
I'll close as Prince says it is working.
