### ISSUE TITLE
Turn criteria into the form of questions

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#453]
The criteria is written as statements for now.  These need to be reworded in the form of questions.

This shouldn't change the meaning of the features.  This would just make the "Yes" "No" answers more intuitive.

Attaching a Word or PDF document with the reworded questions would be a good way to hand this work to a developer who can copy it into the project's files for deployment to app.accesslocator.com and eventually to demo.accesslocator.com.

This is essentially an update to the question list that was "finalized" in #31.

**Comment by joshi1983** [comment]
Blandine said she'll work on this so it is assigned to her.

**Comment by joshi1983** [comment]
@Blandine-AA was this planned to be complete for Monday, January 15?  Is anything blocking you?

Just a reminder that you can modify the original criteria list and send me the new version with the question text.  That'll be enough for me to make the next steps to get those questions on app.accesslocator.com and ready to deploy to demo when the time comes.

**Comment by Blandine-AA** [comment]
[Accessibility Criteria Questions_FINAL-updated-29Jan2018.pdf](https://github.com/hhaccessibility/hhaccessibility.github.io/files/1675390/Accessibility.Criteria.Questions_FINAL-updated-29Jan2018.pdf)

**Comment by joshi1983** [comment]
@Blandine-AA was this cleared up?  Was that question answered for the person who got confused by it?

![image](https://user-images.githubusercontent.com/11838191/35780108-de13547c-09a4-11e8-91c7-e914de74405e.png)

**Comment by joshi1983** [comment]
@Blandine-AA is "Is there a ramped or ground level access at main entrance?" from the Entrance question category a duplicate of "Are the curb cuts/ramps even with the paved surface/road?" in Parking?

**Comment by Blandine-AA** [comment]
@joshi1983 it is not the same question

**Comment by joshi1983** [comment]
The questions were copied but there is some sophisticated relationships between questions being applicable, location categories, and answers to other questions that Blandine asked for and I'm still implementing.

**Comment by Blandine-AA** [comment]
@joshi1983, the relation ships were not a priority for 0.0.5 as the document is not validated yet. I had sent them for review to both you and @stephanosm, and haven't heard any feedback yet.

**Comment by Blandine-AA** [comment]
See latest update in #504
