### ISSUE TITLE
Profile: Clean up misleadingly non-functional Rewards

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#454]
The profile page has some references to a Rewards Program and some trophy icons.  These did nothing since they were added in 2016 and will continue to not work for the foreseeable future.  They were originally added to show that we eventually wanted to make them represent rewards for rating locations or similarly beneficial tasks for AccessLocator but this won't happen for at least another 6 months.  We may bring this back in several months but it'll be better to hide them now and bring them back when it fully works than let this confuse testers in spring.

Here is a screenshot to illustrate:
![image](https://user-images.githubusercontent.com/11838191/34070486-40c448ac-e235-11e7-8481-54d4174ab1f7.png)

This issue includes the following changes:
- [x] Rename the "Reward Program" to "My Reviews".
- [x] Remove the trophy icons and "My Rewards:".

**Comment by joshi1983** [comment]
Mi Sook's changes are merged.  This is ready to be tested.

**Comment by remnantmisook** [comment]
![fix454_screen](https://user-images.githubusercontent.com/34175103/34450330-3f9c4f66-ecbb-11e7-9511-58ab243dc032.PNG)
It should look like this.

**Comment by Blandine-AA** [comment]
Looks nice... 
- [ ] Change "Locations Added By Me" to "Added Locations"

**Comment by joshi1983** [comment]
I merged a rewording of the title for the "My Added Locations" page so it looks like this now:
![image](https://user-images.githubusercontent.com/11838191/34969757-5ee3141e-fa3e-11e7-8d5e-bfb9db71dfb5.png)

**Comment by Blandine-AA** [comment]
Testing: PASS
