### ISSUE TITLE
Location: create a feature for updating existing locations created by the current user

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#460]
Add a feature for modifying existing locations created by the current user.  This may eventually apply to all locations but we can start it restricted to locations added by the current user.

This new feature should be similar to the location add feature from #386 but not allow the user to move the marker on the map.
 
Since this feature would work even after ratings are given by other users, we don't want the user to change the location to something completely different.  Locking the longitude and latitude in place would prevent such a complete change that makes old ratings misleading.  For example, imagine if the user could move the location from a McDonalds to a YMCA several blocks away and have ratings from other users move from McDonalds to YMCA.

**Comment by joshi1983** [comment]
I stopped working on this because Blandine clarified that there's more important work in the Demo Release version 0.0.5 milestone instead.   I don't have any unmerged changes on this.

**Comment by joshi1983** [comment]
This is ready for testing.

The new feature can be viewed by:
1. Sign in at https://app.accesslocator.com.
1. CTRL+SHIFT+R to refresh cache and completely load any JavaScript changes.
1. Click "My Locations"
1. Click "+" to add a new location.
1. Fill out the information on a new location.  Play with the various requirements from #386.  Clicking on the map to move the location and update the address automatically is one key requirement.  The location name should also automatically select location categories and a group especially with correctly spelled franchise names like McDonalds.
1. Click "Add".
1. After creating the location, go to edit it.  The location edit feature can be found in the list of locations you created and under the new "Update" button available on the location report.
1. The edit feature should be very similar to the location add feature except it shouldn't let you move the location.  It lets you update the address in case a street name was spelled incorrectly but it shouldn't let you move the point on the map.

**Comment by singlaneha2205** [comment]
@joshi1983 I tried testing the issue. But I could not locate the update button on the edit location page. Please find below the screenshot of the edit location screen.
![untitled](https://user-images.githubusercontent.com/40703592/43535324-a4d6f35c-9587-11e8-8e04-b971e2615aa7.png)

**Comment by joshi1983** [comment]
@singlaneha2205 that is the edit feature I was suggesting to find.

I was just describing how to get there.  On the location report, there is an "Update" button available for any locations you created.  If space is limited or there are plenty of buttons in the upper right area, a bug icon will show instead of the word "Update" as shown in this screenshot:
![image](https://user-images.githubusercontent.com/11838191/43536972-02fbee02-958c-11e8-8edc-8fa58af14277.png)

Does that clear up the update button confusion?

**Comment by singlaneha2205** [comment]
Yes I will do the testing ahead!!!!

**Comment by joshi1983** [comment]
@stephanosm I think the icon for a button that updates information was picked because if the information is wrong or incomplete, it is like a bug.  @Henry-Hao is that why you picked the bug icon for suggesting updates?

@stephanosm do you have another icon in mind?

**Comment by stephanosm** [comment]
I wonder though if users understand this. Bug is typically a term used by developers. We will have to test it

**Comment by stephanosm** [comment]
I am not sure, really. We can keep it as it is for now and in a future focus group we need to ask users about this.

**Comment by joshi1983** [comment]
Ok, we'll keep the icon as is for now.

**Comment by joshi1983** [comment]
I replaced the Failed Testing label with Ready for testing because @singlaneha2205 said that things are clear enough for her to retest it.

**Comment by singlaneha2205** [comment]
@joshi1983 I tested the issue with above instruction and they are working as expected. We can go ahead and close the issue

**Comment by joshi1983** [comment]
ok, I'll close this because it has been tested.
