### ISSUE TITLE
Location Rating: mobile version of question categories menu needs to keep Rate and View clickable

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#463]
This issue is asking for some polish on recent changes implemented for #410 and #409.  

When the viewport is narrower than 600 pixels wide, a collapsible version of the question category and submit menu is used.

The following screenshot shows the menu with a red line around the Rate and View buttons that can't be clicked while the menu is open:
![image](https://user-images.githubusercontent.com/11838191/34472766-0617800c-ef37-11e7-8892-505c39692db1.png)

The inability to click the Rate and View buttons when the menu is open is counter-intuitive and unfriendly to users.  It the popup has a subtle tint to indicate where a div element overlaps the buttons but this isn't fixing the problem.

This might be related to a problem Blandine mentioned that appeared during a December 2017 meeting with JMCC.  She said there was a problem with the scrollbar in the rating feature.

The menu should be changed so that:
- Rate and View buttons are clickable even while the mobile menu is open.
- If the menu is open, the menu should disappear when clicking the collapse-toggle button.
- Increase the size of the collapse-toggle button to make it easier to click on small mobile screens.  A 20% or 30% increase seems about right.

Be careful not to break the following existing requirements:
- Hovering over the collapse-toggle button should show the mobile menu
- The menu should scroll with the rest of the page.  In other words, don't use CSS position: fixed.
- The hover menu and collapse-toggle button should not show when on laptops.  That feature is strictly for when viewports are under 600 pixels wide.
- On laptops, when the viewport is short(narrow in height), the left menu should stay fixed in position while scrolling through tall question lists.

**Comment by joshi1983** [comment]
This is ready for testing.  I tried it with an Android phone and laptop.

This could be tested by:
1. Sign in on http://app.accesslocator.com either on a mobile phone or in a web browser narrow enough to show the menu icon.
1. Open a location and go to a specific question category.
1. Click on the menu.

**Comment by joshi1983** [comment]
@Blandine-AA can you test this?  Also, try to decide if #410 is done.

**Comment by Blandine-AA** [comment]
@joshi1983 This functionality looks nice on small screen and even on my new old Android phone :). The only problem I have is the submit button position with the categories. But this can be discussed with #476.
PASS
