### ISSUE TITLE
Move updated questions data into the application

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#489]
In #453, Blandine adjusted some of the questions.  Added a few new ones, and reworded some existing ones.

This issue will make that new data available in AccessLocator's seed data and update scripts such as importers/utils/json_to_db.py to bring the updates to app.accesslocator.com and eventually to demo.accesslocator.com.  Migrating existing data such as answers is optional.

**Comment by joshi1983** [comment]
This is ready for testing.

For testing, I suggest visiting both the profile and rating features on http://app.accesslocator.com and comparing the questions with the ones in https://github.com/hhaccessibility/hhaccessibility.github.io/files/1675390/Accessibility.Criteria.Questions_FINAL-updated-29Jan2018.pdf.

**Comment by Blandine-AA** [comment]
- [] Remove bold
![image](https://user-images.githubusercontent.com/20052162/35871165-888ae2de-0b31-11e8-8a47-be648f739fe3.png)
- [ ] Add space between "access" and '(' in 3rd question
- [ ] Make the contents in brakets bold to be consistent with the Entrance category
![image](https://user-images.githubusercontent.com/20052162/35871514-756384e4-0b32-11e8-9902-b91be28d0116.png)

**Comment by Blandine-AA** [comment]
See latest updated file in #504

**Comment by Blandine-AA** [comment]
PASS
