### ISSUE TITLE
Write survey questions and outcomes for focus group testing sessions

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#498]
Make proposal for survey.  This will need to be complete by the end of March.

This has been moved to be done for focus group starting with release 0.0.5

**Comment by joshi1983** [comment]
A couple questions I'd suggest are:
- What change to AccessLocator would convince you to share it with your friends?
- If you were planning a trip to a new city or new restaurant, would you use AccessLocator?  Why or why not?

**Comment by joshi1983** [comment]
@stephanosm from the meeting, you said you wanted to come up with these questions.

You also mentioned wanting to give some goals.

**Comment by Blandine-AA** [comment]
We would need to have these for June 1rst. See 30/60/90 days plan for some cues

**Comment by Blandine-AA** [comment]
@stephanosm, this is the one you are supposed to work on :)

**Comment by joshi1983** [comment]
June 1 is tomorrow.  Will this be ready?

**Comment by stephanosm** [comment]
The survey is sent by email to all participants

**Comment by joshi1983** [comment]
Can this issue be closed?  @stephanosm emailed everyone the survey questions over a month ago.  Is there any work remaining on this?

**Comment by joshi1983** [comment]
I'm closing this because the focus group meetings happened already so this obviously got completed.
