### ISSUE TITLE
Need examples and detail explanation for criteria questions

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#503]
- [x] Ask JMCC to provide examples and more explanation to criteria questions. (Blandine)

Implementation (Josh)
- Amenities
- [x] Are assisted listening devices available?
Examples of assistive listening devices are: amplified telephones which have volume control for both the ringer and the handset,  and wireless headsets which allow for individual sound amplification in theatres, auditoriums or museums. The availability and use of a microphone and speaker system for all public announcements/presentations can also be considered an assistive listening accommodation.  

- [x] Is ceiling track/mechanical lift available in the medical/doctor office?
Ceiling track/mechanical lifts are used to lift individuals into and out of their wheelchairs. A sling, positioned under the client is required to be used in conjunction with the ceiling lift/mechanical lift. Electric lift units need to be charged and in good working order in order to be effective. 

This is related to #506

**Comment by Blandine-AA** [comment]
@joshi1983 , I got the answers for the 2 questions we had identified and updated the issue description.

**Comment by joshi1983** [comment]
There is another question "Is a ceiling track lift available?".  Should that be explained too, @Blandine-AA?

**Comment by Blandine-AA** [comment]
@joshi1983, Not for now.

**Comment by joshi1983** [comment]
I made a rough version of this available for now.

It doesn't look great but it should be screen-reader-friendly and provides the examples.
![image](https://user-images.githubusercontent.com/11838191/36574544-34e06970-1814-11e8-8269-66df67c1659b.png)

I wanted to give some bread crumbs for navigating back to the location rating feature but didn't quickly see a way to keep it looking really good.  I was considering to keep the question categories list available as if the question explanation was just part of the rating feature but didn't want to put that effort in until getting more feedback.

Should the explanation be made available from the "View" or from the user profile?  The same confusing questions appear there and if the user gets confused by them, it may help to give them a way to see the examples and explanation.

**Comment by Blandine-AA** [comment]
@joshi1983 Can this just show as a popup info window when you click on the eyeball, with and [x] to close?
I don't want us to spent a lot of time on this for now.

**Comment by joshi1983** [comment]
Yeah but the popup may not be detected by screen readers.  I'll add a popup like you suggest for the majority of users that haven't indicated that they're using screen readers.

The separate page would be available when the user checked "use screen reader" in the user profile so we still help their experience.

**Comment by Blandine-AA** [comment]
We need to review ![ this design](https://user-images.githubusercontent.com/20052162/36863090-b9ef16ec-1d56-11e8-9985-63384f77d090.png)

Also the display is the same whether I select screen Reader in my profile or not

**Comment by joshi1983** [comment]
I made it so the separate page shows for users who indicated that they use screen readers.

A dialog now shows for every other user.

This is ready for testing.  To test, I suggest seeing all the changes by going through:
- User profile
- Location rating(Rate) on a specific question category
- Location report(View) on a specific question category

and view those with "Use screen reader" saved as checked and unchecked.

**Comment by Blandine-AA** [comment]
PASS
