### ISSUE TITLE
Framework to provide information and/or example for accessibility criteria

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#506]
To help the user understand the questions, we need to provide some details and examples if possible. JMCC would like this to appear as “eye” icons that provide more information when clicked on.
the other design option is to just make the question a link to a popup window that provide more option.

The question is which one, eye or link, is screen reader friendly?

Implement the framework and add details for a couple of criteria in release 0.0.5. See #503 .
The other criteria information will be added in future releases as we received them and new issues will be created to track the work.

**Comment by joshi1983** [comment]
If you want little links to more detail, here are a few that follow your idea of eyeball-like icons.

![image](https://user-images.githubusercontent.com/11838191/36238009-afb2c028-11cd-11e8-9e84-75d1de24339f.png)

The links before the question text:
![image](https://user-images.githubusercontent.com/11838191/36238042-e4a5bb5a-11cd-11e8-899b-fb25494b0988.png)

120% the above size:
![image](https://user-images.githubusercontent.com/11838191/36238086-386e5fd0-11ce-11e8-9f4e-e19435c80c65.png)

We can have text like "See examples" that screen readers would read and that appears on hovering over the eyeball.

**Comment by joshi1983** [comment]
@Blandine-AA what do you think of the above screenshots?

**Comment by Blandine-AA** [comment]
@joshi1983, I like the eyeball icons in front of the questions as they look like bullet points. But for now, since we don't have all the details, I am not sure if it is best to use them on all the questions by default.
The most logical from a UX perspective is to have the eyeball after the question. 
In any case,  it should only be used for the questions that we have extra info on.

**So, for now is to have the eyeball icon ONLY after the 2 questions with have detail information on. We will add the others as we get them.**

I am also ok with your suggestion below, as long as it works for the screen readers.
> We can have text like "See examples" that screen readers would read and that appears on hovering over the eyeball.

**Comment by Blandine-AA** [comment]
Need to redesign how the information is displayed/presented to the user. Moving this to 0.0.7 for now

**Comment by joshi1983** [comment]
An example and explanation feature is implemented and no clear requirements were given for the redesign of this.  This won't be worked on until more feedback tells us that the example and explanation feature is problematic or there is a specific way it can be improved.

For these reasons, I'm closing the issue.
