### ISSUE TITLE
Location Comments

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#515]
For now, the location report has a way to view comments but it is suitable for less than 10 or so comments and it is specific to a question category like "Amenities" or "Elevator".

Here is a comment shown in the feature we currently support:
![image](https://user-images.githubusercontent.com/11838191/36538527-db78a0fe-17a1-11e8-8d98-83da098ccadd.png)

Also, the commenting feature we have is specific to a question category.  This new commenting feature will include comments associated with all the question categories.

Here is a mockup of how this new location comment report could look:
![image](https://user-images.githubusercontent.com/11838191/36623609-2b70a632-18d4-11e8-8faf-595e5a37448b.png)

This new feature would be inaccessible to the end user immediately after completing this issue but the navigation will be added by work from someone else on another issue.  Eventually, this will be referenced from https://user-images.githubusercontent.com/20052162/32290777-75954ff0-bf11-11e7-94c1-258a3948c8dd.png

Here is a breakdown of the requirements:
- [x] Create a feature for listing all comments for a specific location.  Let the location name be a link to the main location report page that has the map and popup.
- [x] Order the comments primarily by question category, secondarily by date such that latest comment is at the top.
- [x] Add subheadings for each question category as you go through them.

**Comment by Blandine-AA** [comment]
Moving this 0.0.6 for now, until we make more progress on 0.0.5

**Comment by joshi1983** [comment]
@Blandine-AA is the "All Comments" link from #244 which is part of demo 0.0.5 milestone being chopped from the #244's scope or should that issue be moved to milestone 0.0.6 too?  This issue is part of implementing your mock ups in https://github.com/hhaccessibility/hhaccessibility.github.io/files/1741955/Location.report.web.page.changes.pdf.

**Comment by joshi1983** [comment]
I discussed this in person with Blandine and we decided to keep it in our current milestone but reduce scope of the issue to just showing all comments without any paging.  I updated the issue description, subtasks, and the mockup accordingly.

Also, @remnantmisook do you think a week is enough time for you to complete this?  I will be too busy with other things from the 0.0.5 milestone to come back to this until around March 4 but do you think you'd find enough time before then.  If you don't finish everything but get some type of dump of the questions by then, that would help and I can take over where you stop.

We're trying hard to get all work marked with milestone Demo 0.0.5 complete by March 15.  The last part of March would be a good polishing period before a big demo.accesslocator.com release is made.

**Comment by Blandine-AA** [comment]
@joshi1983, @remnantmisook, added P1 label for this to be fixed within the next week.

**Comment by joshi1983** [comment]
This was merged and deployed to app.accesslocator.com.  Thanks @remnantmisook.

It looks good to me but this won't be easy for other people to test until it gets integrated with navigation from another issue.  I'll update the popup to include the "All Comments" link.
