### ISSUE TITLE
Make location add feature easier to find

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#521]
In the added locations list, make it more obvious how to add a new location.

A few things to do include are:
- [x] comment on the location add feature when there are no locations in the list
- [x] center the + when there are locations in the list

**Comment by joshi1983** [comment]
Here is a screenshot of how it looks after the change:
![image](https://user-images.githubusercontent.com/11838191/36939135-1453d222-1efa-11e8-8629-f67ad7140255.png)

**Comment by Blandine-AA** [comment]
@joshi1983, the design of the '+' to add a new location is not what we discussed. We could leave it there for now if the functionality works as expected, but we will need to create another issue to redesign this page in 0.0.6 and have a proper icon to add locations.

**Comment by joshi1983** [comment]
If you can mock up the design, that would help match what you want.  I don't remember us talking in great detail beyond "make it clearer for the user to find it".  If there's some specific differences between what we discussed and what I did, I can implement those quickly enough.  Saying there's differences but not saying what they are doesn't push the work forward very well because I implemented everything I could remember.

**Comment by Blandine-AA** [comment]
@joshi1983 , the design we discussed was to have the '+' sign in a blue circle. Similar to what you see in other apps!

**Comment by joshi1983** [comment]
@Blandine-AA I switched to the blue circle just now so it looks like this:
![image](https://user-images.githubusercontent.com/11838191/37207504-5a655bc6-236b-11e8-894e-a7182f34246a.png)

I know it wasn't as high priority as other things but it was really quick to make the change.

**Comment by Blandine-AA** [comment]
PASS
