### ISSUE TITLE
AL News: update web page with link to The MediaPlex article

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#526]
Here is the link: http://themediaplex.com/new-windsor-app-is-like-tripadvisor-for-people-with-disabilities/

**Comment by joshi1983** [comment]
@Blandine-AA Where should that link be added on the page?

Does it belong in "History"?  How did you want the reference to the article worded?
![image](https://user-images.githubusercontent.com/11838191/37206840-4396efd4-2368-11e8-91f8-192b3840d261.png)

**Comment by Blandine-AA** [comment]
@joshi1983, how about adding a new tab called "News", where we put all the articles ever released on AL. the most recent one being at the top.
The first section of the article should be visible and then "Read more..." to open the article out of AL.

What do you think? Is this complicated to implement?

**Comment by joshi1983** [comment]
It should take an hour at most to do.  I guess we'd also want to mention the original Hacking Health event, the event in Toronto, and the Mini Maker Faire.  We can check if the problem we pitched from the January 2017 hackathon got publicized anywhere.

Giving links wouldn't be enough to fill a page with content and look good.  We'd probably want screenshots of the articles and a paragraph explaining the context of each publicized event.

**Comment by joshi1983** [comment]
I added this article, the Digifest 2017, and 2016 Hackathon.  All of them have images and I tested with narrower viewports to simulate what a mobile phone should see.  I made each link look similar to the boxes in release notes so there'd be more consistency.

The top of the page looks like this:
![image](https://user-images.githubusercontent.com/11838191/37382218-eeba92d2-2717-11e8-9fd6-203e530d9cf2.png)

This can be tested by going to http://accesslocator.com and navigating to the "News" section.

**Comment by stephanosm** [comment]
@joshi1983 it looks great. 
One suggestion is to replace the link and blurb about Feng. The reason is that it links to her Linkedin profile and it is empty (no connections). Perhaps add some blurb linking either to: http://themediaplex.com/new-windsor-app-is-like-tripadvisor-for-people-with-disabilities/
 or/and to the actual video that shows you talk about AL.

**Comment by joshi1983** [comment]
I emailed Feng asking if she can add more detail to her linkedin profile.  If she doesn't add sufficient detail in a couple weeks, I'll unlink her profile.

Yeah, I could also mention you(@stephanosm) joined and a few others we met there.  I introduced Abdulrahman Alrifai to the project who had some ideas on how to get funding.

**Comment by Blandine-AA** [comment]
@joshi1983, this is a news section. Just to show the articles. Please just leave it as is. No other links to be added except for the article one.

**Comment by Blandine-AA** [comment]
Pass - This page will be reviewed later anyway!
