### ISSUE TITLE
Investigate the Multilanguage support from Google

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#532]
I saw this on the Windsor Essex Immigration website
![image](https://user-images.githubusercontent.com/20052162/37259224-f71f1a20-2559-11e8-9cd6-dc6fc107f3e8.png)

Click on the arrow here: https://www.welcometowindsoressex.ca

**Comment by joshi1983** [comment]
I'm very confident this isn't something we want worked on any time soon.  
- We're focused on the Windsor and English-speaking part of North America for now. 
- We're focused on disability-related accessibility.  Not language-related accessibility.
- People can use website translators on any website without us adding a feature for it.
- It would be an extra thing for screen readers to read to people and an extra thing for people to look at when they'll hardly ever use it.
  
For these reasons, I'm closing this issue.
