### ISSUE TITLE
Sign in with Facebook is broken

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#537]
![image](https://user-images.githubusercontent.com/20052162/37780101-66a4ee2a-2dc4-11e8-83eb-e7da3c051b0a.png)

**Comment by joshi1983** [comment]
@brucelau-github were you looking at this a month or 2 back?

**Comment by brucelau-github** [comment]
related to issue #542

**Comment by brucelau-github** [comment]
I have fixed them. The dependency hybridauth is broken.

**Comment by Blandine-AA** [comment]
PASS
