### ISSUE TITLE
Sign-up or sign-in is broken?

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#542]
It looks like sign-up or sign-in is broken.
I was doing a demo today and the user could sign-in after she created he account and validated her email. I didn't have time to test it my self. I was wondering if Ruby can test this and document the steps and what she observes?

**Comment by Blandine-AA** [comment]
@joshi1983 tested the Sign-in with an existing account and it works. I guess it is the Sign-up that seems to have a problem.

**Comment by joshi1983** [comment]
@Blandine-AA I fixed something and think this is working on app.accesslocator.com now.  It looked like the email verification step was broken.

**Comment by joshi1983** [comment]
I'm closing because Blandine said this was working.
