### ISSUE TITLE
"Rate this app" feature

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#545]
For people to easily evaluate the app and provide specific feed, During the May 15 status meeting, it was suggested to have a feature that would allow the user to rate the app. This feature would be a very simple survey, 5 questions at the most, that the user can complete in 1 minute or less.

Example of questions:

1. Do you use AL? Y/N
1. If you use AL, how often? ... provide a choice of answers
1. Do you like AL? Y/N
1. Would you recommend AL? Y/N

**Comment by joshi1983** [comment]
Maybe you can make a survey in [Survey Monkey](https://www.surveymonkey.com) and I can link to that.

**Comment by stephanosm** [comment]
Isn't this what I am supposed to do?
Also, I suggest the first 2 questions to be slightly different because of the expected number of focus users. Perhaps:
1. Have you ever used the AL app before?   Y/N
2. If you have, how many times (approximately)  - provide some groups.

**Comment by Blandine-AA** [comment]
@stephanosm, this is not the Focus Design work as discussed at the May 15th meeting. Look at the one assigned to you :)

**Comment by stephanosm** [comment]
ok, thanks for clarifying!

**Comment by joshi1983** [comment]
Who will write this survey now?  Should it be @stephanosm?

Also, like I suggested 21 days ago, Survey Monkey should be good for this.  You can sign up for an account at no charge and collect results from there.  https://www.surveymonkey.com/user/sign-up/

**Comment by M4ttoF** [comment]
I created a sample survey using surveymonkey
https://www.surveymonkey.com/r/2SZ98H7
Let me know if you would like anything changed

**Comment by Blandine-AA** [comment]
@joshi1983, no objections.

**Comment by Blandine-AA** [comment]
Great work @M4ttoF ! Survey questions are ok.

**Comment by joshi1983** [comment]
@PravinaBhatt can you add a link to Matthew's survey ( https://www.surveymonkey.com/r/2SZ98H7 ) from the contact page?

**Comment by PravinaBhatt** [comment]
Yes, I can do it.

**Comment by joshi1983** [comment]
@PravinaBhatt thanks.  It looks good to me.  @singlaneha2205 what do you think?

To test, I suggest these steps:
1. Go to https://app.accesslocator.com/contact
1. See that the link looks good and understandable.
1. Click the link and see that the link navigates to Survey Monkey.

**Comment by singlaneha2205** [comment]
@joshi1983 I tested the above and is working as expected. I was able to navigate to the survey and was able to complete the survey. I think we can go ahead and close the issue.

**Comment by joshi1983** [comment]
@M4ttoF did you receive our survey answers on Survey Monkey?

**Comment by joshi1983** [comment]
Matthew shared some information on how to access the survey data by email.  I'll close this issue as it has been tested by @singlaneha2205 and passed.
