### ISSUE TITLE
Location search error message on demo

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#555]
@stephanosm ran into a bug.  I quoted what Stephanos shared with me.

"I rated Starbucks and then I went to Home to find Starbucks again to see what is total Accessibility but got an error msg."

![image](https://user-images.githubusercontent.com/11838191/40893770-3f066f00-6772-11e8-9f9b-727693abd8ca.png)
"That happened when I clicked the Restaurant button"

**Comment by passionInfinite** [comment]
@joshi1983 assign this to me. I will resolve.

**Comment by joshi1983** [comment]
@passionInfinite there's 2 issues assigned to you but not yet fully ready for testing, though.  There's a pull request with feedback waiting for your attention and a couple lingering steps to #523.  I'll assign this when you have less on your plate.

**Comment by Blandine-AA** [comment]
I had a focus group this afternoon at ALSO and few uses got this error while trying to find Tim Horton as specified on the survey. It was bad :( !

**Comment by joshi1983** [comment]
Correct me if I'm wrong but you had at least one accessibility criteria selected and were signed in when this bug happened, right?

**Comment by stephanosm** [comment]
So @Blandine-AA  what happened after that? Were users being able to rate something else? Did they finally complete the survey? Please share the details.

**Comment by Blandine-AA** [comment]
Most users were able to complete the survey. But others just gave up as they struggled with either the sign-up or the exception that they kept getting. Not all users had the exception.

**Comment by joshi1983** [comment]
This should be fixed on both app.accesslocator.com and demo.accesslocator.com.

I added several more automated tests in case they help similar problems from coming up again and to help other volunteer developers test their changes.

This problem was related to a stale cache for location ratings. When new questions were added in the latest deployment of demo.accesslocator.com, I forgot to clear the cached ratings.  I added a tool to quickly repopulate the cache so the next deployment goes more smoothly. 

The bug pointed out in Stephanos' screenshot would have been reproduced by this sequence:
1. Sign up for an account or sign into an existing account.
1. Have at least 1 of the new accessibility criteria filled in on the profile.  Using a screen reader doesn't count.
1. Use the location search feature to find locations using the table view.  It would show the error like in the screenshot.

**Comment by M4ttoF** [comment]
Tested and Passed

**Comment by joshi1983** [comment]
I'm closing since this was tested by Matthew after I fixed and tested it a few weeks ago.
