### ISSUE TITLE
June focus group testing: sign-up word not visible and creates confusion

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#567]
During the focus groups, many users didn't see the Sign-up link and went straight to sign-in and they tried to sign in with their email and email password.
The fact that the Sign-in characters are bigger than the Sign-up one creates confusion. Both should be of equal size. 
This was tested on an iPhone.

**Comment by joshi1983** [comment]
That's in reference to the home page, right?
![image](https://user-images.githubusercontent.com/11838191/41314750-a265e89c-6e5b-11e8-8b4c-8bc95551f856.png)

I don't know if there's some kind of optical illusion going on but those are exactly the same size.

**Comment by stephanosm** [comment]
I think she refers to this one:

![image](https://user-images.githubusercontent.com/22602396/41317984-d230d902-6e64-11e8-99ca-6aff9456e862.png)

**Comment by joshi1983** [comment]
The page is focused on signing in, though, so equal sized text would be more confusing.   There's a separate page for Sign Up.

I'm leaning toward replacing the home page's single button labelled "Sign in / Sign Up" with 2 links or 2 buttons.  This would be less work and less content to fit on a screen than if we merge the Sign In and Sign Up into a single layout.

**Comment by Blandine-AA** [comment]
Having 2 separate buttons straight from the home page will be less confusing.

In general, users seemed to be looking for less click to get to the information, and very simple and simplified interface and steps. Something to keep in mind!

**Comment by joshi1983** [comment]
Here is a mockup of what we could go with.
![image](https://user-images.githubusercontent.com/11838191/41347552-0019ef8e-6ed8-11e8-9eea-a8ee14256a02.png)

I think even on the narrowest mobile phone layout, we could still stick with 1 row.

**Comment by stephanosm** [comment]
Looks good but perhaps some more spacing between the 2 buttons. Also, I recommend to "explain" the difference between the 2 having the Sign Up button with something like this  (Warning I am not a Designer  :-) 

<img width="284" alt="signup" src="https://user-images.githubusercontent.com/22602396/41354504-26e3017c-6eed-11e8-9fe4-15c64ac6823e.PNG">

**Comment by joshi1983** [comment]
@Yuanzjls this would involve modifying a couple files:
- resources/views/pages/home.blade.php
- resources/assets/sass/_home.scss

**Comment by joshi1983** [comment]
![image](https://user-images.githubusercontent.com/11838191/41865973-c422ecc0-787c-11e8-86d6-95060ee83008.png)

![image](https://user-images.githubusercontent.com/11838191/41865998-d73eaeac-787c-11e8-9f6c-c1596351c127.png)

**Comment by M4ttoF** [comment]
Issue has been tested and merged, can be closed

**Comment by joshi1983** [comment]
I'm closing because Matthew tested this and says it is good in his opinion.  Stephanos suggested a "New User" icon but that can be done in another issue if these changes aren't clear enough.
