### ISSUE TITLE
June focus group testing: Location field updated with geo-coordinates when doing Search by keyword

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#568]
The user is complaining that:
> After correcting my signing in properly, when I typed in Tim Horton's in Windsor and pressed Search, numbers appeared in the Window where Windsor (or Tim Horton's) had previously been. If I use the "Restaurant" category, info becomes available for multiple restaurants (not Tim Horton's only) within a range of 10 km.

This was tested on an iPhone.

**Comment by joshi1983** [comment]
Having a screenshot would have helped with this.

I suspect the user unknowingly and accidentally clicked the home page's map which changed location.

The location he or she clicked happened to also be 0.5km or more away from the nearest street addressable location so it used longitude and latitude as defined by requirements for #397.

Here's a screenshot of how my suspition could have looked on her phone:
![image](https://user-images.githubusercontent.com/11838191/41459552-e5a2e8e6-7057-11e8-88e6-9023dd119176.png)

**Comment by joshi1983** [comment]
Matthew's changes to make the click on the map more obvious have been merged and deployed at https://app.accesslocator.com/.

Testing should be very simple.  
1. Go to the home page.  
1. Click or touch the map and you should see it blink.

**Comment by singlaneha2205** [comment]
@joshi1983 and @Blandine-AA I tested the above issue and it worked as expected. We can go ahead and close the issue.

**Comment by joshi1983** [comment]
I'm closing this as it was successfully tested.
