### ISSUE TITLE
June focus group testing: Data analysis meeting

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#569]
@stephanosm , @joshi1983 ,

Can we meet sometimes this week to go through the survey answers?
I have early morning or lunch time for Wednesday June 13th and Thursday June 14th. I can also do Thursday June 14th around 5 pm

Location : Either at JMCC or at the Tim Hortons on University.

**Comment by stephanosm** [comment]
Too short of a notice for Tomorrow or Thursday. Tomorrow I am available only any time between 4:30-7:00pm, but not Thursday. Friday I have time between 11:30-12:30. Else we can meet next week which I have more availability.

**Comment by joshi1983** [comment]
Monday, June 18 at 5:00pm at Tim Hortons near Bruce and University Ave is good to me.

That would be the usual meeting place:
http://demo.accesslocator.com/location-report/00000000-0000-0000-0000-000000000001

**Comment by stephanosm** [comment]
Since Blandine missed the June 18th meeting we are rescheduling it. My and @joshi1983 's availability is:
Next Monday and Thursday at 5:00-6:30pm
Also, on Wednesday at 6:30-7:30pm
@Blandine-AA what's your availability?

**Comment by Blandine-AA** [comment]
I didn't miss any meeting since there was none scheduled on June 18th, only a proposal!
I am available Monday June 25th, from 5 pm to 6 pm. I am ok with the Tim Hortons!

**Comment by joshi1983** [comment]
Monday, June 25, 2018 at 5:00pm at Tim Hortons(http://demo.accesslocator.com/location-report/1) it is then.

**Comment by joshi1983** [comment]
Since this happened and there's nothing to test about it, I'm closing the issue.
