### ISSUE TITLE
Make facebook authentication work

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#57]
This doesn't require a polished UI.  Keep the UI ugly for the sake of getting this implemented with minimal effort since the UX sketches are incomplete for now.

**Comment by joshi1983** [comment]
https://www.youtube.com/watch?v=tx8XZ_t6SbQ seems useful for this.

**Comment by joshi1983** [comment]
I unassigned myself because I might not work on this for a while.  I have a little of it done but everything I did is merged so someone else could continue work on this.

**Comment by joshi1983** [comment]
I assigned to Bruce since he used a pretty generic solution for Google authentication that he mentioned should work for facebook too.  He'd probably finish this faster than I could.  The little work I did with hybrid auth probably should be removed if it doesn't help to make this change.

**Comment by brucelau-github** [comment]
There is a issue while we retrieve facebook user's email.  Users may login facebook by phone number rather than an email address. In this condition, we could not create user profile with empty email address. @joshi1983

**Comment by brucelau-github** [comment]
@areebakamal 
I need a log picture with following format for our facebook application:

- You can upload a JPG, GIF, or PNG file. 
- The size of the image must be 1024 x 1024 pixels. 
- File size limit 5 MB.

**Comment by brucelau-github** [comment]
@joshi1983 do you have a facebook acount? I need it so that I could add you in to application admistrator group of our project. send me an email.
it is ready to merge. It works with my facebook id since I am the developer and users of this application in facebook. Can you try to test it on your machine with your id? I have ever suffered a security problem before when others log in the application.

**Comment by joshi1983** [comment]
I gave Bruce my facebook information in a private chat conversation.

@brucelau-github for the log picture you're asking Areeba about, where would it go or how would it be used?  The button uses an icon.

**Comment by brucelau-github** [comment]
I will be like show a logo on the authentication page.

**Comment by brucelau-github** [comment]
![screenshot from 2017-01-09 18 27 41](https://cloud.githubusercontent.com/assets/22227484/21787818/53f5b0f8-d699-11e6-8c08-7a7a1de948a0.png)
like this one

**Comment by joshi1983** [comment]
Can you use this for now?  It is our current logo.  I just cropped and scaled to make it 1024 by 1024:

![image](https://cloud.githubusercontent.com/assets/11838191/21787973/1b792efc-d69a-11e6-992f-007bde64488c.png)

It has some rough edges and bluriness at 1028 by 1028 but

**Comment by brucelau-github** [comment]
We detected a white background in your image. Icons look best on our site when the background is transparent. Please use a transparent background and try again.

**Comment by joshi1983** [comment]
![transparent_logo_1024](https://cloud.githubusercontent.com/assets/11838191/21788226/6f5835c6-d69b-11e6-8762-99c4d2a9a81a.png)

**Comment by brucelau-github** [comment]
I have submitted this file as the application logo in our application setting menu.

**Comment by brucelau-github** [comment]
![screenshot from 2017-01-09 18-58-08](https://cloud.githubusercontent.com/assets/22227484/21788612/ac05aa6a-d69d-11e6-8c39-9a944ec07672.png)
it works

**Comment by joshi1983** [comment]
That looks pretty good.

**Comment by joshi1983** [comment]
I'm pretty confident facebook authentication is working fine so I'm closing the issue.
