### ISSUE TITLE
Add HTTPS support for demo.accesslocator.com

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#576]
There is some HTTPS support at https://demo.accesslocator.com but it still shows cautionary messages and users have to click "Proceed to ... (not recommended)" to get through it.

Get the SSL certificate working for demo.accesslocator.com.

**Comment by passionInfinite** [comment]
@joshi1983 @Blandine-AA This issue is resolved.
