### ISSUE TITLE
Regarding Coding Style Checking

### ISSUE THREAD

**Issue by passionInfinite** [hhaccessibility/hhaccessibility.github.io#588]
I would like to include the Coding Style Checking with certain rules. As many people are working and we might have problems related to coding style as everyone might be using different editors so the settings might be different.  So I would like to add `PSR-2` styling rules so that everyone can have uniform standards. I won't take much time to include this and it will be beneficial to resolve our coding style issues. It can be added while solving an issue. No need to give dedicated time to it. It will be less work for @joshi1983 by giving comments regarding style issues.

@Blandine-AA @joshi1983 I would like to know your thoughts on these.

**Comment by joshi1983** [comment]
PSR-2 looks like a popular standard but how would it be automatically enforced?  Can it be checked with a PHPUnit test?  Are there extra dependencies to install to automatically test compliance with it?

Also, how would we switch our code base to that standard without impeding people who are in different stages of work on their coding issues?  Can we filter out specific files they're working on until their work is merged?  If a good portion of every file gets modified, many volunteers will struggle to rebase.

**Comment by passionInfinite** [comment]
@joshi1983  We can easily switch to this standard by two commands 1) for checking coding style 2) for fixing the coding style. The second command will automatically fix all the coding style errors of our project. There will be no need to do rebase for volunteers. We just need to merge our work to master and tell them to pull master and merge master into their working branch.

**Comment by joshi1983** [comment]
@passionInfinite what are the commands you speak of?  Are you talking about php-cs-fixer?

**Comment by passionInfinite** [comment]
Yea. We can include that. :)

**Comment by passionInfinite** [comment]
@joshi1983 We are clear with the code styling, right? so we can close this?

**Comment by joshi1983** [comment]
Yup, I'll close it.  This isn't something people can test by using the application.
