### ISSUE TITLE
Issue with the arrow signs on distance field under Search Location section

### ISSUE THREAD

**Issue by singlaneha2205** [hhaccessibility/hhaccessibility.github.io#613]
During testing, I noticed that on Chrome and Firefox in the distance field under Search Location we can see arrows at the end of the field to increase and decrease the value of the distance field. Refer to the screenshot below.
![untitled](https://user-images.githubusercontent.com/40703592/42405271-12bc951a-8161-11e8-8160-eed357c21903.png)

But in IE and Edge, these arrows are not displayed. The user has to manually enter the increased or decreased value.
![untitled1](https://user-images.githubusercontent.com/40703592/42405322-cbf2a0c4-8161-11e8-8ffa-a4203ebde7ea.png)

Please comment on the expected behavior.

**Comment by joshi1983** [comment]
@codemaster94sb do you feel up to doing this?

**Comment by codemaster94sb** [comment]
Yes i will do it.

Sent from my iPhone

On Jul 11, 2018, at 6:15 PM, Josh Greig <notifications@github.com<mailto:notifications@github.com>> wrote:


@codemaster94sb<https://github.com/codemaster94sb> do you feel up to doing this?

**Comment by joshi1983** [comment]
@codemaster94sb did you find the invitation email?  Please accept so I can indicate that this issue is assigned to you.

**Comment by joshi1983** [comment]
I think the best way to handle this would be to remove the Search Location fields completely.  Those fields are confusing and virtually useless on the profile and they add to the clutter of the profile.  We have people complaining about too many questions to answer on the profile and removing those 2 should save it.

**Comment by joshi1983** [comment]
I'm closing this because another issue will resolve it by removing the Search Location feature from the profile.
