### ISSUE TITLE
Refactoring the project to clear bugs

### ISSUE THREAD

**Issue by passionInfinite** [hhaccessibility/hhaccessibility.github.io#615]
I would like to do a refactoring of the whole project within 5 days and after 5 days we can have our bugs fixed. I am listing the things that I will be doing.

- [x] New Authentication System. 

- **CRITICAL:**  will clear the global $user shared everywhere into the system.
- **CRITICAL:**  Also, remove the tightly coupled BaseUser class with some good helpers that can be reuse.

- [x] Profile Module and some clear messages at the right place.
- [x] ProfilePhotoUploadController

- **CRITICAL:** unnecessary functions that should be cleared and use the Single Class Responsibility Principal.
- This will be changed to **ProfilePhotoController** and it will handle only code for profile photo related things.

- [x] Models Base Classes and refactor model to remove unnecessary code that can be done without model.

- [x] Move to second level routes 

- **CRITICAL:** Our whole system uses only one level routes that  will be changed to second level routes with related urls.
- **It is completing as I am fixing and refactoring the modules.**

- [x] Social Authentications

- **CRITICAL:** After doing configuration to the FB developer apps still we are facing the issue so we are going to remove the dependency of HybridAuth as we can do it in more simple way.

- [x] Helper classes
- This will help to use the helper functions as required anywhere without depending on any module.

- [x] HomeController
- This will clean up the unnecessary things in the code which can be done in one line.

- [x] Coding Style Checking
- This will help us to maintain the coding style for everyone who is contributing.

- [x] LocationSearch (Controller and Routes) Module   
- This will clean up the unnecessary things in the code which can be done in one line.

- [x] LocationManagement (Controller and Routes) Module
- This will clean up the unnecessary things in the code which can be done in one line.

- [x] LocationRating (Controller and Routes) Module
- This will clean up the unnecessary things in the code which can be done in one line.

- [x] LocationReport (Controller and Routes) Module
- This will clean up the unnecessary things in the code which can be done in one line.

- [ ] InternalFeatures (Controller and Routes) Module
- This will use the Authorization Concept instead of just checking on the basic things.

- [x] Questions Module (Controller and Routes)
- This will have the proper question routes and logic.

- [x]  Reviews Module (Controller and Routes)
- This will have proper setup for reviews of the location and by done by which user.

- [ ] PHPUnit Testing
- We will have someone who will regularly do the Unit Testing using PHPUnit. I will also contribute in helping people to do the Unit Testing.

All these things will be completed on 14th July (Saturday) at 4:00 pm. So after that, we can have more focus towards the design, front-end side, importer tool and implementing new features rather than continuously fix the issues that are repeating. @Blandine-AA I would like that you keep track of these things I will put the checkmarks as I progress.

**Comment by Blandine-AA** [comment]
Thanks @Hardik!
Well detailed description of the worrk to be done. I don't see any issue with this. Especially that many people are working on the project almost full time. If this makes future work more efficient, then You can go ahead. Please make sure you check with @joshi1983  to clarifiy or understand initial design intends.

**Comment by Blandine-AA** [comment]
@joshi1983 regarding 
> It would be helpful to have someone finish tests for the location rating, profile image uploading, rotation features.

These should be assigned to @singlaneha2205 .

**Comment by joshi1983** [comment]
@Blandine-AA sure.  I added issues #622, #623, #624 to track that work and assigned them to @singlaneha2205.  I also emailed the environment setup instructions to her so she can test her tests.  She mentioned that she wrote automated tests in other languages so she probably just needs a little guidance to write the tests.

**Comment by passionInfinite** [comment]
@joshi1983 @Blandine-AA For now the internal feature is remaining which will be resolved soon. I would like to have @singlaneha2205 to test this manually first then she can start writing unit tests.

**Comment by joshi1983** [comment]
This is being closed because the changes are too far from a mergeable state to be done in any near future.  Being such an internal concern, this also doesn't warrant the effort necessary to get it in any time soon.  Refactoring and code cleanup will be done in much smaller steps without breaking tests or needing to ask other developers to stop working on their feature and bug fixing changes as we go.
