### ISSUE TITLE
Make Sign in look like UX sketches

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#62]
This work is likely to involve:

- adjusting content in hhaccessibility.github.io\app\resources\assets\sass\app.scss
- running gulp to generate the css
- and adjusting mostly HTML content in hhaccessibility.github.io\app\resources\views\pages\login.blade.php

Don't worry if the form works.  Another issue will cover that.

![3 loginpage](https://cloud.githubusercontent.com/assets/11838191/20545000/b7e62de8-b0da-11e6-8b7b-f676217be5e6.jpg)

**Comment by joshi1983** [comment]
You probably should reuse some of the CSS classes and markup used in the sign up page since work on that has been merged.

[http://app.accesslocator.com/signup](http://app.accesslocator.com/signup)

**Comment by areebakamal** [comment]
Wow, looks good! Will do.

**Comment by stephanosm** [comment]
looks good indeed. Great job guys!

**Comment by joshi1983** [comment]
@areebakamal sorry this might make things a little more difficult for you but I actually renamed 'username' to 'email' in the login.blade.php last night.  It might make things more difficult because you may have a rebase conflict if you get latest and have changes to that file in your laptop's branch for issue-62.

The changes that I made are listed under login.blade.php at:
https://github.com/hhaccessibility/hhaccessibility.github.io/pull/80/files#diff-2bdf8e0b2066425c69dd227bf675775b

If that worries you, you can avoid getting latest until tomorrow morning in CAW.  You can push up and I can review your work tonight even if you don't rebase on the latest changes.

**Comment by joshi1983** [comment]
The page looks very much like the UX sketch.  It looks pretty good.

![image](https://cloud.githubusercontent.com/assets/11838191/20862441/965d9192-b978-11e6-97a0-0ae2aea5d3c1.png)

**Comment by stephanosm** [comment]
just for consistency I think it is better to use everywhere the AccessLocator (no space)

**Comment by joshi1983** [comment]
@stephanosm, #85 was created for that.  I'm hoping to get a student working on it.

**Comment by joshi1983** [comment]
If a user is already signed in, should the log in page look or say anything different? Should it say in strong or bold text, "You already are signed in."?

**Comment by stephanosm** [comment]
yes, or "Welcome firstName!"
