### ISSUE TITLE
Indicate Caps Lock is on when typing password

### ISSUE THREAD

**Issue by M4ttoF** [hhaccessibility/hhaccessibility.github.io#621]
Users should be given a warning that caps lock is on when typing their password to avoid frustration.

**Comment by passionInfinite** [comment]
@M4ttoF Nice one but wait for the #615 to get complete Thank you.

**Comment by joshi1983** [comment]
@M4ttoF how do you think it should look?  We use font awesome and Bootstrap has some icons.  Would any of those icon libraries work for indicating Caplock?

**Comment by M4ttoF** [comment]
@passionInfinite Have you pushed the branch you were talking to me on the phone about so I can start working on this?

@joshi1983 We could use this icon with some text next to it to warn the user. Its "exclamation-circle" from font awesome
![image](https://user-images.githubusercontent.com/19508538/42645495-2e3aaee8-85cc-11e8-90e9-166d959922cb.png)

**Comment by passionInfinite** [comment]
Yes it is named as new-version but wait for my go buddy :)

**Comment by singlaneha2205** [comment]
@M4ttoF I tested the issue and is working as expected. The user is given the message indicating the caps is on. We can go ahead and close this issue.

**Comment by joshi1983** [comment]
I'm closing this as Neha tested it and found no problems.
