### ISSUE TITLE
Add phone number to location report

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#625]
We have the phone numbers for about 70% of locations and want to add that to the location report.

The red-circled area would be a great place to show it.
![image](https://user-images.githubusercontent.com/11838191/42603591-722868a6-853c-11e8-9efe-c63050e2eb30.png)

This task would involve modifying resources/views/pages/location_report/collapsed.blade.php.
If any CSS changes are needed, they can be made in resources/assets/sass/_location_map_report.scss.  Use gulp to convert the scss to CSS and test the changes.

Test this with various browser widths from 1500px down to 200px to simulate a desktop, tablet, and mobile phone layout.

**Comment by parth7676** [comment]
<img width="612" alt="changes" src="https://user-images.githubusercontent.com/14904762/42710145-d5b9996a-86b0-11e8-9580-cdcb24ee7bf4.PNG">

@joshi1983  Added phone number and minor css changes. Pull [#627](https://github.com/hhaccessibility/hhaccessibility.github.io/pull/627)

**Comment by joshi1983** [comment]
That looks great, @parth7676 .  I added some comments to the pull request to address some small technical details but it looks great in your screenshot.

**Comment by joshi1983** [comment]
This is ready for testing.

The suggested testing steps are to follow these steps on both desktop and a mobile device:
1. Search for a location that has a phone number on https://app.accesslocator.com
1. View the report for that location and see if the phone number looks good(nice size and layout).
1. Search for a location that has no phone number.
1. View the report and see if the phone number and elements near it look good.

**Comment by singlaneha2205** [comment]
@joshi1983 I tested the above scenario and it is working as expected. You can see the screenshot for reference as below. I think we can go ahead and close the issue.
![image](https://user-images.githubusercontent.com/40703592/43359253-5baae2d2-926d-11e8-9b45-25aa1331cc9a.png)
Without Phone number
![image](https://user-images.githubusercontent.com/40703592/43359257-65f92c3a-926d-11e8-9e2f-6c61c6c6398b.png)

**Comment by joshi1983** [comment]
Thanks for giving it a go, @singlaneha2205.  I'll close now since it was tested by Neha, myself, and Parth.
