### ISSUE TITLE
June focus group testing : accessibility percentage display not useful

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#631]
We need to rethink how we present the accessibility information to the user.
During the focus group testings, the user found showing accessibility percentages confusing than useful. They wondered what was accessible  event if it showed  a high accessibility percentage, instead of the accessibility  information.

User suggested to only show 100% or 0% accessibility, or not use percentages at all. Just show the information.

We have a focus group discussion with the users on Saturday June 21rst, 2018, to cover some of the issues that were found during the focus group testing.

**Comment by M4ttoF** [comment]
We could keep the percentage for users without accounts and change it for users who do. We could just use a Checkmark or X to indicate whether or not the place provides the services they've indicated that they require

**Comment by joshi1983** [comment]
I'm closing this because Matthew made an issue that took over the scope of this issue in #652.
