### ISSUE TITLE
Navigate user to add location feature after signing up from a link on location search

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#634]
When users are not signed in and they search for a location but can't find any, a link to sign in and sign up is shown like this screenshot:
![image](https://user-images.githubusercontent.com/11838191/42894916-3306b8b8-8a86-11e8-8e0d-f65235b16487.png)

We want both the Sign In and Sign Up to navigate back to the add-location feature upon completing the sign in or sign up.  This was completed for Sign In but there is some outstanding changes needed for Sign Up to work.

**Comment by M4ttoF** [comment]
I could start working on this.

@passionInfinite should I wait for you to finish #615 or am I good to go?

**Comment by passionInfinite** [comment]
@m4ttoF I have already completed #615 just waiting for PR to be merged!

**Comment by M4ttoF** [comment]
After looking further into this issue, we would have to change the way we send out emails for this to happen. Users must confirm their email before they log in, so we would have to include the redirect in the verification email we send out to them

**Comment by joshi1983** [comment]
Yes, the emailed link would probably need to change when a redirect parameter is passed to the signup feature.  

There was talk of making a password confirmation resend link feature.  It is probably taking things too far to worry about redirecting to the add location feature after the initial sign up email doesn't get through.

**Comment by joshi1983** [comment]
This will be tricky to test locally due to email not being set up.  Other than getting email set up locally or temporarily commenting out code used to send email, I don't have many suggestions around that.

Essentially breaks down to:
1. Include the redirect parameter in the URL sent to the email link.  Something like: /signup?redirect=/location-add
1. Adjust the signup to redirect to the specified URL if successful.

@jagrutipatel199320 are you interested in this?

**Comment by joshi1983** [comment]
@jagrutipatel199320 will be unavailable to work on this for a month and has no changes implemented yet so another person can take this on.

**Comment by M4ttoF** [comment]
forgot to assign myself while I was working on it, but I made a PR on it

**Comment by joshi1983** [comment]
This work has been merged and deployed to https://app.accesslocator.com.

Suggested test steps are to:
1. Be signed out on https://app.accesslocator.com.
1. Try to find a location that doesn't exist.  Narrow your search radius, add keywords until no location matches the search criteria.
1. Go to the "Table" view for location search and see the buttons for "Sign In" and "Sign Up".
1. Click "Sign Up".
1. Sign up with an email address you don't have an account for.
1. Click the email link.  
1. Click the "Sign in" link on the page.
1. Sign in using your new credentials.
1. Expect to see the location add feature.

**Comment by joshi1983** [comment]
This works.  It hasn't been tested by someone other than the implementer and myself(reviewer) but it clearly works so I'm closing.
