### ISSUE TITLE
Issue with the change password.

### ISSUE THREAD

**Issue by singlaneha2205** [hhaccessibility/hhaccessibility.github.io#643]
When I tried to change the password for my Profile. I found that the flow is accepting my same password as the new password. According to my view, if the user enters the same password as the new password, the user should be given an error message saying the new password can't be the same as the current password. But right now the application is accepting my current password as the new password.

**Comment by joshi1983** [comment]
I think any developer looking for work can do this.   It'll require some PHP changes in the server.

I'm trying to get more of Hardik's pull request for #615 which appears to touch similar code but it seems best to just handle any rebasing issues as we go rather than block someone from working on this.

**Comment by joshi1983** [comment]
Issue #648 is related and @M4ttoF is taking that on so I'm assigning him to this.

**Comment by joshi1983** [comment]
This issue is concerned with Password Change, right?

![image](https://user-images.githubusercontent.com/11838191/43232020-e0b44794-903c-11e8-85e8-695285a83436.png)

**Comment by joshi1983** [comment]
@singlaneha2205 you wrote the issue so basically test that it behaves the way you want.

It is deployed on https://app.accesslocator.com so test there.

**Comment by singlaneha2205** [comment]
@joshi1983 I tested he above issue it is working as expected now. The application is not accepting the same old password as the new password. We can g ahead and close the issue

**Comment by joshi1983** [comment]
Thanks for testing, Neha.  I'll close.
