### ISSUE TITLE
Make users stay logged in for 24 hours

### ISSUE THREAD

**Issue by M4ttoF** [hhaccessibility/hhaccessibility.github.io#650]
To make things easier for the users, we discussed that it would be best to enable them to stay logged in for a longer amount of time

**Comment by joshi1983** [comment]
I think this would involve updating lifetime in app/config/session.php:

``    'lifetime' => 120,```

I think the 120 is the number of minutes that the session should last.

**Comment by joshi1983** [comment]
This is ready for testing on https://app.accesslocator.com.

The testing method I suggest is pretty different.  I didn't actually test this so it'll be important to do this.
1. Sign into https://app.accesslocator.com/signin
1. Keep your browser tab open for 2 and a half hours.  The old life span was 2 hours and the extra half hour would be a generous buffer.  If your internet cuts out, that shouldn't interfere with the test but be sure not to click anywhere in the site for the full 2 and a half hour interval in case that throws off the results.
1. Click the Home link.  Are you still signed in?  Can you go back to the profile without reentering credentials?

**Comment by singlaneha2205** [comment]
@joshi1983 I tested the above issue and user remains logged in after 2.5 hours on inactivity. I think its working fine. We can go ahead and close the issue.

**Comment by joshi1983** [comment]
Great.  Thanks for patiently waiting for it.

I'll close now.
