### ISSUE TITLE
Make search results start with a map

### ISSUE THREAD

**Issue by M4ttoF** [hhaccessibility/hhaccessibility.github.io#651]
It would be best for users if they could first view the map, and then opt to switch to the table view as the map is more visually friendly

**Comment by joshi1983** [comment]
If signed in and the associated account indicates that a screen reader is used, it would still be good to redirect to the table by default.

**Comment by M4ttoF** [comment]
@joshi1983 
Made a new commit and that's now covered in #653

**Comment by M4ttoF** [comment]
PR has been merged so I'm going to close this issue

**Comment by joshi1983** [comment]
I agree this was good to close.  Usually we get someone like @singlaneha2205 to test before closing but this issue looked very simple.
