### ISSUE TITLE
Location suggestion dialog improvements

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#669]
@Henry-Hao has been implementing lots of suggested edit changes for #461 including the suggestion edit feature we have merged in master and deployed on https://app.accesslocator.com.

To see the new location suggestion feature:
1. Sign in.
1. Find a location and view its location report.
1. Click either the "Update Suggestions" button or the bug icon near the upper-right.

While Henry is finishing more work on a suggestion review feature, someone else can make our suggestion dialog more user-friendly.  These improvements would include:
- [x] Highlight fields that are different from the current location fields.  It is difficult to know what fields have suggested changes right now.  If a black border or some marker showed next to fields that aren't exactly the same as original, that would help.
- [x] Validate that at least 1 field was updated.  If nothing was updated when "Confirm" is clicked, show the message in the same place as other validation messages from the server.  It is possible to submit a suggestion without any suggested changes right now.  That is both useless data for AccessLocator to manage and probably means that the user submitted by mistake and nothing is warning them.  This validation could be put in PHP or JavaScript.  That is up to you.
- [x] Disable the buttons at the bottom of the form while an HTTP request is in transit.  For now, it is possible to type a suggestion and then hit the "Confirm" button repeatedly causing multiple suggestion records to be saved.  Disabling those buttons would prevent the creation of multiple identical suggestion records.  Disabling the buttons would also prevent closing the dialog before seeing the server's response.

Here's a screenshot just to clarify the suggestion dialog feature this is dealing with:
![image](https://user-images.githubusercontent.com/11838191/43357151-2d90b1fa-924b-11e8-8f26-37b5e1e2955f.png)

**Comment by joshi1983** [comment]
@parth7676 do you want to work on this?

**Comment by joshi1983** [comment]
I passed these improvement ideas by Henry and he agreed with them.

**Comment by Blandine-AA** [comment]
Is @Henry-Hao working on this?

**Comment by joshi1983** [comment]
@Henry-Hao do you want to work on it?  I didn't hear from @parth7676 in 3 weeks which is probably his way of say, "No, I'm not interested in working on this.".

**Comment by Henry-Hao** [comment]
@joshi1983 Ok, I will do it these days.

**Comment by joshi1983** [comment]
ok sure.  I assigned you.  Let me know if you run into trouble.

@parth7676 thanks for your help on other issues.  Let me know if or when you want to get more practice from AccessLocator or see some tasks of more interest to you.

**Comment by Henry-Hao** [comment]
@joshi1983 In subtask 2, instead of the message, what about simply disable the submit button when the suggestion is the same as the original since this suggestion is useless?

**Comment by joshi1983** [comment]
The changes from Henry were merged and deployed to https://app.accesslocator.com.  This is ready for testing.

**Comment by joshi1983** [comment]
This hasn't been tested by a third person who wasn't involved with implementation and review but it should be good anyway so I'm closing the issue.
