### ISSUE TITLE
Inconsistency on location report page!

### ISSUE THREAD

**Issue by singlaneha2205** [hhaccessibility/hhaccessibility.github.io#670]
While going through different locations  I noticed that we have inconsistency on location page. For some locations we have buttons displayed as Suggest Updates, Accommodation and so on, while for others we have icons for the same features. I think it should be uniform across the application. Please refer to below screenshots for further reference.
Buttons with names:
![untitled](https://user-images.githubusercontent.com/40703592/43359372-53ab1f8c-926f-11e8-95a8-bab59a6d3011.png)

Buttons With Icons:
![untitled](https://user-images.githubusercontent.com/40703592/43359366-2c2ea2b2-926f-11e8-84db-29c27d9e9de7.png)

**Comment by joshi1983** [comment]
Those buttons can use some improvements but the decision between icons and words is intended to be based on a mixture of available space and the number of buttons.  In those screenshots, there are more buttons in the case that uses icons.

**Comment by joshi1983** [comment]
I can't think of a better way to handle these buttons.  The issue was originally made based on a misunderstanding of how the icons and button text are determined rather than it really being a bug.  I think it is working as well as possible.
