### ISSUE TITLE
Location name overlapping with Universal and Personal button.

### ISSUE THREAD

**Issue by singlaneha2205** [hhaccessibility/hhaccessibility.github.io#671]
While going through different location. When I navigated to location "University of Windsor Conference and accommodation center"  I noticed that the name of the location overlap with the Universal and Personal buttons. Please refer to below screenshot.
![untitled](https://user-images.githubusercontent.com/40703592/43359437-7625f91e-9270-11e8-85b3-17a6c1945ffa.png)

**Comment by joshi1983** [comment]
http://michikono.github.io/boxfit/ may be useful for shrinking the text when it gets too long for the available space.

**Comment by joshi1983** [comment]
The fixes were deployed to https://app.accesslocator.com.

The specific location was mentioned at:
![image](https://user-images.githubusercontent.com/11838191/44007144-754b950e-9e5e-11e8-8470-a50a838caa57.png)

Here's a link if it helps:
https://app.accesslocator.com/location/report/00000000-0000-0000-0000-000000010270

A location with the longest name is at:
https://app.accesslocator.com/location/report/00000000-0000-0000-0000-000000002476

The changes I made should affect all locations with long names.  It decreases the font size to fit them into the available space on the location report and location rating features.  Really long names still wrap but use reduced font sizes so they don't go to more lines than necessary to keep the text readable.

To test these changes, I suggest:
1. Viewing the report for locations with a range of name lengths.
1. See if the location names aren't overlapped by anything in the location report or location rating feature.
1. If you visit a location from the location search feature, it'll add an extra search icon which increases the likelihood that the name will be overlapped or wrap.  Use the search feature if you a name looks really close to getting cut off.

**Comment by joshi1983** [comment]
I unassigned @singlaneha2205 so any volunteer can feel free to test this.

**Comment by joshi1983** [comment]
I'm confident enough with this to not wait any longer for another person to test.
