### ISSUE TITLE
Remove Search Location and Search Radius from Profile

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#695]
The search location and search radius are used in the home and location search features.  There is no good reason to have it in the profile and the profile page is already the most tall and complex layout in AccessLocator.  The extra height lead to focus group testers complaining that they couldn't find the 'Save Profile' button.

![image](https://user-images.githubusercontent.com/11838191/47276649-99f36800-d586-11e8-8c07-bf32b340c0d8.png)

This will resolve #538 and #613 .

**Comment by joshi1983** [comment]
This is ready for testing on app.accesslocator.com.

**Comment by stephanosm** [comment]
passed!
