### ISSUE TITLE
Make home page look similar to mockup

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#72]
Make the home page look more like the UX sketch from Areeba.

Here is the UX sketch:
![unnamed](https://cloud.githubusercontent.com/assets/11838191/20643020/77b85a2a-b3eb-11e6-9d10-62b4f2d75215.jpg)

Here is the background image used from the sketch:
![accesbilitybackground](https://cloud.githubusercontent.com/assets/11838191/20643084/f1e795d0-b3ec-11e6-9f26-9b65ee8ffd5a.jpg)

**Comment by joshi1983** [comment]
I'm closing because the home page looks a lot like the mockup after merging.

**Comment by joshi1983** [comment]
Should the Login / Sign up button be removed when the user is already signed in?

It just might confuse some users to see options for signing in when they already signed in.

**Comment by Blandine-AA** [comment]
Normally, after signing in, le login/sign-up button should not be visible anymore.
On the menu bar or somewhere on the top left, we should have a logout /sign out button.

We will need to discuss how we want the menu bar with all those functionalities (access to profile, logout, ...) to look like.

**Comment by joshi1983** [comment]
ok.  I'll handle the removal of the Login/Sign up button on the home page pretty soon.  I'll wait for that extra discussion before changing the menu.

Some sites show the person's name on every page but Areeba might have some good ideas regarding how to convey that the user is signed in.
