### ISSUE TITLE
Define a Privacy Policy for AccessLocator

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#730]
facebook.com authentication strongly cautions users that their personal information isn't secure when signing up.  Getting facebook authentication to trust AccessLocator enough to not warn visitors like we've done something horribly wrong requires us to complete a few things including a privacy policy.

A privacy policy was started at: https://app.accesslocator.com/privacy-policy.
It needs review and potential improvements.

**Comment by joshi1983** [comment]
@stephanosm can you look over my initial draft of our privacy policy and let me know if you want any improvements?

**Comment by stephanosm** [comment]
I read it and I believe it is ok.

**Comment by joshi1983** [comment]
Great thanks.
