### ISSUE TITLE
Load Recovery Reply To Email from .env file

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#734]
We don't want anyone's email address tracked in the repository.  We want them maintained in the .env file.

For now, the reply to email address is hard coded in PasswordRecoveryController.php.

**Comment by joshi1983** [comment]
@hari2684 did you want to take this on?

**Comment by hariharan2684** [comment]
ok

**Comment by joshi1983** [comment]
Nice.  Thanks.

Since some changes were merged that affected files you'll update in this issue, it is important to get latest before working on this.

There are instructions on how to get the latest merged changes at:
https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/git-commands

![image](https://user-images.githubusercontent.com/11838191/50522390-d799d300-0a98-11e9-8870-ce3bf2aee5eb.png)
You can skip the step of adding an upstream remote since you've already done that.  I crossed it out in the screenshot to be clear.

**Comment by joshi1983** [comment]
Thanks Hariharan.  It has been merged and deployed.

I'm closing this since I tested the changes and there isn't much reason to wait for a third person to test these changes.
