### ISSUE TITLE
Add HTTPS support for app.accesslocator.com

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#77]
Add HTTPS support because we'll be receiving passwords from the sign in and sign up forms and want those encrypted before they pass through multiple computers on their way to our server.  Letting a user's password be seen by third parties would be irresponsible of us.

The following links may be helpful:
- https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-apache-for-ubuntu-14-04
- https://www.digicert.com/ssl-certificate-installation-ubuntu-server-with-apache2.htm

**Comment by joshi1983** [comment]
yay!  https://app.accesslocator.com/ works.

**Comment by brucelau-github** [comment]
following this instruction
https://certbot.eff.org/#ubuntuxenial-apache

**Comment by joshi1983** [comment]
I assigned this to Bruce since he's investigating to be more sure about if there's a way to get an SSL certificate published for our domain for free.  It seems unlikely so far.

**Comment by Blandine-AA** [comment]
@joshi1983 @brucelau-github 

Please provide feedback if this should be included in our next milestone for demo release version 0.0.2

**Comment by joshi1983** [comment]
The 0.0.2 milestone has passed and this was not included.

https://letsencrypt.org/ also seems to act as a free certificate authority according to a reference found at https://css-tricks.com/just-another-https-nudge/#more-251929.  When you get time, @brucelau-github can you look into that?  If you find something you want to test, you could try with app.accesslocator.com.  This doesn't have a solid deadline for the next few months but could lead to our site not publishing(leaving unencrypted) our test passwords to everyone between the web browser and Digital Ocean which would be nice.

**Comment by joshi1983** [comment]
Along with letsencrypt.org, I was told by someone attending last night's Hackforge event on encryption that you could use https://certbot.eff.org/ and a couple commands to get it working.

**Comment by Blandine-AA** [comment]
Moving to release 0.0.4 to better track the issue.

**Comment by joshi1983** [comment]
@passionInfinite got this to work without the warning message.  Thanks, Hardik.

**Comment by passionInfinite** [comment]
@joshi1983  Thanks @joshi1983. Add this to label ready to test as this is for app.accesslocator.com
For demo.accesslocator.com we need to wait for sometimes as we have issued many certs. I will add SSL to demo.accesslocator.com as it will become available.

**Comment by passionInfinite** [comment]
@Blandine-AA Following are some steps to perform testing:

1) Open particular link (app.accesslocator.com)
2) Click on Secure (It should be green)
3) Click on Valid under the certificate.
4) It will open certificate viewer.
5) Check the Common Name in Issued To, it should be same as the domain URL you are visiting. (app.accesslocator.com).
6) Check the Common Name in Issued From, it should be Let's Encrypt Authority X3.

**Comment by passionInfinite** [comment]
@joshi1983 No updates on this! Close this as it is already tested.

**Comment by singlaneha2205** [comment]
@joshi1983 and @Blandine-AA  I tested this issue and was able to test it successfully for IE, Chrome, and Firefox. We can go ahead and close the issue.
![image](https://user-images.githubusercontent.com/40703592/42404156-e9dc01aa-8154-11e8-8276-34514172d3ee.png)
![image](https://user-images.githubusercontent.com/40703592/42404166-fbea5c84-8154-11e8-9d07-c6d094650d25.png)
![image](https://user-images.githubusercontent.com/40703592/42404176-0ecc6360-8155-11e8-8b31-792192ea8e2f.png)

**Comment by joshi1983** [comment]
Thanks.
