### ISSUE TITLE
Contact form : add captcha

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#95]
Captcha to be accessible - provide audio option too

**Comment by joshi1983** [comment]
Anyone working on this should use the same captcha solution used in #96.

**Comment by brucelau-github** [comment]
merged with issue#96 fixed

**Comment by joshi1983** [comment]
Bruce, don't merge.  I'll have to revert now.  I wanted to review first and only merge after it was good.  I'm glad you made a pull request but I wanted the opportunity to review.

**Comment by joshi1983** [comment]
I reset as if you didn't merge.  Recreate your pull request but don't merge.  There are some changes I want you to make with your work.  They aren't big but I don't want them merged until they're made.   Thanks for the work so far.

**Comment by brucelau-github** [comment]
Okay, I thought I do not familiar with the pull request function. It said there is no conflict so I click that button. :) Sorry about that. Next time I will just invoke a new pull request.

**Comment by joshi1983** [comment]
This is available at app.accesslocator.com and working well.  Thanks, Bruce.  I'm closing now that Blandine and others can see it working.
