### ISSUE TITLE
Sign Up page : add captcha

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#96]
Captcha to be accessible - provide audio functionality

**Comment by joshi1983** [comment]
This may help:
https://laravel-news.com/laravel-no-captcha-recaptcha

This article makes Google's "no captcha" or "recaptcha" is one of the most accessible versions of captcha available.  It works with screen readers, people with dyslexia, and poor vision.
http://simplyaccessible.com/article/googles-no-captcha/

**Comment by brucelau-github** [comment]
add recaptcha on contact form and signup form
![contact recaptcha](https://cloud.githubusercontent.com/assets/22227484/21442263/ceb84f22-c86a-11e6-95af-6ee300fd15b3.png)
![recaptcha](https://cloud.githubusercontent.com/assets/22227484/21442266/d40f55f6-c86a-11e6-879e-4d1187f1fbb5.png)

**Comment by joshi1983** [comment]
Great.  I'll review your pull request.  I reopened because it isn't really resolved until it gets merged and I'll have to review the pull request before it gets merged.  I'd also like to deploy it to app.accesslocator.com so Blandine and others can see the work completed too.

**Comment by joshi1983** [comment]
This is working at [app.accesslocator.com](http://app.accesslocator.com).  Thanks Bruce
