### ISSUE TITLE
Testing : create a test environment subdomain

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#97]
Create a subdomain for testing : test.accesslocator.com

**Comment by joshi1983** [comment]
@Blandine-AA , I can do that quickly.  Do you want it to have the current state of the application for now?  I guess it'll be clear when you want it updated.

I'll keep app.accesslocator.com very close to our latest work and test.accesslocator.com will be stable and get out of date as long as you like.

**Comment by joshi1983** [comment]
[test.accesslocator.com](http://test.accesslocator.com) is now available.  It is exactly the same as app.accesslocator.com for now.

**Comment by joshi1983** [comment]
I'm closing this issue since the issue description merely asks for a working subdomain which is completed.
